// Table measured on Java (JDK 21.0.2) by the probe `ProbeDupe.java`
// (maintainer-only probe): `ContestDupeChecker`
// (scope, session, letter case, spaces, null) and `Tour.session`. The rows are
// not edited by hand — they are regenerated by the script `gen_swift.py`.

@testable import MCLCore

enum DupeMeasured {
    /// A case step: `add`/`dupe` = call, band, mode, ownQth, epochSecond (`nil` = Java `null`).
    enum Step: Sendable {
        case add(String?, String?, String?, String?, Int64?)
        case dupe(String?, String?, String?, String?, Int64?)
        case reset
    }

    struct Row: Sendable, CustomStringConvertible {
        let name: String
        /// `~` = a definition without `dupe`, `NODUPE` = `dupe` without `scope`, otherwise the scope name.
        let scope: String
        let tour: String?
        let steps: [Step]
        /// `isDupe` results in the order of the `dupe` steps.
        let java: [Bool]
        var description: String { name }
    }

    enum SessionOutcome: Sendable, Equatable {
        case empty
        /// startMinute, durationMinutes, session number.
        case session(Int, Int, Int64)
    }

    struct SessionRow: Sendable, CustomStringConvertible {
        let tour: String?
        let epochSecond: Int64
        let nanos: Int
        let java: SessionOutcome
        init(_ tour: String?, _ epochSecond: Int64, _ nanos: Int, _ java: SessionOutcome) {
            self.tour = tour
            self.epochSecond = epochSecond
            self.nanos = nanos
            self.java = java
        }
        var description: String { "\(tour ?? "nil") @\(epochSecond).\(nanos)" }
    }

    static let rows: [Row] = [
        Row(name: "per-band", scope: "PER_BAND", tour: nil,
            steps: [.add("OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "20m", "SSB", nil, nil), .dupe("OK1AA", "40m", "CW", nil, nil), .dupe("OK1AB", "20m", "CW", nil, nil)],
            java: [true, true, false, false]),
        Row(name: "per-band-mode", scope: "PER_BAND_MODE", tour: nil,
            steps: [.add("OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "20m", "SSB", nil, nil), .dupe("OK1AA", "40m", "CW", nil, nil)],
            java: [true, false, false]),
        Row(name: "per-mode", scope: "PER_MODE", tour: nil,
            steps: [.add("OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "40m", "CW", nil, nil), .dupe("OK1AA", "20m", "SSB", nil, nil)],
            java: [true, true, false]),
        Row(name: "once", scope: "ONCE", tour: nil,
            steps: [.add("OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "40m", "SSB", nil, nil), .dupe("OK1AB", "40m", "SSB", nil, nil)],
            java: [true, true, false]),
        Row(name: "default-no-dupe", scope: "~", tour: nil,
            steps: [.add("OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "40m", "CW", nil, nil)],
            java: [true, false]),
        Row(name: "default-no-scope", scope: "NODUPE", tour: nil,
            steps: [.add("OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "40m", "CW", nil, nil)],
            java: [true, false]),
        Row(name: "nil-band-per-band", scope: "PER_BAND", tour: nil,
            steps: [.add("OK1AA", nil, "CW", nil, nil), .dupe("OK1AA", nil, "CW", nil, nil), .dupe("OK1AA", "null", "CW", nil, nil), .dupe("OK1AA", "20m", "CW", nil, nil)],
            java: [true, true, false]),
        Row(name: "literal-null-band", scope: "PER_BAND", tour: nil,
            steps: [.add("OK1AA", "null", "CW", nil, nil), .dupe("OK1AA", nil, "CW", nil, nil), .dupe("OK1AA", "null", "SSB", nil, nil)],
            java: [true, true]),
        Row(name: "nil-mode-per-mode", scope: "PER_MODE", tour: nil,
            steps: [.add("OK1AA", "20m", nil, nil, nil), .dupe("OK1AA", "40m", nil, nil, nil), .dupe("OK1AA", "40m", "null", nil, nil), .dupe("OK1AA", "40m", "CW", nil, nil)],
            java: [true, true, false]),
        Row(name: "nil-both-band-mode", scope: "PER_BAND_MODE", tour: nil,
            steps: [.add("OK1AA", nil, nil, nil, nil), .dupe("OK1AA", nil, nil, nil, nil), .dupe("OK1AA", "null", "null", nil, nil), .dupe("OK1AA", nil, "CW", nil, nil)],
            java: [true, true, false]),
        Row(name: "pipe-collision-band-mode", scope: "PER_BAND_MODE", tour: nil,
            steps: [.add("OK1AA", "a|b", "c", nil, nil), .dupe("OK1AA", "a", "b|c", nil, nil), .dupe("OK1AA", "a|b", "c", nil, nil)],
            java: [true, true]),
        Row(name: "pipe-collision-call", scope: "PER_BAND", tour: nil,
            steps: [.add("A|20m", "20m", "CW", nil, nil), .dupe("A", "20m|20m", "CW", nil, nil), .dupe("A|20m", "20m", "CW", nil, nil)],
            java: [false, true]),
        Row(name: "pipe-call-qth", scope: "PER_BAND", tour: nil,
            steps: [.add("OK1AA|20m", "30m", "CW", nil, nil), .dupe("OK1AA", "20m|30m", "CW", nil, nil)],
            java: [false]),
        Row(name: "call-case", scope: "PER_BAND", tour: nil,
            steps: [.add("ok1aa", "20m", "CW", nil, nil), .dupe("OK1AA", "20m", "CW", nil, nil), .dupe("Ok1Aa", "20m", "CW", nil, nil)],
            java: [true, true]),
        Row(name: "call-trim", scope: "PER_BAND", tour: nil,
            steps: [.add("  OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA ", "20m", "CW", nil, nil), .dupe("\u{9}OK1AA\u{A}", "20m", "CW", nil, nil), .dupe("\u{1}OK1AA ", "20m", "CW", nil, nil)],
            java: [true, true, true, true]),
        Row(name: "call-nbsp-not-trimmed", scope: "PER_BAND", tour: nil,
            steps: [.add("\u{A0}OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "20m", "CW", nil, nil), .dupe("\u{A0}OK1AA", "20m", "CW", nil, nil), .dupe("\u{A0}ok1aa", "20m", "CW", nil, nil), .dupe("\u{2003}OK1AA", "20m", "CW", nil, nil)],
            java: [false, true, true, false]),
        Row(name: "call-inner-space", scope: "PER_BAND", tour: nil,
            steps: [.add("OK1 AA", "20m", "CW", nil, nil), .dupe("OK1AA", "20m", "CW", nil, nil), .dupe("ok1 aa", "20m", "CW", nil, nil)],
            java: [false, true]),
        Row(name: "call-empty-vs-null", scope: "PER_BAND", tour: nil,
            steps: [.add(nil, "20m", "CW", nil, nil), .dupe(nil, "20m", "CW", nil, nil), .dupe(" ", "20m", "CW", nil, nil), .dupe("", "20m", "CW", nil, nil), .dupe("null", "20m", "CW", nil, nil), .dupe("NULL", "20m", "CW", nil, nil)],
            java: [true, true, true, false, false]),
        Row(name: "call-only-blanks", scope: "PER_BAND", tour: nil,
            steps: [.add("  ", "20m", "CW", nil, nil), .dupe(nil, "20m", "CW", nil, nil), .dupe("", "20m", "CW", nil, nil)],
            java: [true, true]),
        Row(name: "call-uppercase-special", scope: "PER_BAND", tour: nil,
            steps: [.add("stra\u{DF}e", "20m", "CW", nil, nil), .dupe("STRASSE", "20m", "CW", nil, nil), .dupe("stra\u{DF}e", "20m", "CW", nil, nil), .dupe("STRA\u{1E9E}E", "20m", "CW", nil, nil)],
            java: [true, true, false]),
        Row(name: "call-uppercase-turkish-i", scope: "PER_BAND", tour: nil,
            steps: [.add("\u{131}", "20m", "CW", nil, nil), .dupe("I", "20m", "CW", nil, nil), .dupe("i", "20m", "CW", nil, nil), .dupe("\u{130}", "20m", "CW", nil, nil)],
            java: [true, true, false]),
        Row(name: "call-final-sigma", scope: "PER_BAND", tour: nil,
            steps: [.add("\u{3C3}\u{3C2}", "20m", "CW", nil, nil), .dupe("\u{3A3}\u{3A3}", "20m", "CW", nil, nil)],
            java: [true]),
        Row(name: "call-kelvin", scope: "PER_BAND", tour: nil,
            steps: [.add("\u{212A}", "20m", "CW", nil, nil), .dupe("K", "20m", "CW", nil, nil), .dupe("k", "20m", "CW", nil, nil)],
            java: [false, false]),
        Row(name: "call-canonical-equivalent", scope: "PER_BAND", tour: nil,
            steps: [.add("\u{C5}", "20m", "CW", nil, nil), .dupe("A\u{30A}", "20m", "CW", nil, nil), .dupe("\u{212B}", "20m", "CW", nil, nil)],
            java: [false, false]),
        Row(name: "call-not-bmp", scope: "PER_BAND", tour: nil,
            steps: [.add("\u{10428}", "20m", "CW", nil, nil), .dupe("\u{10400}", "20m", "CW", nil, nil)],
            java: [true]),
        Row(name: "band-case", scope: "PER_BAND", tour: nil,
            steps: [.add("OK1AA", "20M", "CW", nil, nil), .dupe("OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "20M", "CW", nil, nil)],
            java: [false, true]),
        Row(name: "mode-case", scope: "PER_MODE", tour: nil,
            steps: [.add("OK1AA", "20m", "cw", nil, nil), .dupe("OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "40m", "cw", nil, nil)],
            java: [false, true]),
        Row(name: "band-canonical-vs-utf16", scope: "PER_BAND", tour: nil,
            steps: [.add("OK1AA", "\u{C5}", "CW", nil, nil), .dupe("OK1AA", "A\u{30A}", "CW", nil, nil), .dupe("OK1AA", "\u{C5}", "CW", nil, nil)],
            java: [false, true]),
        Row(name: "qth", scope: "PER_BAND", tour: nil,
            steps: [.add("OK1AA", "20m", "CW", "JN89", nil), .dupe("OK1AA", "20m", "CW", "JN89", nil), .dupe("OK1AA", "20m", "CW", "jn89", nil), .dupe("OK1AA", "20m", "CW", "JN89 ", nil), .dupe("OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "20m", "CW", "", nil), .dupe("OK1AA", "20m", "CW", "JN88", nil)],
            java: [true, false, false, false, false, false]),
        Row(name: "qth-null-is-empty", scope: "PER_BAND", tour: nil,
            steps: [.add("OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "20m", "CW", "", nil), .dupe("OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "20m", "CW", "null", nil)],
            java: [true, true, false]),
        Row(name: "qth-once", scope: "ONCE", tour: nil,
            steps: [.add("OK1AA", "20m", "CW", "JN89", nil), .dupe("OK1AA", "40m", "SSB", "JN89", nil), .dupe("OK1AA", "40m", "SSB", "JN88", nil)],
            java: [true, false]),
        Row(name: "reset", scope: "PER_BAND", tour: nil,
            steps: [.add("OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "20m", "CW", nil, nil), .reset, .dupe("OK1AA", "20m", "CW", nil, nil), .add("OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "20m", "CW", nil, nil)],
            java: [true, false, true]),
        Row(name: "idempotent", scope: "PER_BAND", tour: nil,
            steps: [.dupe("OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "20m", "CW", nil, nil), .add("OK1AA", "20m", "CW", nil, nil), .add("OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "20m", "CW", nil, nil), .reset, .dupe("OK1AA", "20m", "CW", nil, nil)],
            java: [false, false, true, false]),
        Row(name: "tour-same-session", scope: "PER_BAND", tour: "1200/60",
            steps: [.add("OK1AA", "20m", "CW", nil, 46800), .dupe("OK1AA", "20m", "CW", nil, 46800), .dupe("OK1AA", "20m", "CW", nil, 50399), .dupe("OK1AA", "20m", "CW", nil, 50400), .dupe("OK1AA", "20m", "CW", nil, 46799), .dupe("OK1AA", "20m", "CW", nil, 43200), .dupe("OK1AA", "20m", "CW", nil, 43199)],
            java: [true, true, false, false, false, false]),
        Row(name: "tour-null-instant", scope: "PER_BAND", tour: "1200/60",
            steps: [.add("OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "20m", "CW", nil, 46800), .add("OK1AA", "20m", "CW", nil, 46800), .dupe("OK1AA", "20m", "CW", nil, nil), .dupe("OK1AA", "20m", "CW", nil, 46800)],
            java: [true, false, true, true]),
        Row(name: "tour-with-null-instant-added-in-session", scope: "PER_BAND", tour: "1200/60",
            steps: [.add("OK1AA", "20m", "CW", nil, 46800), .dupe("OK1AA", "20m", "CW", nil, nil)],
            java: [false]),
        Row(name: "tour-negative-time", scope: "PER_BAND", tour: "1200/60",
            steps: [.add("OK1AA", "20m", "CW", nil, -1), .dupe("OK1AA", "20m", "CW", nil, -1), .dupe("OK1AA", "20m", "CW", nil, -3000), .dupe("OK1AA", "20m", "CW", nil, -3600), .dupe("OK1AA", "20m", "CW", nil, -3601), .dupe("OK1AA", "20m", "CW", nil, 0), .dupe("OK1AA", "20m", "CW", nil, -43201)],
            java: [true, true, true, false, false, false]),
        Row(name: "tour-offset-start", scope: "PER_BAND", tour: "1230/30",
            steps: [.add("OK1AA", "20m", "CW", nil, 45000), .dupe("OK1AA", "20m", "CW", nil, 45000), .dupe("OK1AA", "20m", "CW", nil, 46799), .dupe("OK1AA", "20m", "CW", nil, 46800), .dupe("OK1AA", "20m", "CW", nil, 44999)],
            java: [true, true, false, false]),
        Row(name: "tour-once-two-sessions", scope: "ONCE", tour: "0000/60",
            steps: [.add("OK1AA", "20m", "CW", nil, 0), .dupe("OK1AA", "40m", "SSB", nil, 3599), .dupe("OK1AA", "40m", "SSB", nil, 3600)],
            java: [true, false]),
        Row(name: "tour-per-band-mode", scope: "PER_BAND_MODE", tour: "1200/60",
            steps: [.add("OK1AA", "20m", "CW", "JN89", 46800), .dupe("OK1AA", "20m", "CW", "JN89", 46800), .dupe("OK1AA", "20m", "SSB", "JN89", 46800), .dupe("OK1AA", "20m", "CW", "JN88", 46800), .dupe("OK1AA", "20m", "CW", "JN89", 50400)],
            java: [true, false, false, false]),
        Row(name: "tour-1440-quirk", scope: "PER_BAND", tour: "1200/1440",
            steps: [.add("OK1AA", "20m", "CW", nil, 0), .dupe("OK1AA", "20m", "CW", nil, 52799), .dupe("OK1AA", "20m", "CW", nil, 52800), .dupe("OK1AA", "20m", "CW", nil, 43200)],
            java: [false, false, false]),
    ]

    static let sessions: [SessionRow] = [
        SessionRow("1200/60", 43200, 0, .session(720, 60, 0)),
        SessionRow("1200/60", 43199, 0, .session(720, 60, -1)),
        SessionRow("1200/60", 46799, 0, .session(720, 60, 0)),
        SessionRow("1200/60", 46800, 0, .session(720, 60, 1)),
        SessionRow("1200/60", 0, 0, .session(720, 60, -12)),
        SessionRow("1200/60", -1, 0, .session(720, 60, -13)),
        SessionRow("1200/60", -1, 999999999, .session(720, 60, -13)),
        SessionRow("1200/60", -43200, 0, .session(720, 60, -24)),
        SessionRow("1200/60", -43201, 0, .session(720, 60, -25)),
        SessionRow("1200/60", -46800, 0, .session(720, 60, -25)),
        SessionRow("1200/60", -46801, 0, .session(720, 60, -26)),
        SessionRow("1200/60", -59, 0, .session(720, 60, -13)),
        SessionRow("1200/60", 59, 999999999, .session(720, 60, -12)),
        SessionRow("1200/60", 60, 0, .session(720, 60, -12)),
        SessionRow("0000/5", 0, 0, .session(0, 5, 0)),
        SessionRow("0000/5", 299, 0, .session(0, 5, 0)),
        SessionRow("0000/5", 300, 0, .session(0, 5, 1)),
        SessionRow("0000/5", -1, 0, .session(0, 5, -1)),
        SessionRow("0000/5", -300, 0, .session(0, 5, -1)),
        SessionRow("0000/5", -301, 0, .session(0, 5, -2)),
        SessionRow("2359/5", 86339, 0, .session(1439, 5, -1)),
        SessionRow("2359/5", 86340, 0, .session(1439, 5, 0)),
        SessionRow("2359/5", 86640, 0, .session(1439, 5, 1)),
        SessionRow("2359/5", 86639, 0, .session(1439, 5, 0)),
        SessionRow("1200/30", 1000000000, 0, .session(720, 30, 555531)),
        SessionRow("1200/30", 1700000000, 500000000, .session(720, 30, 944420)),
        SessionRow("1200/1440", 0, 0, .session(720, 880, -1)),
        SessionRow("1200/1440", 52799, 0, .session(720, 880, 0)),
        SessionRow("1200/1440", 52800, 0, .session(720, 880, 0)),
        SessionRow("1200/1440", -52800, 0, .session(720, 880, -2)),
        SessionRow("1200/1440", -52801, 0, .session(720, 880, -2)),
        SessionRow("1200/0030", 45000, 0, .session(720, 30, 1)),
        SessionRow("1200/0100", 46800, 0, .session(720, 60, 1)),
        SessionRow("1200/1000", 46800, 0, .session(720, 600, 0)),
        SessionRow("1200/9999", 0, 0, .session(720, 6039, -1)),
        SessionRow("1200/9999", 599940, 0, .session(720, 6039, 1)),
        SessionRow("1200/9999", 599939, 0, .session(720, 6039, 1)),
        SessionRow("1200/5", -31557014167219200, 0, .session(720, 5, -105190047224208)),
        SessionRow("1200/5", 31556889864403199, 999999999, .session(720, 5, 105189632881199)),
        SessionRow("0000/60", -31557014167219200, 0, .session(0, 60, -8765837268672)),
        SessionRow("0000/60", 31556889864403199, 0, .session(0, 60, 8765802740111)),
        SessionRow("2359/5", -31557014167219200, 0, .session(1439, 5, -105190047224352)),
        SessionRow("0000/5", 31556889864403199, 0, .session(0, 5, 105189632881343)),
        SessionRow("1200/4", 0, 0, .empty),
        SessionRow("2400/60", 0, 0, .empty),
        SessionRow(nil, 0, 0, .empty),
    ]
}
