// Table measured on Java (JDK 21.0.2) by the probe `ProbeMultiplier.java`
// (maintainer-only probe): `MultiplierEvaluator.preview/commit`
// over `QsoContextFactory.build`, `MultiplierTracker` and the `ScoreEngine.compute` counts after each step.
// The rows are not edited by hand — they are regenerated by the script `gen_swift.py`. The result is the probe text
// (`MultiplierEvaluatorTests.describe` composes it the same way); the `@file` definition is from the fixtures.

import Testing
@testable import MCLCore

enum MultiplierMeasured {
    /// Fields of the received exchange (`receivedRaw`); a `nil` key/value = Java `null`.
    struct Field: Sendable {
        let key: String?
        let value: String?
        init(_ key: String?, _ value: String?) {
            self.key = key
            self.value = value
        }
    }

    enum Input: Sendable {
        /// callsign, band, mode, received fields (`nil` = null map)
        case preview(String?, String?, String?, [Field]?)
        case commit(String?, String?, String?, [Field]?)
        /// operation A/R/W/D/K/N, binding, scope, key — directly over the scenario's tracker
        case tracker(String, String?, String?, String?)
    }

    struct Step: Sendable {
        let input: Input
        /// The Java result of a step and the score counts after it (`-` for tracker operations).
        let result: String
        let score: String
        init(_ input: Input, _ result: String, _ score: String) {
            self.input = input
            self.result = result
            self.score = score
        }
    }

    struct Scenario: Sendable, CustomTestStringConvertible {
        let name: String
        /// `@file` from the fixtures `contest-data/contests`, otherwise YAML
        let definition: String
        let myCall: String?
        let steps: [Step]
        var testDescription: String { name }
    }

    static let s0 = Scenario(
        name: "java-rtty-dx-field-not-applicable",
        definition: "@cq-ww-rtty.yaml",
        myCall: "OK1XOE",
        steps: [
            Step(.preview("OM7M", "20m", "RTTY", [.init("zone", "15")]), "zones,cq_zones,15,20m,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,~,20m,SUSPICIOUS,false,false", "mult=0 groups=[zones=0,countries=0,states=0] distinct=0"),
        ])

    static let s1 = Scenario(
        name: "java-rtty-wve-state",
        definition: "@cq-ww-rtty.yaml",
        myCall: "OK1XOE",
        steps: [
            Step(.preview("W1AW", "20m", "RTTY", [.init("zone", "5"), .init("state", "CT")]), "zones,cq_zones,5,20m,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,291,20m,KNOWN_NEW_MULTIPLIER,true,true;states,na_areas,CT,20m,KNOWN_NEW_MULTIPLIER,true,true", "mult=0 groups=[zones=0,countries=0,states=0] distinct=0"),
        ])

    static let s2 = Scenario(
        name: "java-cw-known-new-then-already",
        definition: "@cq-ww-cw.yaml",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "20m", "CW", [.init("zone", "14")]), "zones,cq_zones,14,20m,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,230,20m,KNOWN_NEW_MULTIPLIER,true,true", "mult=2 groups=[zones=1,countries=1] distinct=2"),
            Step(.preview("DL2XYZ", "20m", "CW", [.init("zone", "14")]), "zones,cq_zones,14,20m,KNOWN_ALREADY_WORKED,true,false;countries,dxcc_entities,230,20m,KNOWN_ALREADY_WORKED,true,false", "mult=2 groups=[zones=1,countries=1] distinct=2"),
        ])

    static let s3 = Scenario(
        name: "java-cw-invalid-format",
        definition: "@cq-ww-cw.yaml",
        myCall: "OK1XOE",
        steps: [
            Step(.preview("DL1ABC", "20m", "CW", [.init("zone", "abc")]), "zones,cq_zones,~,20m,INVALID_FORMAT,false,false;countries,dxcc_entities,230,20m,KNOWN_NEW_MULTIPLIER,true,true", "mult=0 groups=[zones=0,countries=0] distinct=0"),
        ])

    static let s4 = Scenario(
        name: "java-cw-suspicious",
        definition: "@cq-ww-cw.yaml",
        myCall: "OK1XOE",
        steps: [
            Step(.preview("QQ9QQ", "20m", "CW", [.init("zone", "14")]), "zones,cq_zones,14,20m,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,~,20m,SUSPICIOUS,false,false", "mult=0 groups=[zones=0,countries=0] distinct=0"),
        ])

    static let s5 = Scenario(
        name: "java-160-unknown-accepted",
        definition: "@cq-160-cw.yaml",
        myCall: "OK1XOE",
        steps: [
            Step(.preview("W1AW", "160m", "CW", [.init("state", "XX")]), "areas,na_areas,XX,*,UNKNOWN_ACCEPTED,true,true", "mult=0 groups=[areas=0,countries=0] distinct=0"),
        ])

    static let s6 = Scenario(
        name: "cq-ww-cw",
        definition: "@cq-ww-cw.yaml",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "20m", "CW", [.init("rst", "599"), .init("zone", "14")]), "zones,cq_zones,14,20m,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,230,20m,KNOWN_NEW_MULTIPLIER,true,true", "mult=2 groups=[zones=1,countries=1] distinct=2"),
            Step(.preview("DL2XYZ", "20m", "CW", [.init("rst", "599"), .init("zone", "14")]), "zones,cq_zones,14,20m,KNOWN_ALREADY_WORKED,true,false;countries,dxcc_entities,230,20m,KNOWN_ALREADY_WORKED,true,false", "mult=2 groups=[zones=1,countries=1] distinct=2"),
            Step(.commit("DL2XYZ", "20m", "CW", [.init("rst", "599"), .init("zone", "14")]), "zones,cq_zones,14,20m,KNOWN_ALREADY_WORKED,true,false;countries,dxcc_entities,230,20m,KNOWN_ALREADY_WORKED,true,false", "mult=2 groups=[zones=1,countries=1] distinct=2"),
            Step(.commit("DL2XYZ", "40m", "CW", [.init("rst", "599"), .init("zone", "14")]), "zones,cq_zones,14,40m,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,230,40m,KNOWN_NEW_MULTIPLIER,true,true", "mult=4 groups=[zones=2,countries=2] distinct=4"),
            Step(.commit("W1AW", "20m", "CW", [.init("zone", "5")]), "zones,cq_zones,5,20m,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,291,20m,KNOWN_NEW_MULTIPLIER,true,true", "mult=6 groups=[zones=3,countries=3] distinct=6"),
            Step(.commit("W1AW", "20m", "CW", [.init("zone", "05")]), "zones,cq_zones,5,20m,KNOWN_ALREADY_WORKED,true,false;countries,dxcc_entities,291,20m,KNOWN_ALREADY_WORKED,true,false", "mult=6 groups=[zones=3,countries=3] distinct=6"),
            Step(.commit("W1AW", "20m", "CW", [.init("zone", " 5 ")]), "zones,cq_zones,5,20m,KNOWN_ALREADY_WORKED,true,false;countries,dxcc_entities,291,20m,KNOWN_ALREADY_WORKED,true,false", "mult=6 groups=[zones=3,countries=3] distinct=6"),
            Step(.commit("K1ABC", "20m", "CW", [.init("zone", "41")]), "zones,cq_zones,~,20m,INVALID_FORMAT,false,false;countries,dxcc_entities,291,20m,KNOWN_ALREADY_WORKED,true,false", "mult=6 groups=[zones=3,countries=3] distinct=6"),
            Step(.commit("K1ABC", "20m", "CW", [.init("zone", "0")]), "zones,cq_zones,~,20m,INVALID_FORMAT,false,false;countries,dxcc_entities,291,20m,KNOWN_ALREADY_WORKED,true,false", "mult=6 groups=[zones=3,countries=3] distinct=6"),
            Step(.commit("OK1AA", "20m", "CW", [.init("zone", "15")]), "zones,cq_zones,15,20m,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,503,20m,KNOWN_NEW_MULTIPLIER,true,true", "mult=8 groups=[zones=4,countries=4] distinct=8"),
            Step(.commit("QQ9QQ", "20m", "CW", [.init("zone", "14")]), "zones,cq_zones,14,20m,KNOWN_ALREADY_WORKED,true,false;countries,dxcc_entities,~,20m,SUSPICIOUS,false,false", "mult=8 groups=[zones=4,countries=4] distinct=8"),
            Step(.commit(nil, "20m", "CW", [.init("zone", "14")]), "zones,cq_zones,14,20m,KNOWN_ALREADY_WORKED,true,false;countries,dxcc_entities,~,20m,SUSPICIOUS,false,false", "mult=8 groups=[zones=4,countries=4] distinct=8"),
            Step(.commit("XX1A", "20m", "CW", [.init("zone", "33")]), "zones,cq_zones,33,20m,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,~,20m,SUSPICIOUS,false,false", "mult=9 groups=[zones=5,countries=4] distinct=9"),
            Step(.commit("DL1ABC", nil, "CW", [.init("zone", "14")]), "zones,cq_zones,14,null,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,230,null,KNOWN_NEW_MULTIPLIER,true,true", "mult=11 groups=[zones=6,countries=5] distinct=11"),
            Step(.commit("DL1ABC", nil, "CW", [.init("zone", "14")]), "zones,cq_zones,14,null,KNOWN_ALREADY_WORKED,true,false;countries,dxcc_entities,230,null,KNOWN_ALREADY_WORKED,true,false", "mult=11 groups=[zones=6,countries=5] distinct=11"),
            Step(.commit("DL1ABC", "null", "CW", [.init("zone", "14")]), "zones,cq_zones,14,null,KNOWN_ALREADY_WORKED,true,false;countries,dxcc_entities,230,null,KNOWN_ALREADY_WORKED,true,false", "mult=11 groups=[zones=6,countries=5] distinct=11"),
            Step(.commit("dl1abc", "20m", "CW", [.init("zone", "14")]), "zones,cq_zones,14,20m,KNOWN_ALREADY_WORKED,true,false;countries,dxcc_entities,230,20m,KNOWN_ALREADY_WORKED,true,false", "mult=11 groups=[zones=6,countries=5] distinct=11"),
            Step(.commit("DL1ABC", "20M", "CW", [.init("zone", "14")]), "zones,cq_zones,14,20M,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,230,20M,KNOWN_NEW_MULTIPLIER,true,true", "mult=13 groups=[zones=7,countries=6] distinct=13"),
            Step(.commit("DL1ABC", "20m", "CW", nil), "zones,cq_zones,~,20m,INVALID_FORMAT,false,false;countries,dxcc_entities,230,20m,KNOWN_ALREADY_WORKED,true,false", "mult=13 groups=[zones=7,countries=6] distinct=13"),
            Step(.commit("DL1ABC", "20m", "CW", []), "zones,cq_zones,~,20m,INVALID_FORMAT,false,false;countries,dxcc_entities,230,20m,KNOWN_ALREADY_WORKED,true,false", "mult=13 groups=[zones=7,countries=6] distinct=13"),
            Step(.preview("VE3ABC", "80m", "CW", [.init("zone", "\u{661}\u{664}")]), "zones,cq_zones,~,80m,INVALID_FORMAT,false,false;countries,dxcc_entities,1,80m,KNOWN_NEW_MULTIPLIER,true,true", "mult=13 groups=[zones=7,countries=6] distinct=13"),
            Step(.preview("VE3ABC", "80m", "CW", [.init("zone", "\u{A0}4")]), "zones,cq_zones,~,80m,INVALID_FORMAT,false,false;countries,dxcc_entities,1,80m,KNOWN_NEW_MULTIPLIER,true,true", "mult=13 groups=[zones=7,countries=6] distinct=13"),
        ])

    static let s7 = Scenario(
        name: "cq-ww-rtty",
        definition: "@cq-ww-rtty.yaml",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("W1AW", "20m", "RTTY", [.init("zone", "5"), .init("state", "CT")]), "zones,cq_zones,5,20m,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,291,20m,KNOWN_NEW_MULTIPLIER,true,true;states,na_areas,CT,20m,KNOWN_NEW_MULTIPLIER,true,true", "mult=3 groups=[zones=1,countries=1,states=1] distinct=3"),
            Step(.commit("W1AW", "20m", "RTTY", [.init("zone", "5"), .init("state", "ct")]), "zones,cq_zones,5,20m,KNOWN_ALREADY_WORKED,true,false;countries,dxcc_entities,291,20m,KNOWN_ALREADY_WORKED,true,false;states,na_areas,CT,20m,KNOWN_ALREADY_WORKED,true,false", "mult=3 groups=[zones=1,countries=1,states=1] distinct=3"),
            Step(.commit("K2AA", "20m", "RTTY", [.init("zone", "5"), .init("state", "NY")]), "zones,cq_zones,5,20m,KNOWN_ALREADY_WORKED,true,false;countries,dxcc_entities,291,20m,KNOWN_ALREADY_WORKED,true,false;states,na_areas,NY,20m,KNOWN_NEW_MULTIPLIER,true,true", "mult=4 groups=[zones=1,countries=1,states=2] distinct=4"),
            Step(.commit("VE3AA", "20m", "RTTY", [.init("zone", "4"), .init("state", "ON")]), "zones,cq_zones,4,20m,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,1,20m,KNOWN_NEW_MULTIPLIER,true,true;states,na_areas,ON,20m,KNOWN_NEW_MULTIPLIER,true,true", "mult=7 groups=[zones=2,countries=2,states=3] distinct=7"),
            Step(.commit("W1AW", "40m", "RTTY", [.init("zone", "5"), .init("state", "XX")]), "zones,cq_zones,5,40m,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,291,40m,KNOWN_NEW_MULTIPLIER,true,true;states,na_areas,XX,40m,UNKNOWN_ACCEPTED,true,true", "mult=10 groups=[zones=3,countries=3,states=4] distinct=10"),
            Step(.commit("W1AW", "40m", "RTTY", [.init("zone", "5")]), "zones,cq_zones,5,40m,KNOWN_ALREADY_WORKED,true,false;countries,dxcc_entities,291,40m,KNOWN_ALREADY_WORKED,true,false;states,na_areas,~,40m,INVALID_FORMAT,false,false", "mult=10 groups=[zones=3,countries=3,states=4] distinct=10"),
            Step(.commit("DL1ABC", "20m", "RTTY", [.init("zone", "14"), .init("state", "CT")]), "zones,cq_zones,14,20m,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,230,20m,KNOWN_NEW_MULTIPLIER,true,true", "mult=12 groups=[zones=4,countries=4,states=4] distinct=12"),
            Step(.commit("OM7M", "20m", "RTTY", [.init("zone", "15")]), "zones,cq_zones,15,20m,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,~,20m,SUSPICIOUS,false,false", "mult=13 groups=[zones=5,countries=4,states=4] distinct=13"),
        ])

    static let s8 = Scenario(
        name: "cq-wpx-cw",
        definition: "@cq-wpx-cw.yaml",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("OK1AA", "20m", "CW", [.init("nr", "1")]), "prefixes,wpx_prefixes,OK1,*,KNOWN_NEW_MULTIPLIER,true,true", "mult=1 groups=[prefixes=1] distinct=1"),
            Step(.commit("OK1BB", "40m", "CW", [.init("nr", "2")]), "prefixes,wpx_prefixes,OK1,*,KNOWN_ALREADY_WORKED,true,false", "mult=1 groups=[prefixes=1] distinct=1"),
            Step(.commit("OK2AA", "20m", "CW", [.init("nr", "3")]), "prefixes,wpx_prefixes,OK2,*,KNOWN_NEW_MULTIPLIER,true,true", "mult=2 groups=[prefixes=2] distinct=2"),
            Step(.commit("OK1AA/P", "20m", "CW", [.init("nr", "4")]), "prefixes,wpx_prefixes,OK1,*,KNOWN_ALREADY_WORKED,true,false", "mult=2 groups=[prefixes=2] distinct=2"),
            Step(.commit("W1AW", nil, nil, [.init("nr", "5")]), "prefixes,wpx_prefixes,W1,*,KNOWN_NEW_MULTIPLIER,true,true", "mult=3 groups=[prefixes=3] distinct=3"),
            Step(.commit("QQ9QQ", "20m", "CW", [.init("nr", "6")]), "prefixes,wpx_prefixes,QQ9,*,KNOWN_NEW_MULTIPLIER,true,true", "mult=4 groups=[prefixes=4] distinct=4"),
            Step(.commit("", "20m", "CW", [.init("nr", "7")]), "prefixes,wpx_prefixes,~,*,SUSPICIOUS,false,false", "mult=4 groups=[prefixes=4] distinct=4"),
            Step(.commit(nil, "20m", "CW", [.init("nr", "8")]), "prefixes,wpx_prefixes,~,*,SUSPICIOUS,false,false", "mult=4 groups=[prefixes=4] distinct=4"),
            Step(.commit("DL/OK1AA", "20m", "CW", [.init("nr", "9")]), "prefixes,wpx_prefixes,DL0,*,KNOWN_NEW_MULTIPLIER,true,true", "mult=5 groups=[prefixes=5] distinct=5"),
            Step(.commit("ok1cc", "20m", "CW", [.init("nr", "10")]), "prefixes,wpx_prefixes,OK1,*,KNOWN_ALREADY_WORKED,true,false", "mult=5 groups=[prefixes=5] distinct=5"),
        ])

    static let s9 = Scenario(
        name: "cq-160-cw",
        definition: "@cq-160-cw.yaml",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("W1AW", "160m", "CW", [.init("state", "CT")]), "areas,na_areas,CT,*,KNOWN_NEW_MULTIPLIER,true,true", "mult=1 groups=[areas=1,countries=0] distinct=1"),
            Step(.commit("W1AW", "160m", "CW", [.init("state", "XX")]), "areas,na_areas,XX,*,UNKNOWN_ACCEPTED,true,true", "mult=2 groups=[areas=2,countries=0] distinct=2"),
            Step(.commit("W1AW", "160m", "CW", [.init("state", "XX")]), "areas,na_areas,XX,*,UNKNOWN_ACCEPTED,true,false", "mult=2 groups=[areas=2,countries=0] distinct=2"),
            Step(.commit("VE3AA", "160m", "CW", [.init("state", "ON")]), "areas,na_areas,ON,*,KNOWN_NEW_MULTIPLIER,true,true", "mult=3 groups=[areas=3,countries=0] distinct=3"),
            Step(.commit("DL1ABC", "160m", "CW", [.init("zone", "14")]), "countries,dxcc_entities,230,*,KNOWN_NEW_MULTIPLIER,true,true", "mult=4 groups=[areas=3,countries=1] distinct=4"),
            Step(.commit("DL2AA", "160m", "CW", [.init("zone", "14")]), "countries,dxcc_entities,230,*,KNOWN_ALREADY_WORKED,true,false", "mult=4 groups=[areas=3,countries=1] distinct=4"),
            Step(.commit("OK1AA", "160m", "CW", [.init("zone", "15")]), "countries,dxcc_entities,503,*,KNOWN_NEW_MULTIPLIER,true,true", "mult=5 groups=[areas=3,countries=2] distinct=5"),
            Step(.commit("QQ9QQ", "160m", "CW", [.init("zone", "1")]), "countries,dxcc_entities,~,*,SUSPICIOUS,false,false", "mult=5 groups=[areas=3,countries=2] distinct=5"),
            Step(.commit("W1AW", "160m", "CW", []), "areas,na_areas,~,*,INVALID_FORMAT,false,false", "mult=5 groups=[areas=3,countries=2] distinct=5"),
        ])

    static let s10 = Scenario(
        name: "wae-cw",
        definition: "@wae-cw.yaml",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("W1AW", "80m", "CW", [.init("nr", "1")]), "countries,dxcc_entities,291,80m,KNOWN_NEW_MULTIPLIER,true,true", "mult=4 groups=[countries=4] distinct=1"),
            Step(.commit("VE3AA", "80m", "CW", [.init("nr", "2")]), "countries,dxcc_entities,1,80m,KNOWN_NEW_MULTIPLIER,true,true", "mult=8 groups=[countries=8] distinct=2"),
            Step(.commit("W1AW", "80m", "CW", [.init("nr", "3")]), "countries,dxcc_entities,291,80m,KNOWN_ALREADY_WORKED,true,false", "mult=8 groups=[countries=8] distinct=2"),
            Step(.commit("W1AW", "40m", "CW", [.init("nr", "4")]), "countries,dxcc_entities,291,40m,KNOWN_NEW_MULTIPLIER,true,true", "mult=11 groups=[countries=11] distinct=3"),
            Step(.commit("W1AW", "20m", "CW", [.init("nr", "5")]), "countries,dxcc_entities,291,20m,KNOWN_NEW_MULTIPLIER,true,true", "mult=13 groups=[countries=13] distinct=4"),
            Step(.commit("W1AW", "160m", "CW", [.init("nr", "6")]), "countries,dxcc_entities,291,160m,KNOWN_NEW_MULTIPLIER,true,true", "mult=14 groups=[countries=14] distinct=5"),
            Step(.commit("W1AW", "6m", "CW", [.init("nr", "7")]), "countries,dxcc_entities,291,6m,KNOWN_NEW_MULTIPLIER,true,true", "mult=15 groups=[countries=15] distinct=6"),
            Step(.commit("DL1ABC", "20m", "CW", [.init("nr", "8")]), "", "mult=15 groups=[countries=15] distinct=6"),
            Step(.commit("XX1A", "15m", "CW", [.init("nr", "9")]), "", "mult=15 groups=[countries=15] distinct=6"),
            Step(.commit("QQ9QQ", "10m", "CW", [.init("nr", "10")]), "", "mult=15 groups=[countries=15] distinct=6"),
        ])

    static let s11 = Scenario(
        name: "wae-cw-from-na",
        definition: "@wae-cw.yaml",
        myCall: "W1AW",
        steps: [
            Step(.commit("DL1ABC", "80m", "CW", [.init("nr", "1")]), "countries,dxcc_entities,230,80m,KNOWN_NEW_MULTIPLIER,true,true", "mult=4 groups=[countries=4] distinct=1"),
            Step(.commit("OK1AA", "80m", "CW", [.init("nr", "2")]), "countries,dxcc_entities,503,80m,KNOWN_NEW_MULTIPLIER,true,true", "mult=8 groups=[countries=8] distinct=2"),
            Step(.commit("VE3AA", "80m", "CW", [.init("nr", "3")]), "", "mult=8 groups=[countries=8] distinct=2"),
            Step(.commit("OK1AA", "10m", "CW", [.init("nr", "4")]), "countries,dxcc_entities,503,10m,KNOWN_NEW_MULTIPLIER,true,true", "mult=10 groups=[countries=10] distinct=3"),
        ])

    static let s12 = Scenario(
        name: "iaru-hf",
        definition: "@iaru-hf.yaml",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "20m", "CW", [.init("rst", "599"), .init("exch", "28")]), "zones,itu_zones,28,20m,KNOWN_NEW_MULTIPLIER,true,true;hq,iaru_hq,~,20m,INVALID_FORMAT,false,false", "mult=1 groups=[zones=1,hq=0] distinct=1"),
            Step(.commit("DL2AA", "20m", "CW", [.init("exch", "28")]), "zones,itu_zones,28,20m,KNOWN_ALREADY_WORKED,true,false;hq,iaru_hq,~,20m,INVALID_FORMAT,false,false", "mult=1 groups=[zones=1,hq=0] distinct=1"),
            Step(.commit("DA0HQ", "20m", "CW", [.init("exch", "DARC")]), "zones,itu_zones,~,20m,INVALID_FORMAT,false,false;hq,iaru_hq,DARC,20m,KNOWN_NEW_MULTIPLIER,true,true", "mult=2 groups=[zones=1,hq=1] distinct=2"),
            Step(.commit("DA0HQ", "40m", "SSB", [.init("exch", "darc")]), "zones,itu_zones,~,40m,INVALID_FORMAT,false,false;hq,iaru_hq,DARC,40m,KNOWN_NEW_MULTIPLIER,true,true", "mult=3 groups=[zones=1,hq=2] distinct=3"),
            Step(.commit("W1AW", "20m", "CW", [.init("exch", "ARRL")]), "zones,itu_zones,~,20m,INVALID_FORMAT,false,false;hq,iaru_hq,ARRL,20m,KNOWN_NEW_MULTIPLIER,true,true", "mult=4 groups=[zones=1,hq=3] distinct=4"),
            Step(.commit("W1AW", "20m", "CW", [.init("exch", "76")]), "zones,itu_zones,~,20m,INVALID_FORMAT,false,false;hq,iaru_hq,~,20m,INVALID_FORMAT,false,false", "mult=4 groups=[zones=1,hq=3] distinct=4"),
            Step(.commit("W1AW", "20m", "CW", [.init("exch", "08")]), "zones,itu_zones,8,20m,KNOWN_NEW_MULTIPLIER,true,true;hq,iaru_hq,~,20m,INVALID_FORMAT,false,false", "mult=5 groups=[zones=2,hq=3] distinct=5"),
            Step(.commit("W1AW", "20m", "CW", [.init("exch", "ZZZZ")]), "zones,itu_zones,~,20m,INVALID_FORMAT,false,false;hq,iaru_hq,ZZZZ,20m,UNKNOWN_ACCEPTED,true,true", "mult=6 groups=[zones=2,hq=4] distinct=6"),
            Step(.commit("LA2RR", "20m", "CW", [.init("exch", "AC")]), "zones,itu_zones,~,20m,INVALID_FORMAT,false,false;hq,iaru_hq,AC,20m,KNOWN_NEW_MULTIPLIER,true,true", "mult=7 groups=[zones=2,hq=5] distinct=7"),
        ])

    static let s13 = Scenario(
        name: "ok-om-dx-cw",
        definition: "@ok-om-dx-cw.yaml",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("OK1AA", "20m", "CW", [.init("district", "APA")]), "districts,ok_om_districts,APA,20m,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,503,20m,KNOWN_NEW_MULTIPLIER,true,true", "mult=2 groups=[districts=1,countries=1] distinct=2"),
            Step(.commit("OK1BB", "20m", "CW", [.init("district", "apa")]), "districts,ok_om_districts,APA,20m,KNOWN_ALREADY_WORKED,true,false;countries,dxcc_entities,503,20m,KNOWN_ALREADY_WORKED,true,false", "mult=2 groups=[districts=1,countries=1] distinct=2"),
            Step(.commit("OK1BB", "40m", "CW", [.init("district", "APA")]), "districts,ok_om_districts,APA,40m,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,503,40m,KNOWN_NEW_MULTIPLIER,true,true", "mult=4 groups=[districts=2,countries=2] distinct=4"),
            Step(.commit("OK2AA", "20m", "CW", [.init("district", "ZZZ")]), "districts,ok_om_districts,ZZZ,20m,UNKNOWN_ACCEPTED,true,true;countries,dxcc_entities,503,20m,KNOWN_ALREADY_WORKED,true,false", "mult=5 groups=[districts=3,countries=2] distinct=5"),
            Step(.commit("OK2AA", "20m", "CW", [.init("district", "12")]), "districts,ok_om_districts,12,20m,UNKNOWN_ACCEPTED,true,true;countries,dxcc_entities,503,20m,KNOWN_ALREADY_WORKED,true,false", "mult=6 groups=[districts=4,countries=2] distinct=6"),
            Step(.commit("DL1ABC", "20m", "CW", [.init("nr", "1")]), "countries,dxcc_entities,230,20m,KNOWN_NEW_MULTIPLIER,true,true", "mult=7 groups=[districts=4,countries=3] distinct=7"),
            Step(.commit("W1AW", "20m", "CW", [.init("nr", "2"), .init("district", "APA")]), "countries,dxcc_entities,291,20m,KNOWN_NEW_MULTIPLIER,true,true", "mult=8 groups=[districts=4,countries=4] distinct=8"),
        ])

    static let s14 = Scenario(
        name: "dup-id",
        definition: "{exchange: {received: [{id: zone, type: CQ_ZONE}]}, multipliers: [{id: z, set: cq_zones, from: zone, scope: PER_BAND}, {id: z, set: cq_zones, from: zone, scope: PER_BAND}], scoring: {total: multTotal}}",
        myCall: "OK1XOE",
        steps: [
            Step(.preview("DL1ABC", "20m", "CW", [.init("zone", "14")]), "z,cq_zones,14,20m,KNOWN_NEW_MULTIPLIER,true,true;z,cq_zones,14,20m,KNOWN_NEW_MULTIPLIER,true,true", "mult=0 groups=[z=0] distinct=0"),
            Step(.commit("DL1ABC", "20m", "CW", [.init("zone", "14")]), "z,cq_zones,14,20m,KNOWN_NEW_MULTIPLIER,true,true;z,cq_zones,14,20m,KNOWN_ALREADY_WORKED,true,false", "mult=1 groups=[z=2] distinct=1"),
            Step(.preview("DL1ABC", "20m", "CW", [.init("zone", "14")]), "z,cq_zones,14,20m,KNOWN_ALREADY_WORKED,true,false;z,cq_zones,14,20m,KNOWN_ALREADY_WORKED,true,false", "mult=1 groups=[z=2] distinct=1"),
            Step(.commit("DL1ABC", "40m", "CW", [.init("zone", "15")]), "z,cq_zones,15,40m,KNOWN_NEW_MULTIPLIER,true,true;z,cq_zones,15,40m,KNOWN_ALREADY_WORKED,true,false", "mult=2 groups=[z=4] distinct=2"),
        ])

    static let s15 = Scenario(
        name: "from-upper",
        definition: "{stationClasses: [{id: dx}], exchange: {received: [{id: zone, type: CQ_ZONE, appliesWhen: {workedClass: dx}}]}, multipliers: [{id: z, set: cq_zones, from: ZONE}]}",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "20m", "CW", [.init("zone", "14")]), "z,cq_zones,~,*,INVALID_FORMAT,false,false", "mult=0 groups=[z=0] distinct=0"),
        ])

    static let s16 = Scenario(
        name: "from-upper-inherits-class",
        definition: "{stationClasses: [{id: wve, when: {dxccIn: [US]}}, {id: dx}], exchange: {received: [{id: zone, type: CQ_ZONE, appliesWhen: {workedClass: wve}}]}, multipliers: [{id: z, set: cq_zones, from: ZONE}]}",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "20m", "CW", [.init("zone", "14")]), "", "mult=0 groups=[z=0] distinct=0"),
            Step(.commit("W1AW", "20m", "CW", [.init("zone", "5")]), "z,cq_zones,~,*,INVALID_FORMAT,false,false", "mult=0 groups=[z=0] distinct=0"),
        ])

    static let s17 = Scenario(
        name: "field-id-upper",
        definition: "{exchange: {received: [{id: Zone, type: CQ_ZONE}]}, multipliers: [{id: z, set: cq_zones, from: zone}]}",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "20m", "CW", [.init("Zone", "14")]), "z,cq_zones,~,*,INVALID_FORMAT,false,false", "mult=0 groups=[z=0] distinct=0"),
        ])

    static let s18 = Scenario(
        name: "scopes",
        definition: "{exchange: {received: [{id: zone, type: CQ_ZONE}]}, multipliers: [{id: none, set: cq_zones, from: zone}, {id: once, set: cq_zones, from: zone, scope: ONCE}, {id: band, set: cq_zones, from: zone, scope: PER_BAND}, {id: mode, set: cq_zones, from: zone, scope: PER_MODE}, {id: bm, set: cq_zones, from: zone, scope: PER_BAND_MODE}], scoring: {total: multTotal}}",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "20m", "CW", [.init("zone", "14")]), "none,cq_zones,14,*,KNOWN_NEW_MULTIPLIER,true,true;once,cq_zones,14,*,KNOWN_NEW_MULTIPLIER,true,true;band,cq_zones,14,20m,KNOWN_NEW_MULTIPLIER,true,true;mode,cq_zones,14,CW,KNOWN_NEW_MULTIPLIER,true,true;bm,cq_zones,14,20m\\u007CCW,KNOWN_NEW_MULTIPLIER,true,true", "mult=5 groups=[none=1,once=1,band=1,mode=1,bm=1] distinct=5"),
            Step(.commit("DL1ABC", "20m", "SSB", [.init("zone", "14")]), "none,cq_zones,14,*,KNOWN_ALREADY_WORKED,true,false;once,cq_zones,14,*,KNOWN_ALREADY_WORKED,true,false;band,cq_zones,14,20m,KNOWN_ALREADY_WORKED,true,false;mode,cq_zones,14,SSB,KNOWN_NEW_MULTIPLIER,true,true;bm,cq_zones,14,20m\\u007CSSB,KNOWN_NEW_MULTIPLIER,true,true", "mult=7 groups=[none=1,once=1,band=1,mode=2,bm=2] distinct=7"),
            Step(.commit("DL1ABC", "40m", "CW", [.init("zone", "14")]), "none,cq_zones,14,*,KNOWN_ALREADY_WORKED,true,false;once,cq_zones,14,*,KNOWN_ALREADY_WORKED,true,false;band,cq_zones,14,40m,KNOWN_NEW_MULTIPLIER,true,true;mode,cq_zones,14,CW,KNOWN_ALREADY_WORKED,true,false;bm,cq_zones,14,40m\\u007CCW,KNOWN_NEW_MULTIPLIER,true,true", "mult=9 groups=[none=1,once=1,band=2,mode=2,bm=3] distinct=9"),
            Step(.commit("DL1ABC", nil, nil, [.init("zone", "14")]), "none,cq_zones,14,*,KNOWN_ALREADY_WORKED,true,false;once,cq_zones,14,*,KNOWN_ALREADY_WORKED,true,false;band,cq_zones,14,null,KNOWN_NEW_MULTIPLIER,true,true;mode,cq_zones,14,null,KNOWN_NEW_MULTIPLIER,true,true;bm,cq_zones,14,null\\u007Cnull,KNOWN_NEW_MULTIPLIER,true,true", "mult=12 groups=[none=1,once=1,band=3,mode=3,bm=4] distinct=12"),
            Step(.commit("DL1ABC", "null", "null", [.init("zone", "14")]), "none,cq_zones,14,*,KNOWN_ALREADY_WORKED,true,false;once,cq_zones,14,*,KNOWN_ALREADY_WORKED,true,false;band,cq_zones,14,null,KNOWN_ALREADY_WORKED,true,false;mode,cq_zones,14,null,KNOWN_ALREADY_WORKED,true,false;bm,cq_zones,14,null\\u007Cnull,KNOWN_ALREADY_WORKED,true,false", "mult=12 groups=[none=1,once=1,band=3,mode=3,bm=4] distinct=12"),
            Step(.commit("DL1ABC", nil, "CW", [.init("zone", "14")]), "none,cq_zones,14,*,KNOWN_ALREADY_WORKED,true,false;once,cq_zones,14,*,KNOWN_ALREADY_WORKED,true,false;band,cq_zones,14,null,KNOWN_ALREADY_WORKED,true,false;mode,cq_zones,14,CW,KNOWN_ALREADY_WORKED,true,false;bm,cq_zones,14,null\\u007CCW,KNOWN_NEW_MULTIPLIER,true,true", "mult=13 groups=[none=1,once=1,band=3,mode=3,bm=5] distinct=13"),
            Step(.commit("DL1ABC", "20m|CW", nil, [.init("zone", "14")]), "none,cq_zones,14,*,KNOWN_ALREADY_WORKED,true,false;once,cq_zones,14,*,KNOWN_ALREADY_WORKED,true,false;band,cq_zones,14,20m\\u007CCW,KNOWN_NEW_MULTIPLIER,true,true;mode,cq_zones,14,null,KNOWN_ALREADY_WORKED,true,false;bm,cq_zones,14,20m\\u007CCW\\u007Cnull,KNOWN_NEW_MULTIPLIER,true,true", "mult=15 groups=[none=1,once=1,band=4,mode=3,bm=6] distinct=15"),
            Step(.commit("DL1ABC", "*", "CW", [.init("zone", "14")]), "none,cq_zones,14,*,KNOWN_ALREADY_WORKED,true,false;once,cq_zones,14,*,KNOWN_ALREADY_WORKED,true,false;band,cq_zones,14,*,KNOWN_NEW_MULTIPLIER,true,true;mode,cq_zones,14,CW,KNOWN_ALREADY_WORKED,true,false;bm,cq_zones,14,*\\u007CCW,KNOWN_NEW_MULTIPLIER,true,true", "mult=17 groups=[none=1,once=1,band=5,mode=3,bm=7] distinct=17"),
        ])

    static let s19 = Scenario(
        name: "no-from",
        definition: "{multipliers: [{id: a, set: cq_zones}]}",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "20m", "CW", [.init("zone", "14")]), "a,cq_zones,~,*,INVALID_FORMAT,false,false", "mult=0 groups=[a=0] distinct=0"),
        ])

    static let s20 = Scenario(
        name: "from-callsign-case",
        definition: "{multipliers: [{id: c, set: dxcc_entities, from: CallSign}, {id: w, set: wpx_prefixes, from: CALLSIGN}, {id: z, set: cq_zones, from: callsign}]}",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "20m", "CW", []), "c,dxcc_entities,230,*,KNOWN_NEW_MULTIPLIER,true,true;w,wpx_prefixes,DL1,*,KNOWN_NEW_MULTIPLIER,true,true;z,cq_zones,~,*,SUSPICIOUS,false,false", "mult=2 groups=[c=1,w=1,z=0] distinct=2"),
        ])

    static let s21 = Scenario(
        name: "null-id",
        definition: "{exchange: {received: [{id: zone, type: CQ_ZONE}]}, multipliers: [{set: cq_zones, from: zone, scope: PER_BAND}, {id: 'null', set: cq_zones, from: zone, scope: PER_BAND}], scoring: {total: multTotal}}",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "20m", "CW", [.init("zone", "14")]), "~,cq_zones,14,20m,KNOWN_NEW_MULTIPLIER,true,true;null,cq_zones,14,20m,KNOWN_NEW_MULTIPLIER,true,true", "mult=2 groups=[~=1,null=1] distinct=2"),
            Step(.preview("DL1ABC", "20m", "CW", [.init("zone", "14")]), "~,cq_zones,14,20m,KNOWN_ALREADY_WORKED,true,false;null,cq_zones,14,20m,KNOWN_ALREADY_WORKED,true,false", "mult=2 groups=[~=1,null=1] distinct=2"),
        ])

    static let s22 = Scenario(
        name: "null-set",
        definition: "{multipliers: [{id: a, from: callsign}]}",
        myCall: "OK1XOE",
        steps: [
            Step(.preview("DL1ABC", "20m", "CW", []), "EXC MultiplierException: multiplik\\u00E1torov\\u00E1\\u0020sada\\u0020'null'\\u0020nen\\u00ED\\u0020v\\u0020registru", "mult=0 groups=[a=0] distinct=0"),
        ])

    static let s23 = Scenario(
        name: "unknown-set-partial-commit",
        definition: "{exchange: {received: [{id: zone, type: CQ_ZONE}]}, multipliers: [{id: a, set: cq_zones, from: zone}, {id: b, set: nope, from: zone}], scoring: {total: multTotal}}",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "20m", "CW", [.init("zone", "14")]), "EXC MultiplierException: multiplik\\u00E1torov\\u00E1\\u0020sada\\u0020'nope'\\u0020nen\\u00ED\\u0020v\\u0020registru", "mult=1 groups=[a=1,b=0] distinct=1"),
            Step(.preview("DL1ABC", "20m", "CW", [.init("zone", "14")]), "EXC MultiplierException: multiplik\\u00E1torov\\u00E1\\u0020sada\\u0020'nope'\\u0020nen\\u00ED\\u0020v\\u0020registru", "mult=1 groups=[a=1,b=0] distinct=1"),
            Step(.tracker("W", "a", "*", "14"), "true", "-"),
            Step(.tracker("D", "a", nil, nil), "1", "-"),
        ])

    static let s24 = Scenario(
        name: "no-multipliers",
        definition: "{exchange: {received: [{id: zone, type: CQ_ZONE}]}}",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "20m", "CW", [.init("zone", "14")]), "", "mult=0 groups=[] distinct=0"),
        ])

    static let s25 = Scenario(
        name: "empty-multipliers",
        definition: "{multipliers: []}",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "20m", "CW", []), "", "mult=0 groups=[] distinct=0"),
        ])

    static let s26 = Scenario(
        name: "applies-explicit-empty",
        definition: "{stationClasses: [{id: wve, when: {dxccIn: [US]}}, {id: dx}], exchange: {received: [{id: state, type: STATE, appliesWhen: {workedClass: wve}}]}, multipliers: [{id: s, set: na_areas, from: state, appliesWhen: {}}]}",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "20m", "CW", [.init("state", "CT")]), "s,na_areas,~,*,INVALID_FORMAT,false,false", "mult=0 groups=[s=0] distinct=0"),
            Step(.commit("W1AW", "20m", "CW", [.init("state", "CT")]), "s,na_areas,CT,*,KNOWN_NEW_MULTIPLIER,true,true", "mult=1 groups=[s=1] distinct=1"),
        ])

    static let s27 = Scenario(
        name: "applies-case-sensitive",
        definition: "{stationClasses: [{id: dx}], multipliers: [{id: c, set: dxcc_entities, from: callsign, appliesWhen: {workedClass: DX}}, {id: d, set: dxcc_entities, from: callsign, appliesWhen: {workedClass: dx}}]}",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "20m", "CW", []), "d,dxcc_entities,230,*,KNOWN_NEW_MULTIPLIER,true,true", "mult=1 groups=[c=0,d=1] distinct=1"),
        ])

    static let s28 = Scenario(
        name: "applies-inherit-later-duplicate",
        definition: "{stationClasses: [{id: wve, when: {dxccIn: [US]}}, {id: dx}], exchange: {received: [{id: zone, type: CQ_ZONE}, {id: ZONE, type: CQ_ZONE, appliesWhen: {workedClass: wve}}]}, multipliers: [{id: z, set: cq_zones, from: zone}]}",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "20m", "CW", [.init("zone", "14")]), "", "mult=0 groups=[z=0] distinct=0"),
            Step(.commit("W1AW", "20m", "CW", [.init("zone", "5"), .init("ZONE", "4")]), "z,cq_zones,5,*,KNOWN_NEW_MULTIPLIER,true,true", "mult=1 groups=[z=1] distinct=1"),
        ])

    static let s29 = Scenario(
        name: "applies-no-class",
        definition: "{exchange: {received: [{id: zone, type: CQ_ZONE, appliesWhen: {workedClass: dx}}]}, multipliers: [{id: z, set: cq_zones, from: zone}]}",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "20m", "CW", [.init("zone", "14")]), "", "mult=0 groups=[z=0] distinct=0"),
        ])

    static let s30 = Scenario(
        name: "applies-null-class-id",
        definition: "{stationClasses: [{when: {}}], exchange: {received: [{id: zone, type: CQ_ZONE}]}, multipliers: [{id: z, set: cq_zones, from: zone, appliesWhen: {workedClass: 'null'}}, {id: y, set: cq_zones, from: zone, appliesWhen: {workedClass: ~}}]}",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "20m", "CW", [.init("zone", "14")]), "y,cq_zones,14,*,KNOWN_NEW_MULTIPLIER,true,true", "mult=1 groups=[z=0,y=1] distinct=1"),
        ])

    static let s31 = Scenario(
        name: "applies-utf16",
        definition: "{stationClasses: [{id: \"\u{212A}\"}], multipliers: [{id: c, set: dxcc_entities, from: callsign, appliesWhen: {workedClass: K}}, {id: d, set: dxcc_entities, from: callsign, appliesWhen: {workedClass: \"\u{212A}\"}}]}",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "20m", "CW", []), "d,dxcc_entities,230,*,KNOWN_NEW_MULTIPLIER,true,true", "mult=1 groups=[c=0,d=1] distinct=1"),
        ])

    static let s32 = Scenario(
        name: "grid-fields",
        definition: "{exchange: {received: [{id: loc, type: LOCATOR}]}, multipliers: [{id: g, set: grid_fields, from: loc, scope: PER_BAND}], scoring: {total: multTotal}}",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "2m", "FM", [.init("loc", "JN89")]), "g,grid_fields,JN,2m,UNKNOWN_ACCEPTED,true,true", "mult=1 groups=[g=1] distinct=1"),
            Step(.commit("DL1ABC", "2m", "FM", [.init("loc", "jn89ab")]), "g,grid_fields,JN,2m,UNKNOWN_ACCEPTED,true,false", "mult=1 groups=[g=1] distinct=1"),
            Step(.commit("DL1ABC", "70cm", "FM", [.init("loc", "JO70")]), "g,grid_fields,JO,70cm,UNKNOWN_ACCEPTED,true,true", "mult=2 groups=[g=2] distinct=2"),
            Step(.commit("DL1ABC", "2m", "FM", [.init("loc", "XX")]), "g,grid_fields,~,2m,INVALID_FORMAT,false,false", "mult=2 groups=[g=2] distinct=2"),
            Step(.tracker("K", "g", nil, nil), "JN;JO", "-"),
        ])

    static let s33 = Scenario(
        name: "weights",
        definition: "{exchange: {received: [{id: zone, type: CQ_ZONE}]}, multipliers: [{id: w, set: cq_zones, from: zone, scope: PER_BAND_MODE, bandWeights: {80m: 4, 'null': 5, '*': 7}}, {id: o, set: cq_zones, from: zone, bandWeights: {'*': 3}}], scoring: {total: multTotal}}",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "80m", "CW", [.init("zone", "14")]), "w,cq_zones,14,80m\\u007CCW,KNOWN_NEW_MULTIPLIER,true,true;o,cq_zones,14,*,KNOWN_NEW_MULTIPLIER,true,true", "mult=7 groups=[w=4,o=3] distinct=2"),
            Step(.commit("DL1ABC", "80m", "SSB", [.init("zone", "14")]), "w,cq_zones,14,80m\\u007CSSB,KNOWN_NEW_MULTIPLIER,true,true;o,cq_zones,14,*,KNOWN_ALREADY_WORKED,true,false", "mult=11 groups=[w=8,o=3] distinct=3"),
            Step(.commit("DL1ABC", nil, "CW", [.init("zone", "15")]), "w,cq_zones,15,null\\u007CCW,KNOWN_NEW_MULTIPLIER,true,true;o,cq_zones,15,*,KNOWN_NEW_MULTIPLIER,true,true", "mult=19 groups=[w=13,o=6] distinct=5"),
            Step(.commit("DL1ABC", "20m", "CW", [.init("zone", "14")]), "w,cq_zones,14,20m\\u007CCW,KNOWN_NEW_MULTIPLIER,true,true;o,cq_zones,14,*,KNOWN_ALREADY_WORKED,true,false", "mult=20 groups=[w=14,o=6] distinct=6"),
            Step(.commit("DL1ABC", "80M", "CW", [.init("zone", "14")]), "w,cq_zones,14,80M\\u007CCW,KNOWN_NEW_MULTIPLIER,true,true;o,cq_zones,14,*,KNOWN_ALREADY_WORKED,true,false", "mult=21 groups=[w=15,o=6] distinct=7"),
        ])

    static let s34 = Scenario(
        name: "weights-utf16",
        definition: "{exchange: {received: [{id: zone, type: CQ_ZONE}]}, multipliers: [{id: w, set: cq_zones, from: zone, scope: PER_BAND, bandWeights: {\"\u{212A}\": 5, \"\u{C5}\": 3}}], scoring: {total: multTotal}}",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "K", "CW", [.init("zone", "14")]), "w,cq_zones,14,K,KNOWN_NEW_MULTIPLIER,true,true", "mult=1 groups=[w=1] distinct=1"),
            Step(.commit("DL1ABC", "\u{212A}", "CW", [.init("zone", "14")]), "w,cq_zones,14,\\u212A,KNOWN_NEW_MULTIPLIER,true,true", "mult=6 groups=[w=6] distinct=2"),
            Step(.commit("DL1ABC", "A\u{30A}", "CW", [.init("zone", "14")]), "w,cq_zones,14,A\\u030A,KNOWN_NEW_MULTIPLIER,true,true", "mult=7 groups=[w=7] distinct=3"),
            Step(.commit("DL1ABC", "\u{C5}", "CW", [.init("zone", "14")]), "w,cq_zones,14,\\u00C5,KNOWN_NEW_MULTIPLIER,true,true", "mult=10 groups=[w=10] distinct=4"),
        ])

    static let s35 = Scenario(
        name: "weights-canonical-keys",
        definition: "{exchange: {received: [{id: zone, type: CQ_ZONE}]}, multipliers: [{id: w, set: cq_zones, from: zone, scope: PER_BAND, bandWeights: {K: 2, \"\u{212A}\": 5}}], scoring: {total: multTotal}}",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "K", "CW", [.init("zone", "14")]), "w,cq_zones,14,K,KNOWN_NEW_MULTIPLIER,true,true", "mult=2 groups=[w=2] distinct=1"),
            Step(.commit("DL1ABC", "\u{212A}", "CW", [.init("zone", "14")]), "w,cq_zones,14,\\u212A,KNOWN_NEW_MULTIPLIER,true,true", "mult=7 groups=[w=7] distinct=2"),
        ])

    static let s36 = Scenario(
        name: "nil-binding",
        definition: "{exchange: {received: [{id: zone, type: CQ_ZONE}]}, multipliers: [~]}",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "20m", "CW", [.init("zone", "14")]), "EXC NullPointerException: Cannot\\u0020invoke\\u0020\"cz.ok1xoe.maccontestlogger.contest.def.ContestDefinition$MultiplierBinding.appliesWhen()\"\\u0020because\\u0020\"b\"\\u0020is\\u0020null", "EXC NullPointerException: Cannot\\u0020invoke\\u0020\"cz.ok1xoe.maccontestlogger.contest.def.ContestDefinition$MultiplierBinding.bandWeights()\"\\u0020because\\u0020\"b\"\\u0020is\\u0020null"),
        ])

    static let s37 = Scenario(
        name: "nil-binding-mixed",
        definition: "{exchange: {received: [{id: zone, type: CQ_ZONE}]}, multipliers: [{id: a, set: cq_zones, from: zone}, ~, {id: b, set: dxcc_entities, from: callsign}], scoring: {total: multTotal}}",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "20m", "CW", [.init("zone", "14")]), "EXC NullPointerException: Cannot\\u0020invoke\\u0020\"cz.ok1xoe.maccontestlogger.contest.def.ContestDefinition$MultiplierBinding.appliesWhen()\"\\u0020because\\u0020\"b\"\\u0020is\\u0020null", "EXC NullPointerException: Cannot\\u0020invoke\\u0020\"cz.ok1xoe.maccontestlogger.contest.def.ContestDefinition$MultiplierBinding.bandWeights()\"\\u0020because\\u0020\"b\"\\u0020is\\u0020null"),
            Step(.preview("DL1ABC", "20m", "CW", [.init("zone", "14")]), "EXC NullPointerException: Cannot\\u0020invoke\\u0020\"cz.ok1xoe.maccontestlogger.contest.def.ContestDefinition$MultiplierBinding.appliesWhen()\"\\u0020because\\u0020\"b\"\\u0020is\\u0020null", "EXC NullPointerException: Cannot\\u0020invoke\\u0020\"cz.ok1xoe.maccontestlogger.contest.def.ContestDefinition$MultiplierBinding.bandWeights()\"\\u0020because\\u0020\"b\"\\u0020is\\u0020null"),
        ])

    static let s38 = Scenario(
        name: "nil-received-field",
        definition: "{stationClasses: [{id: dx}], exchange: {received: [~, {id: zone, type: CQ_ZONE, appliesWhen: {workedClass: dx}}]}, multipliers: [{id: z, set: cq_zones, from: zone}]}",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "20m", "CW", [.init("zone", "14")]), "EXC NullPointerException: Cannot\\u0020invoke\\u0020\"cz.ok1xoe.maccontestlogger.contest.def.ContestDefinition$ExchangeField.appliesWhen()\"\\u0020because\\u0020\"f\"\\u0020is\\u0020null", "mult=0 groups=[z=0] distinct=0"),
        ])

    static let s39 = Scenario(
        name: "weights-null-value",
        definition: "{exchange: {received: [{id: zone, type: CQ_ZONE}]}, multipliers: [{id: w, set: cq_zones, from: zone, scope: PER_BAND, bandWeights: {80m: ~, 40m: 3}}], scoring: {total: multTotal}}",
        myCall: "OK1XOE",
        steps: [
            Step(.commit("DL1ABC", "20m", "CW", [.init("zone", "14")]), "w,cq_zones,14,20m,KNOWN_NEW_MULTIPLIER,true,true", "mult=1 groups=[w=1] distinct=1"),
            Step(.commit("DL1ABC", "40m", "CW", [.init("zone", "14")]), "w,cq_zones,14,40m,KNOWN_NEW_MULTIPLIER,true,true", "mult=4 groups=[w=4] distinct=2"),
            Step(.commit("DL1ABC", "80m", "CW", [.init("zone", "14")]), "w,cq_zones,14,80m,KNOWN_NEW_MULTIPLIER,true,true", "EXC NullPointerException: Cannot\\u0020invoke\\u0020\"java.lang.Integer.intValue()\"\\u0020because\\u0020the\\u0020return\\u0020value\\u0020of\\u0020\"java.util.Map.getOrDefault(Object\\u002C\\u0020Object)\"\\u0020is\\u0020null"),
        ])

    static let s40 = Scenario(
        name: "tracker",
        definition: "{multipliers: []}",
        myCall: "OK1XOE",
        steps: [
            Step(.tracker("R", "b", "s", "k"), "false", "-"),
            Step(.tracker("W", "b", "s", "k"), "false", "-"),
            Step(.tracker("A", "b", "s", "k"), "true", "-"),
            Step(.tracker("A", "b", "s", "k"), "false", "-"),
            Step(.tracker("W", "b", "s", "k"), "true", "-"),
            Step(.tracker("R", "b", "s", "k"), "false", "-"),
            Step(.tracker("W", "b", "s", "k"), "true", "-"),
            Step(.tracker("R", "b", "s", "k"), "true", "-"),
            Step(.tracker("W", "b", "s", "k"), "false", "-"),
            Step(.tracker("R", "b", "s", "k"), "false", "-"),
            Step(.tracker("R", "b", "other", "k"), "false", "-"),
            Step(.tracker("D", "b", nil, nil), "0", "-"),
            Step(.tracker("A", "b", "s", nil), "true", "-"),
            Step(.tracker("W", "b", "s", nil), "true", "-"),
            Step(.tracker("A", nil, "s", "k"), "true", "-"),
            Step(.tracker("W", nil, "s", "k"), "true", "-"),
            Step(.tracker("D", nil, nil, nil), "1", "-"),
            Step(.tracker("A", "b", "s2", "k"), "true", "-"),
            Step(.tracker("A", "b", "s", "K"), "true", "-"),
            Step(.tracker("A", "b", "s", "\u{212A}"), "true", "-"),
            Step(.tracker("A", "b", "s", "A\u{30A}"), "true", "-"),
            Step(.tracker("A", "b", "s2", "\u{C5}"), "true", "-"),
            Step(.tracker("D", "b", nil, nil), "6", "-"),
            Step(.tracker("K", "b", nil, nil), "~;A\\u030A;K;k;\\u00C5;\\u212A", "-"),
            Step(.tracker("N", nil, nil, nil), "7", "-"),
            Step(.tracker("W", "b", "S", "k"), "false", "-"),
            Step(.tracker("W", "b", "s", "\u{C5}"), "false", "-"),
            Step(.tracker("W", "\u{212A}", "s", "k"), "false", "-"),
            Step(.tracker("K", "zz", nil, nil), "", "-"),
            Step(.tracker("D", "zz", nil, nil), "0", "-"),
            Step(.tracker("R", "b", "s", nil), "true", "-"),
            Step(.tracker("K", "b", nil, nil), "A\\u030A;K;k;\\u00C5;\\u212A", "-"),
            Step(.tracker("N", nil, nil, nil), "6", "-"),
        ])

    static let scenarios: [Scenario] = [
        s0,
        s1,
        s2,
        s3,
        s4,
        s5,
        s6,
        s7,
        s8,
        s9,
        s10,
        s11,
        s12,
        s13,
        s14,
        s15,
        s16,
        s17,
        s18,
        s19,
        s20,
        s21,
        s22,
        s23,
        s24,
        s25,
        s26,
        s27,
        s28,
        s29,
        s30,
        s31,
        s32,
        s33,
        s34,
        s35,
        s36,
        s37,
        s38,
        s39,
        s40,
    ]
}
