// Table measured on Java (JDK 21.0.2) by the probe `ProbeGrab.java`
// (maintainer-only probe): `ExchangeGrab.normalize`,
// `ExchangeGrab.route` (also successively over one map) and `SpotExchangeEstimator.estimate`.
// Rows are not edited by hand — they are regenerated by the script `gen_swift.py`. The result is the probe
// text (`GrabMeasuredTests` composes it the same way).

@testable import MCLCore

enum GrabMeasured {
    enum Outcome: Sendable, Equatable {
        case text(String)
        /// Java fails with a NullPointerException; Swift is lenient (a deliberate divergence from Java v1.1.1).
        case npe
    }

    /// DXCC source for the estimate: fixture `dxcc-test.json`, the test's fake table, Java `null`.
    enum Dxcc: Sendable {
        case fixture, fake, none
    }

    /// `normalize(token)`.
    struct NormalizeRow: Sendable, CustomStringConvertible {
        let label: String
        let token: String?
        let java: Outcome
        init(_ label: String, _ token: String?, _ java: Outcome) {
            self.label = label; self.token = token; self.java = java
        }
        var description: String { label }
    }

    /// `route(fields, current, token)`; the fields are the inside of `{exchange: {received: [...]}}`,
    /// `nil` = a `null` list; `current == nil` is Java `null`.
    struct RouteRow: Sendable, CustomStringConvertible {
        let label: String
        let fields: String?
        let current: [(String?, String?)]?
        let token: String?
        let java: Outcome
        init(_ label: String, _ fields: String?, _ current: [(String?, String?)]?,
             _ token: String?, _ java: Outcome) {
            self.label = label; self.fields = fields; self.current = current
            self.token = token; self.java = java
        }
        var description: String { label }
    }

    /// Successive `route` over one map, the result is inserted into it (Java `HashMap`).
    struct SequenceRow: Sendable, CustomStringConvertible {
        let label: String
        let fields: String?
        let tokens: [String?]
        let java: Outcome
        init(_ label: String, _ fields: String?, _ tokens: [String?], _ java: Outcome) {
            self.label = label; self.fields = fields; self.tokens = tokens; self.java = java
        }
        var description: String { label }
    }

    /// `estimate(fields, call, dxcc, hqCalls, gridByCall)`.
    struct EstimateRow: Sendable, CustomStringConvertible {
        let label: String
        let fields: String?
        let call: String?
        let dxcc: Dxcc
        let hq: [(String?, String?)]?
        let grid: [(String?, String?)]?
        let java: Outcome
        init(_ label: String, _ fields: String?, _ call: String?, _ dxcc: Dxcc,
             _ hq: [(String?, String?)]?, _ grid: [(String?, String?)]?, _ java: Outcome) {
            self.label = label; self.fields = fields; self.call = call; self.dxcc = dxcc
            self.hq = hq; self.grid = grid; self.java = java
        }
        var description: String { label }
    }

    static let normalize: [NormalizeRow] = [
        NormalizeRow("null", nil, .text("")),
        NormalizeRow("empty", "", .text("")),
        NormalizeRow("spaces", "  ", .text("")),
        NormalizeRow("stars", "***", .text("")),
        NormalizeRow("paren-ct", "(ct)", .text("CT")),
        NormalizeRow("call-portable", "ok1xoe/p", .text("OK1XOE/P")),
        NormalizeRow("ellipsis", "\u{2026}OK\u{2026}", .text("OK")),
        NormalizeRow("sharp-s", "stra\u{DF}e", .text("STRASSE")),
        NormalizeRow("z-caron", "Ž", .text("\\u017D")),
        NormalizeRow("dash", "-", .text("-")),
        NormalizeRow("slash", "/", .text("/")),
        NormalizeRow("dashes-a", "--a--", .text("--A--")),
        NormalizeRow("ctl-599", "\u{1}599\u{1}", .text("599")),
        NormalizeRow("nbsp-599", "\u{A0}599\u{A0}", .text("599")),
        NormalizeRow("emsp-599", "\u{2003}599\u{2003}", .text("599")),
        NormalizeRow("dotless-i", "\u{131}", .text("I")),
        NormalizeRow("ligature-ff", "\u{FB00}", .text("FF")),
        NormalizeRow("kelvin", "\u{212A}", .text("\\u212A")),
        NormalizeRow("emoji-a", "\u{1F600}a", .text("A")),
        NormalizeRow("a-emoji", "a\u{1F600}", .text("A")),
        NormalizeRow("arabic-3", "\u{663}", .text("\\u0663")),
        NormalizeRow("inner-dot", "a.b", .text("A.B")),
        NormalizeRow("quotes-59", "'59'", .text("59")),
        NormalizeRow("underscore", "_x_", .text("X")),
        NormalizeRow("titlecase-dz", "\u{1C5}", .text("\\u01C4")),
        NormalizeRow("n-apostrophe", "\u{149}", .text("\\u02BCN")),
        NormalizeRow("iota-dialytika", "\u{390}", .text("\\u0399")),
        NormalizeRow("combining-end", "a\u{301}", .text("A")),
        NormalizeRow("combining-start", "\u{301}a", .text("A")),
        NormalizeRow("roman-numeral", "\u{2160}", .text("")),
        NormalizeRow("superscript-2", "x\u{B2}", .text("X")),
        NormalizeRow("tab-nl", "\u{9}ny\u{A}", .text("NY")),
        NormalizeRow("inner-space", "a b", .text("A\\u0020B")),
        NormalizeRow("replacement-char", "\u{FFFD}a", .text("A")),
        NormalizeRow("plus5", "+5", .text("5")),
        NormalizeRow("minus5", "-5", .text("-5")),
        NormalizeRow("fullwidth", "\u{FF41}\u{FF11}", .text("\\uFF21\\uFF11")),
    ]

    static let route: [RouteRow] = [
        RouteRow("cqww-599", "{id: rst, type: RST}, {id: zone, type: CQ_ZONE, validation: {min: 1, max: 40}}, {id: state, type: STATE}", [], "599", .text("rst=599")),
        RouteRow("cqww-15-rst-filled", "{id: rst, type: RST}, {id: zone, type: CQ_ZONE, validation: {min: 1, max: 40}}, {id: state, type: STATE}", [("rst", "599")], "15", .text("zone=15")),
        RouteRow("cqww-15-empty", "{id: rst, type: RST}, {id: zone, type: CQ_ZONE, validation: {min: 1, max: 40}}, {id: state, type: STATE}", [], "15", .text("zone=15")),
        RouteRow("cqww-77", "{id: rst, type: RST}, {id: zone, type: CQ_ZONE, validation: {min: 1, max: 40}}, {id: state, type: STATE}", [("rst", "599")], "77", .text("empty")),
        RouteRow("cqww-ct", "{id: rst, type: RST}, {id: zone, type: CQ_ZONE, validation: {min: 1, max: 40}}, {id: state, type: STATE}", [("rst", "599"), ("zone", "5")], "CT", .text("state=CT")),
        RouteRow("cqww-14-zone-empty", "{id: rst, type: RST}, {id: zone, type: CQ_ZONE, validation: {min: 1, max: 40}}, {id: state, type: STATE}", [("rst", "599"), ("zone", "")], "14", .text("zone=14")),
        RouteRow("cqww-14-zone-filled", "{id: rst, type: RST}, {id: zone, type: CQ_ZONE, validation: {min: 1, max: 40}}, {id: state, type: STATE}", [("rst", "599"), ("zone", "15")], "14", .text("zone=14")),
        RouteRow("cqww-paren-ct", "{id: rst, type: RST}, {id: zone, type: CQ_ZONE, validation: {min: 1, max: 40}}, {id: state, type: STATE}", [("rst", "599"), ("zone", "5")], "(ct)", .text("state=CT")),
        RouteRow("cqww-call", "{id: rst, type: RST}, {id: zone, type: CQ_ZONE, validation: {min: 1, max: 40}}, {id: state, type: STATE}", [], "OK1XOE", .text("empty")),
        RouteRow("cqww-blank", "{id: rst, type: RST}, {id: zone, type: CQ_ZONE, validation: {min: 1, max: 40}}, {id: state, type: STATE}", [], "  ", .text("empty")),
        RouteRow("cqww-stars", "{id: rst, type: RST}, {id: zone, type: CQ_ZONE, validation: {min: 1, max: 40}}, {id: state, type: STATE}", [], "***", .text("empty")),
        RouteRow("cqww-05-repeat", "{id: rst, type: RST}, {id: zone, type: CQ_ZONE, validation: {min: 1, max: 40}}, {id: state, type: STATE}", [("rst", "599"), ("zone", "05")], "05", .text("zone=05")),
        RouteRow("serial-length-007", "{id: rst, type: RST}, {id: nr, type: SERIAL, validation: {length: 3}}", [("rst", "599")], "007", .text("nr=007")),
        RouteRow("serial-length-7", "{id: rst, type: RST}, {id: nr, type: SERIAL, validation: {length: 3}}", [("rst", "599")], "7", .text("empty")),
        RouteRow("locator-jn88wx", "{id: grid, type: LOCATOR}", [], "JN88wx", .text("grid=JN88WX")),
        RouteRow("locator-jn", "{id: grid, type: LOCATOR}", [], "JN", .text("empty")),
        RouteRow("regex-oh", "{id: sect, type: TEXT, validation: {regex: '[A-Z]{2,3}'}}", [], "OH", .text("sect=OH")),
        RouteRow("regex-ohiox", "{id: sect, type: TEXT, validation: {regex: '[A-Z]{2,3}'}}", [], "OHIOX", .text("empty")),
        RouteRow("type-RST-599", "{id: f, type: RST}", [], "599", .text("f=599")),
        RouteRow("type-RST-111", "{id: f, type: RST}", [], "111", .text("f=111")),
        RouteRow("type-RST-600", "{id: f, type: RST}", [], "600", .text("empty")),
        RouteRow("type-RST-509", "{id: f, type: RST}", [], "509", .text("empty")),
        RouteRow("type-RST-590", "{id: f, type: RST}", [], "590", .text("empty")),
        RouteRow("type-RST-59", "{id: f, type: RST}", [], "59", .text("empty")),
        RouteRow("type-RST-5999", "{id: f, type: RST}", [], "5999", .text("empty")),
        RouteRow("type-RS-59", "{id: f, type: RS}", [], "59", .text("f=59")),
        RouteRow("type-RS-50", "{id: f, type: RS}", [], "50", .text("empty")),
        RouteRow("type-RS-5", "{id: f, type: RS}", [], "5", .text("empty")),
        RouteRow("type-RS-69", "{id: f, type: RS}", [], "69", .text("empty")),
        RouteRow("type-RS-11", "{id: f, type: RS}", [], "11", .text("f=11")),
        RouteRow("type-SERIAL-0", "{id: f, type: SERIAL}", [], "0", .text("f=0")),
        RouteRow("type-SERIAL-9999", "{id: f, type: SERIAL}", [], "9999", .text("f=9999")),
        RouteRow("type-SERIAL-10000", "{id: f, type: SERIAL}", [], "10000", .text("empty")),
        RouteRow("type-SERIAL-\\u{663}", "{id: f, type: SERIAL}", [], "\u{663}", .text("empty")),
        RouteRow("type-SERIAL--5", "{id: f, type: SERIAL}", [], "-5", .text("empty")),
        RouteRow("type-SERIAL-0007", "{id: f, type: SERIAL}", [], "0007", .text("f=0007")),
        RouteRow("type-INTEGER-42", "{id: f, type: INTEGER}", [], "42", .text("f=42")),
        RouteRow("type-CQ_ZONE-05", "{id: f, type: CQ_ZONE}", [], "05", .text("f=05")),
        RouteRow("type-ITU_ZONE-90", "{id: f, type: ITU_ZONE}", [], "90", .text("f=90")),
        RouteRow("type-LOCATOR-jn88wx", "{id: f, type: LOCATOR}", [], "jn88wx", .text("f=JN88WX")),
        RouteRow("type-LOCATOR-JS88", "{id: f, type: LOCATOR}", [], "JS88", .text("empty")),
        RouteRow("type-LOCATOR-JN88YX", "{id: f, type: LOCATOR}", [], "JN88YX", .text("empty")),
        RouteRow("type-LOCATOR-JN8", "{id: f, type: LOCATOR}", [], "JN8", .text("empty")),
        RouteRow("type-LOCATOR-RR99XX", "{id: f, type: LOCATOR}", [], "RR99XX", .text("f=RR99XX")),
        RouteRow("type-LOCATOR-AA00", "{id: f, type: LOCATOR}", [], "AA00", .text("f=AA00")),
        RouteRow("type-LOCATOR-JN88W", "{id: f, type: LOCATOR}", [], "JN88W", .text("empty")),
        RouteRow("type-IOTA-EU-001", "{id: f, type: IOTA}", [], "EU-001", .text("f=EU-001")),
        RouteRow("type-IOTA-EU001", "{id: f, type: IOTA}", [], "EU001", .text("f=EU001")),
        RouteRow("type-IOTA-EU-1", "{id: f, type: IOTA}", [], "EU-1", .text("f=EU-1")),
        RouteRow("type-IOTA-EU-0001", "{id: f, type: IOTA}", [], "EU-0001", .text("empty")),
        RouteRow("type-IOTA-E-1", "{id: f, type: IOTA}", [], "E-1", .text("empty")),
        RouteRow("type-IOTA-eu-12", "{id: f, type: IOTA}", [], "eu-12", .text("f=EU-12")),
        RouteRow("type-STATE-CT", "{id: f, type: STATE}", [], "CT", .text("f=CT")),
        RouteRow("type-STATE-ABCD", "{id: f, type: STATE}", [], "ABCD", .text("f=ABCD")),
        RouteRow("type-STATE-ABCDE", "{id: f, type: STATE}", [], "ABCDE", .text("empty")),
        RouteRow("type-STATE-C1", "{id: f, type: STATE}", [], "C1", .text("empty")),
        RouteRow("type-STATE-\\u{17D}", "{id: f, type: STATE}", [], "Ž", .text("empty")),
        RouteRow("type-PROVINCE-ON", "{id: f, type: PROVINCE}", [], "ON", .text("f=ON")),
        RouteRow("type-NATIONAL-OK", "{id: f, type: NATIONAL}", [], "OK", .text("f=OK")),
        RouteRow("type-NATIONAL-123", "{id: f, type: NATIONAL}", [], "123", .text("empty")),
        RouteRow("type-NATIONAL-OK1234", "{id: f, type: NATIONAL}", [], "OK1234", .text("f=OK1234")),
        RouteRow("type-NATIONAL-OK12345", "{id: f, type: NATIONAL}", [], "OK12345", .text("empty")),
        RouteRow("type-NATIONAL-1A", "{id: f, type: NATIONAL}", [], "1A", .text("f=1A")),
        RouteRow("type-HQ-DARC", "{id: f, type: HQ}", [], "DARC", .text("f=DARC")),
        RouteRow("type-DXCC-OK", "{id: f, type: DXCC}", [], "OK", .text("f=OK")),
        RouteRow("type-PREFIX-OK1", "{id: f, type: PREFIX}", [], "OK1", .text("f=OK1")),
        RouteRow("type-DISTRICT-123", "{id: f, type: DISTRICT}", [], "123", .text("f=123")),
        RouteRow("type-DISTRICT-ABCDEFG", "{id: f, type: DISTRICT}", [], "ABCDEFG", .text("empty")),
        RouteRow("type-DISTRICT-A1", "{id: f, type: DISTRICT}", [], "A1", .text("f=A1")),
        RouteRow("type-TEXT-ok1xoe/p", "{id: f, type: TEXT}", [], "ok1xoe/p", .text("f=OK1XOE/P")),
        RouteRow("type-TEXT--", "{id: f, type: TEXT}", [], "-", .text("f=-")),
        RouteRow("type-TEXT-/", "{id: f, type: TEXT}", [], "/", .text("f=/")),
        RouteRow("type-TEXT-ABCDEFGHIJ", "{id: f, type: TEXT}", [], "ABCDEFGHIJ", .text("f=ABCDEFGHIJ")),
        RouteRow("type-TEXT-ABCDEFGHIJK", "{id: f, type: TEXT}", [], "ABCDEFGHIJK", .text("empty")),
        RouteRow("type-TEXT-a.b", "{id: f, type: TEXT}", [], "a.b", .text("empty")),
        RouteRow("type-TEXT-\\u{2160}", "{id: f, type: TEXT}", [], "\u{2160}", .text("empty")),
        RouteRow("type-QTC-1", "{id: f, type: QTC}", [], "1", .text("empty")),
        RouteRow("type-QTC-A", "{id: f, type: QTC}", [], "A", .text("empty")),
        RouteRow("minmax-40", "{id: rst, type: RST}, {id: zone, type: CQ_ZONE, validation: {min: 1, max: 40}}, {id: state, type: STATE}", [("rst", "599")], "40", .text("zone=40")),
        RouteRow("minmax-41", "{id: rst, type: RST}, {id: zone, type: CQ_ZONE, validation: {min: 1, max: 40}}, {id: state, type: STATE}", [("rst", "599")], "41", .text("empty")),
        RouteRow("minmax-1", "{id: rst, type: RST}, {id: zone, type: CQ_ZONE, validation: {min: 1, max: 40}}, {id: state, type: STATE}", [("rst", "599")], "1", .text("zone=1")),
        RouteRow("minmax-0", "{id: rst, type: RST}, {id: zone, type: CQ_ZONE, validation: {min: 1, max: 40}}, {id: state, type: STATE}", [("rst", "599")], "0", .text("empty")),
        RouteRow("minmax-01", "{id: rst, type: RST}, {id: zone, type: CQ_ZONE, validation: {min: 1, max: 40}}, {id: state, type: STATE}", [("rst", "599")], "01", .text("zone=01")),
        RouteRow("text-min-minus5", "{id: t, type: TEXT, validation: {min: -10}}", [], "-5", .text("t=-5")),
        RouteRow("text-min-plus5", "{id: t, type: TEXT, validation: {min: 1}}", [], "+5", .text("t=5")),
        RouteRow("text-min-arabic", "{id: t, type: TEXT, validation: {min: 1}}", [], "\u{663}", .text("empty")),
        RouteRow("text-min-overflow", "{id: t, type: TEXT, validation: {min: 1}}", [], "2147483648", .text("empty")),
        RouteRow("text-max-intmax", "{id: t, type: TEXT, validation: {max: 2147483647}}", [], "2147483647", .text("t=2147483647")),
        RouteRow("text-min-letters", "{id: t, type: TEXT, validation: {min: 1}}", [], "ABC", .text("empty")),
        RouteRow("length-sharp-s", "{id: t, type: TEXT, validation: {length: 7}}", [], "stra\u{DF}e", .text("t=STRASSE")),
        RouteRow("length-sharp-s-6", "{id: t, type: TEXT, validation: {length: 6}}", [], "stra\u{DF}e", .text("empty")),
        RouteRow("regex-case", "{id: t, type: TEXT, validation: {regex: '[a-z]+'}}", [], "abc", .text("empty")),
        RouteRow("regex-ci", "{id: t, type: TEXT, validation: {regex: '(?i)[a-z]+'}}", [], "abc", .text("t=ABC")),
        RouteRow("regex-unicode-class", "{id: t, type: TEXT, validation: {regex: '\\p{Lu}+'}}", [], "abc", .text("t=ABC")),
        RouteRow("bad-regex-double-backslash", "{id: t, type: TEXT, validation: {regex: '\\\\p{Lu}+'}}", [], "abc", .text("EXC PatternSyntaxException: Illegal\\u0020repetition\\u0020near\\u0020index\\u00204\\u000A\\u005C\\u005Cp{Lu}+\\u000A\\u0020\\u0020\\u0020\\u0020^")),
        RouteRow("regex-and-length", "{id: t, type: TEXT, validation: {regex: '[A-Z]+', length: 2}}", [], "ABC", .text("empty")),
        RouteRow("regex-partial", "{id: t, type: TEXT, validation: {regex: 'AB'}}", [], "ABC", .text("empty")),
        RouteRow("regex-empty", "{id: t, type: TEXT, validation: {regex: ''}}", [], "ABC", .text("empty")),
        RouteRow("bad-regex-paren", "{id: t, type: TEXT, validation: {regex: '('}}", [], "ABC", .text("EXC PatternSyntaxException: Unclosed\\u0020group\\u0020near\\u0020index\\u00201\\u000A(")),
        RouteRow("bad-regex-class", "{id: t, type: TEXT, validation: {regex: '[a-'}}", [], "ABC", .text("EXC PatternSyntaxException: Illegal\\u0020character\\u0020range\\u0020near\\u0020index\\u00203\\u000A[a-")),
        RouteRow("bad-regex-second", "{id: a, type: TEXT}, {id: t, type: TEXT, validation: {regex: '('}}", [], "ABC", .text("EXC PatternSyntaxException: Unclosed\\u0020group\\u0020near\\u0020index\\u00201\\u000A(")),
        RouteRow("bad-regex-first-typed-out", "{id: t, type: RST, validation: {regex: '('}}", [], "ABC", .text("EXC PatternSyntaxException: Unclosed\\u0020group\\u0020near\\u0020index\\u00201\\u000A(")),
        RouteRow("bad-regex-empty-token", "{id: t, type: TEXT, validation: {regex: '('}}", [], "***", .text("empty")),
        RouteRow("bad-regex-null-fields-ok", nil, [], "ABC", .text("empty")),
        RouteRow("bad-regex-after-null-element", "~, {id: t, type: TEXT, validation: {regex: '('}}", [], "ABC", .npe),
        RouteRow("bad-regex-tab", "{id: t, type: TEXT, validation: {regex: \"\\ta(\"}}", [], "ABC", .text("EXC PatternSyntaxException: Unclosed\\u0020group\\u0020near\\u0020index\\u00203\\u000A\\u0009a(")),
        RouteRow("bad-regex-two-class-first", "{id: a, type: TEXT, validation: {regex: '[a-'}}, {id: t, type: TEXT, validation: {regex: '('}}", [], "ABC", .text("EXC PatternSyntaxException: Illegal\\u0020character\\u0020range\\u0020near\\u0020index\\u00203\\u000A[a-")),
        RouteRow("bad-regex-two-paren-first", "{id: a, type: TEXT, validation: {regex: '('}}, {id: t, type: TEXT, validation: {regex: '[a-'}}", [], "ABC", .text("EXC PatternSyntaxException: Unclosed\\u0020group\\u0020near\\u0020index\\u00201\\u000A(")),
        RouteRow("bad-regex-newline", "{id: t, type: TEXT, validation: {regex: \"A\\n(\"}}", [], "ABC", .text("EXC PatternSyntaxException: Unclosed\\u0020group\\u0020near\\u0020index\\u00203\\u000AA\\u000A(")),
        RouteRow("bad-regex-line-separator", "{id: t, type: TEXT, validation: {regex: \"A\\u2028(\"}}", [], "ABC", .text("EXC PatternSyntaxException: Unclosed\\u0020group\\u0020near\\u0020index\\u00203\\u000AA\\u2028(")),
        RouteRow("bad-regex-newline-before-error", "{id: t, type: TEXT, validation: {regex: \"AB\\n\\nC[\"}}", [], "ABC", .text("EXC PatternSyntaxException: Unclosed\\u0020character\\u0020class\\u0020near\\u0020index\\u00205\\u000AAB\\u000A\\u000AC[\\u000A\\u0020\\u0020\\u0020\\u0020\\u0020^")),
        RouteRow("regex-java-lower", "{id: t, type: TEXT, validation: {regex: '\\p{javaLowerCase}+'}}", [], "ABC", .text("empty")),
        RouteRow("regex-java-upper", "{id: t, type: TEXT, validation: {regex: '\\p{javaUpperCase}+'}}", [], "ABC", .text("t=ABC")),
        RouteRow("regex-deep-nesting", "{id: t, type: TEXT, validation: {regex: '(((((((((((((((((A)))))))))))))))))'}}", [], "A", .text("t=A")),
        RouteRow("regex-comments", "{id: t, type: TEXT, validation: {regex: '(?x) A B C'}}", [], "abd", .text("empty")),
        RouteRow("fields-null", nil, [], "599", .text("empty")),
        RouteRow("fields-empty", "", [], "599", .text("empty")),
        RouteRow("null-element", "~, {id: rst, type: RST}", [], "599", .npe),
        RouteRow("null-element-after-match", "{id: rst, type: RST}, ~", [], "599", .npe),
        RouteRow("null-type", "{id: t}", [], "599", .npe),
        RouteRow("null-type-after", "{id: rst, type: RST}, {id: t}", [], "599", .npe),
        RouteRow("current-null-accepting", "{id: rst, type: RST}, {id: zone, type: CQ_ZONE, validation: {min: 1, max: 40}}, {id: state, type: STATE}", nil, "599", .npe),
        RouteRow("current-null-nothing", "{id: rst, type: RST}, {id: zone, type: CQ_ZONE, validation: {min: 1, max: 40}}, {id: state, type: STATE}", nil, "OK1XOE", .text("empty")),
        RouteRow("null-id-immutable", "{type: RST}", [], "599", .npe),
        RouteRow("null-id-immutable-filled", "{type: RST}", [("a", "1")], "599", .npe),
        RouteRow("null-id-hashmap", "{type: RST}", [], "599", .text("~=599")),
        RouteRow("null-id-hashmap-filled", "{type: RST}, {id: b, type: RST}", [(nil, "579")], "599", .text("b=599")),
        RouteRow("dup-id-filled", "{id: z, type: CQ_ZONE}, {id: z, type: INTEGER}", [("z", "5")], "14", .text("z=14")),
        RouteRow("second-empty", "{id: a, type: INTEGER}, {id: b, type: INTEGER}", [("a", "5")], "14", .text("b=14")),
        RouteRow("blank-space", "{id: a, type: INTEGER}, {id: b, type: INTEGER}", [("a", " "), ("b", "")], "14", .text("a=14")),
        RouteRow("blank-nbsp", "{id: a, type: INTEGER}, {id: b, type: INTEGER}", [("a", "\u{A0}")], "14", .text("b=14")),
        RouteRow("blank-emsp", "{id: a, type: INTEGER}, {id: b, type: INTEGER}", [("a", "\u{2003}"), ("b", "1")], "14", .text("a=14")),
        RouteRow("blank-ctl", "{id: a, type: INTEGER}, {id: b, type: INTEGER}", [("a", "\u{1}")], "14", .text("b=14")),
        RouteRow("blank-null-value", "{id: a, type: INTEGER}, {id: b, type: INTEGER}", [("a", nil), ("b", "")], "14", .text("a=14")),
        RouteRow("utf16-key", "{id: \"A\u{30A}\", type: INTEGER}, {id: b, type: INTEGER}", [("\u{C5}", "1")], "14", .text("A\\u030A=14")),
        RouteRow("utf16-key-exact", "{id: \"A\u{30A}\", type: INTEGER}, {id: b, type: INTEGER}", [("A\u{30A}", "1")], "14", .text("b=14")),
        RouteRow("token-null", "{id: rst, type: RST}, {id: zone, type: CQ_ZONE, validation: {min: 1, max: 40}}, {id: state, type: STATE}", [], nil, .text("empty")),
    ]

    static let sequence: [SequenceRow] = [
        SequenceRow("seq-599-05-ny", "{id: rst, type: RST}, {id: zone, type: CQ_ZONE, validation: {min: 1, max: 40}}, {id: state, type: STATE}", ["599", "05", "NY"], .text("rst=599;zone=05;state=NY")),
        SequenceRow("seq-05-599-ny", "{id: rst, type: RST}, {id: zone, type: CQ_ZONE, validation: {min: 1, max: 40}}, {id: state, type: STATE}", ["05", "599", "NY"], .text("zone=05;rst=599;state=NY")),
        SequenceRow("seq-599-05-05", "{id: rst, type: RST}, {id: zone, type: CQ_ZONE, validation: {min: 1, max: 40}}, {id: state, type: STATE}", ["599", "05", "05"], .text("rst=599;zone=05;zone=05")),
        SequenceRow("seq-ny-tx-ca", "{id: rst, type: RST}, {id: zone, type: CQ_ZONE, validation: {min: 1, max: 40}}, {id: state, type: STATE}", ["NY", "TX", "CA"], .text("state=NY;state=TX;state=CA")),
        SequenceRow("seq-null-id", "{type: INTEGER}, {id: b, type: INTEGER}", ["1", "2", "3"], .text("~=1;b=2;~=3")),
    ]

    static let estimate: [EstimateRow] = [
        EstimateRow("itu-ok", "{id: exch, estimate: ituZone}", "OK1ABC", .fixture, [], [], .text("exch=28")),
        EstimateRow("grid-lookup", "{id: grid, estimate: grid}", "OK1ABC", .fixture, [], [("OK1ABC", "JO70")], .text("grid=JO70")),
        EstimateRow("grid-none", "{id: grid, estimate: grid}", "OK1ABC", .fixture, [], [], .text("")),
        EstimateRow("cq-continent", "{id: z, estimate: cqZone}, {id: c, estimate: continent}", "OK1ABC", .fixture, [], [], .text("z=15;c=EU")),
        EstimateRow("no-estimate", "{id: rst}, {id: exch, estimate: ituZone}", "OK1ABC", .fixture, [], [], .text("exch=28")),
        EstimateRow("unknown-call", "{id: exch, estimate: ituZone}", "XYZ999QQ", .fixture, [], [], .text("")),
        EstimateRow("iaru-hq", "{id: exch, estimate: iaruExch}", "DA0HQ", .fixture, [("DA0HQ", "DARC")], [], .text("exch=DARC")),
        EstimateRow("iaru-non-hq", "{id: exch, estimate: iaruExch}", "OK1ABC", .fixture, [("DA0HQ", "DARC")], [], .text("exch=28")),
        EstimateRow("iaru-empty-hq", "{id: exch, estimate: iaruExch}", "OK1ABC", .fixture, [], [], .text("exch=28")),
        EstimateRow("w-first-zones", "{id: i, estimate: ituZone}, {id: z, estimate: cqZone}, {id: c, estimate: continent}", "W1AW", .fixture, [], [], .text("i=6;z=3;c=NA")),
        EstimateRow("ve-first-zones", "{id: i, estimate: ituZone}, {id: z, estimate: cqZone}", "VE3AA", .fixture, [], [], .text("i=2;z=1")),
        EstimateRow("deleted-entity", "{id: exch, estimate: ituZone}", "XX1A", .fixture, [], [], .text("")),
        EstimateRow("kind-padded", "{id: exch, estimate: \" ituZone\u{9}\"}", "OK1ABC", .fixture, [], [], .text("exch=28")),
        EstimateRow("kind-upper", "{id: exch, estimate: ITUZONE}", "OK1ABC", .fixture, [], [], .text("")),
        EstimateRow("kind-blank", "{id: exch, estimate: \" \"}", "OK1ABC", .fixture, [], [], .text("")),
        EstimateRow("kind-emsp", "{id: exch, estimate: \"\u{2003}\"}", "OK1ABC", .fixture, [], [], .text("")),
        EstimateRow("kind-nbsp", "{id: exch, estimate: \"\u{A0}ituZone\"}", "OK1ABC", .fixture, [], [], .text("")),
        EstimateRow("kind-emsp-pad", "{id: exch, estimate: \"\u{2003}ituZone\"}", "OK1ABC", .fixture, [], [], .text("")),
        EstimateRow("kind-unknown", "{id: exch, estimate: foo}", "OK1ABC", .fixture, [], [], .text("")),
        EstimateRow("call-padded-lower", "{id: exch, estimate: iaruExch}, {id: g, estimate: grid}", " ok1abc ", .fixture, [("OK1ABC", "CRK")], [("OK1ABC", "JO70")], .text("exch=CRK;g=JO70")),
        EstimateRow("call-padded-zone", "{id: exch, estimate: ituZone}", " ok1abc ", .fixture, [], [], .text("exch=28")),
        EstimateRow("call-lower-hq-key-lower", "{id: exch, estimate: iaruExch}", "da0hq", .fixture, [("da0hq", "DARC")], [], .text("exch=28")),
        EstimateRow("call-sharp-s", "{id: g, estimate: grid}", "stra\u{DF}e", .fixture, [], [("STRASSE", "JN00")], .text("g=JN00")),
        EstimateRow("call-null", "{id: exch, estimate: ituZone}", nil, .fixture, [], [], .text("")),
        EstimateRow("received-null", nil, "OK1ABC", .fixture, [], [], .text("")),
        EstimateRow("dxcc-null-grid", "{id: g, estimate: grid}", "OK1ABC", .none, [], [("OK1ABC", "JO70")], .text("")),
        EstimateRow("hq-null-map", "{id: exch, estimate: iaruExch}", "OK1ABC", .fixture, nil, nil, .text("exch=28")),
        EstimateRow("grid-null-map", "{id: g, estimate: grid}", "OK1ABC", .fixture, [], nil, .text("")),
        EstimateRow("hq-empty-value", "{id: exch, estimate: iaruExch}", "OK1ABC", .fixture, [("OK1ABC", "")], [], .text("")),
        EstimateRow("hq-blank-value", "{id: exch, estimate: iaruExch}", "OK1ABC", .fixture, [("OK1ABC", "\u{2003}")], [], .text("")),
        EstimateRow("hq-nbsp-value", "{id: exch, estimate: iaruExch}", "OK1ABC", .fixture, [("OK1ABC", "\u{A0}")], [], .text("exch=\\u00A0")),
        EstimateRow("hq-null-value", "{id: exch, estimate: iaruExch}", "OK1ABC", .fixture, [("OK1ABC", nil)], [], .text("exch=28")),
        EstimateRow("hq-unknown-call", "{id: exch, estimate: iaruExch}", "ZZ9HQ", .fixture, [("ZZ9HQ", "XYZ")], [], .text("exch=XYZ")),
        EstimateRow("grid-blank", "{id: g, estimate: grid}", "OK1ABC", .fixture, [], [("OK1ABC", "  ")], .text("")),
        EstimateRow("grid-unknown-call", "{id: g, estimate: grid}", "ZZ9ZZ", .fixture, [], [("ZZ9ZZ", "AA00")], .text("g=AA00")),
        EstimateRow("fake-null-first", "{id: i, estimate: ituZone}, {id: z, estimate: cqZone}, {id: e, estimate: iaruExch}", "NI1A", .fake, [], [], .text("i=null;z=null;e=null")),
        EstimateRow("fake-empty-lists", "{id: i, estimate: ituZone}, {id: z, estimate: cqZone}, {id: c, estimate: continent}", "EI1A", .fake, [], [], .text("c=EU")),
        EstimateRow("fake-null-lists", "{id: i, estimate: ituZone}, {id: z, estimate: cqZone}, {id: c, estimate: continent}", "NU1A", .fake, [], [], .text("")),
        EstimateRow("fake-null-continent", "{id: c, estimate: continent}", "NC1A", .fake, [], [], .text("")),
        EstimateRow("fake-empty-continents", "{id: c, estimate: continent}", "EC1A", .fake, [], [], .text("")),
        EstimateRow("fake-blank-continent", "{id: c, estimate: continent}", "BC1A", .fake, [], [], .text("")),
        EstimateRow("fake-original-call", "{id: i, estimate: ituZone}, {id: g, estimate: grid}", " sp1a ", .fake, [], [("SP1A", "KO02")], .text("i=29;g=KO02")),
        EstimateRow("dup-id", "{id: x, estimate: cqZone}, {id: y, estimate: continent}, {id: x, estimate: ituZone}", "OK1ABC", .fixture, [], [], .text("x=28;y=EU")),
        EstimateRow("null-id", "{estimate: cqZone}, {id: y, estimate: continent}", "OK1ABC", .fixture, [], [], .text("~=15;y=EU")),
        EstimateRow("null-element", "~, {id: exch, estimate: ituZone}", "OK1ABC", .fixture, [], [], .npe),
        EstimateRow("null-element-no-call", "~, {id: exch, estimate: ituZone}", nil, .fixture, [], [], .text("")),
        EstimateRow("order", "{id: c, estimate: continent}, {id: a, estimate: ituZone}, {id: b, estimate: cqZone}", "OK1ABC", .fixture, [], [], .text("c=EU;a=28;b=15")),
    ]
}
