// Generated by a maintainer-only probe from the ProbeSessionTable output
// (JDK 21.0.2) — do not edit by hand; procedure in a maintainer-only probe

/// `ContestSession` table measured on Java v1.1.1.
enum SessionMeasured {
    static let javaVersion = "21.0.2"

    /// Cases (maintainer-only probe without comments).
    static let cases = #"""
    S ¦ bonus-once ¦ fake ¦ {scoring: {bonuses: [{id: b, value: {fixed: 10}, scope: ONCE}], total: "bonusPoints"}} ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ OK1AA ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AB ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AC ¦ 40m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AD ¦ 20m ¦ SSB ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AE ¦ 40m ¦ SSB ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AA ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    S ¦ bonus-no-scope ¦ fake ¦ {scoring: {bonuses: [{id: b, value: {fixed: 10}}]}} ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ OK1AA ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AB ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AC ¦ 40m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AD ¦ 20m ¦ SSB ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AE ¦ 40m ¦ SSB ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AA ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    S ¦ bonus-per-band ¦ fake ¦ {scoring: {bonuses: [{id: b, value: {fixed: 10}, scope: PER_BAND}]}} ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ OK1AA ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AB ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AC ¦ 40m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AD ¦ 20m ¦ SSB ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AE ¦ 40m ¦ SSB ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AA ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    S ¦ bonus-per-mode ¦ fake ¦ {scoring: {bonuses: [{id: b, value: {fixed: 10}, scope: PER_MODE}]}} ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ OK1AA ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AB ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AC ¦ 40m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AD ¦ 20m ¦ SSB ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AE ¦ 40m ¦ SSB ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AA ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    S ¦ bonus-per-band-mode ¦ fake ¦ {scoring: {bonuses: [{id: b, value: {fixed: 10}, scope: PER_BAND_MODE}]}} ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ OK1AA ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AB ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AC ¦ 40m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AD ¦ 20m ¦ SSB ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AE ¦ 40m ¦ SSB ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AA ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    S ¦ bonus-when-cw ¦ fake ¦ {scoring: {bonuses: [{id: b, when: {mode: CW}, value: {fixed: 10}, scope: PER_BAND}]}} ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ OK1AA ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AB ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AC ¦ 40m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AD ¦ 20m ¦ SSB ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AE ¦ 40m ¦ SSB ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AA ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    S ¦ bonus-two-same-id ¦ fake ¦ {scoring: {bonuses: [{id: b, value: {fixed: 10}}, {id: b, value: {fixed: 1}}]}} ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ OK1AA ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AB ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AC ¦ 40m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AD ¦ 20m ¦ SSB ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AE ¦ 40m ¦ SSB ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AA ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    S ¦ bonus-null-id ¦ fake ¦ {scoring: {bonuses: [{value: {fixed: 10}, scope: PER_BAND}]}} ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ OK1AA ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AB ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AC ¦ 40m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AD ¦ 20m ¦ SSB ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AE ¦ 40m ¦ SSB ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AA ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    S ¦ bonus-no-value ¦ fake ¦ {scoring: {bonuses: [{id: b, scope: ONCE}]}} ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ OK1AA ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AB ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AC ¦ 40m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AD ¦ 20m ¦ SSB ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AE ¦ 40m ¦ SSB ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AA ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    S ¦ bonus-nil-element ¦ fake ¦ {scoring: {bonuses: [~, {id: b, value: {fixed: 10}}]}} ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ OK1AA ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AB ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    S ¦ bonus-int-wrap ¦ fake ¦ {scoring: {bonuses: [{id: b, value: {fixed: 2147483647}, scope: PER_BAND_MODE}]}} ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ OK1AA ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AB ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AC ¦ 40m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AD ¦ 20m ¦ SSB ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AE ¦ 40m ¦ SSB ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AA ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    S ¦ bonus-expr-first-wins ¦ fake ¦ {scoring: {bonuses: [{id: b, value: {expr: "qsoCount + 7"}, scope: PER_BAND}, {id: z, when: {mode: SSB}, value: {fixed: 0}, scope: ONCE}, {id: z, value: {fixed: 5}, scope: ONCE}]}} ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ OK1AA ¦ 20m ¦ SSB ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AB ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AC ¦ 40m ¦ CW ¦ {} ¦ 0 ¦ ~
    S ¦ bonus-dupe-worth ¦ fake ¦ {scoring: {qsoPoints: {default: 3}, bonuses: [{id: b, value: {fixed: 10}, scope: PER_BAND}], total: "qsoPoints + bonusPoints"}, dupe: {scope: ONCE, dupeWorthZero: false}} ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ OK1AA ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AA ¦ 40m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ OK1AB ¦ 40m ¦ CW ¦ {} ¦ 0 ¦ ~
    S ¦ partial-bonus-expr ¦ test ¦ {id: t, modes: [CW], bands: [20m, 40m], exchange: {received: [{id: rst, type: RST}]}, multipliers: [{id: c, set: dxcc_entities, from: callsign, scope: PER_BAND}], scoring: {qsoPoints: {default: 1}, bonuses: [{id: a, value: {fixed: 7}}, {id: b, when: {expr: "1 +"}, value: {fixed: 5}}], total: "qsoPoints * multTotal + bonusPoints"}} ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ DL1ABC ¦ 20m ¦ CW ¦ rst=599 ¦ 0 ¦ ~
    P ¦ DL1ABC ¦ 20m ¦ CW ¦ rst=599 ¦ ~
    L ¦ DL1ABC ¦ 20m ¦ CW ¦ rst=599 ¦ 0 ¦ ~
    S ¦ partial-bonus-value ¦ test ¦ {id: t, modes: [CW], scoring: {qsoPoints: {default: 1}, bonuses: [{id: v, value: {expr: "2 *"}, scope: PER_BAND}], total: "qsoPoints + bonusPoints"}} ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ DL1ABC ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ DL2ABC ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    S ¦ partial-points ¦ test ¦ {id: t, modes: [CW], multipliers: [{id: c, set: dxcc_entities, from: callsign, scope: PER_BAND}], scoring: {qsoPoints: {rules: [{value: {expr: "max("}}]}, total: "qsoPoints"}} ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ DL1ABC ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    P ¦ DL1ABC ¦ 20m ¦ CW ¦ {} ¦ ~
    S ¦ partial-unknown-set ¦ test ¦ {id: t, modes: [CW], multipliers: [{id: c, set: dxcc_entities, from: callsign}, {id: x, set: nope, from: callsign}], scoring: {qsoPoints: {default: 1}, total: "qsoPoints * multTotal"}} ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ DL1ABC ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    G ¦ all ¦ 20m;40m
    S ¦ exchange-overflow ¦ test ¦ @cq-ww-cw.yaml ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ DL1ABC ¦ 20m ¦ CW ¦ rst=599;zone=2147483648 ¦ 0 ¦ ~
    E ¦ DL1ABC ¦ rst=599;zone=2147483648
    E ¦ DL1ABC ¦ rst=599;zone=14
    E ¦ DL1ABC ¦ rst=599
    E ¦ DL1ABC ¦ ~
    L ¦ DL1ABC ¦ 20m ¦ CW ¦ rst=599;zone=14 ¦ 0 ¦ ~
    S ¦ cq-ww-cw ¦ test ¦ @cq-ww-cw.yaml ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ DL1ABC ¦ 20m ¦ CW ¦ zone=14 ¦ now ¦ ~
    L ¦ W1AW ¦ 20m ¦ CW ¦ zone=5 ¦ now ¦ ~
    L ¦ DL2XYZ ¦ 20m ¦ CW ¦ zone=14 ¦ now ¦ ~
    L ¦ DL2XYZ ¦ 20m ¦ CW ¦ zone=14 ¦ now ¦ ~
    P ¦ DL2XYZ ¦ 20m ¦ CW ¦ zone=14 ¦ ~
    P ¦ VE3ABC ¦ 40m ¦ CW ¦ zone=4 ¦ ~
    L ¦ VE3ABC ¦ 20m ¦ FT8 ¦ rst=599;zone=4 ¦ 0 ¦ ~
    L ¦ VE3ABC ¦ 20m ¦ CW ¦ rst=599;zone=4 ¦ 0 ¦ ~
    L ¦ VE3XYZ ¦ \u{0020}\u{0020} ¦ CW ¦ zone=4 ¦ 0 ¦ ~
    L ¦ VE3XYZ ¦ ~ ¦ CW ¦ zone=4 ¦ 0 ¦ ~
    L ¦ VE3XYZ ¦ \u{00A0} ¦ CW ¦ zone=4 ¦ 0 ¦ ~
    L ¦ VE3XYZ ¦ 15m ¦  ¦ zone=4 ¦ 0 ¦ ~
    L ¦ VE3XYZ ¦ 10m ¦ ~ ¦ zone=4 ¦ 0 ¦ ~
    L ¦ VE3XYZ ¦ 10m ¦ cw ¦ zone=4 ¦ 0 ¦ ~
    L ¦ ~ ¦ 10m ¦ CW ¦ zone=4 ¦ 0 ¦ ~
    L ¦ QQ9QQ ¦ 10m ¦ CW ¦ zone=99 ¦ ~ ¦ ~
    G ¦ dxcc ¦ 160m;80m;40m;20m;15m;10m
    G ¦ set:cq_zones ¦ 160m;80m;40m;20m;15m;10m
    G ¦ none ¦ 20m
    G ¦ binding:countries ¦ 20m;20m;40m
    A ¦ DL1ABC
    A ¦ ~
    F ¦ DL1ABC ¦ 599 14 ¦ ~
    F ¦ DL1ABC ¦ \u{0020}\u{0020}599\u{0020}\u{0020}\u{0020}14\u{0020}\u{0020}extra\u{0020} ¦ ~
    F ¦ DL1ABC ¦ 599\u{0009}14 ¦ ~
    F ¦ DL1ABC ¦ 599\u{00A0}14 ¦ ~
    F ¦ DL1ABC ¦ 599 ¦ 7
    F ¦ DL1ABC ¦ ~ ¦ 7
    F ¦ DL1ABC ¦ 599 14 ¦ 3
    F ¦ DL1ABC ¦ \u{0001}599 ¦ ~
    R ¦ OK2ABC ¦ 80m ¦ CW ¦ 599 15 ¦ ~ ¦ 0 ¦ ~
    R ¦ OK2ABC ¦ 80m ¦ CW ¦ 599 15 ¦ ~ ¦ ~ ¦ ~
    O ¦ 599 DAD
    M ¦ dxcc_entities
    M ¦ cq_zones
    M ¦ ~
    M ¦ nope
    Q ¦ 5
    K ¦ w1aw/m
    K ¦ OK/DL1ABC/P
    K ¦ K1ABC/ESX
    K ¦ VP2E/K7ABC
    K ¦ AB1/CD2
    K ¦ /
    K ¦
    K ¦ \u{0020}\u{0020}
    K ¦ ABC
    K ¦ W1AW//
    K ¦ ABC/DEF
    K ¦ OK1\u{0661}ABC
    K ¦ W1\u{000A}AW/P
    K ¦ W1\u{0085}AW/K2\u{2028}A/DL1
    K ¦ ~
    S ¦ cq-wpx-cw ¦ test ¦ @cq-wpx-cw.yaml ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ W1AW ¦ 20m ¦ CW ¦ nr=1 ¦ now ¦ ~
    L ¦ DL1ABC ¦ 20m ¦ CW ¦ nr=2 ¦ now ¦ ~
    L ¦ W1AW ¦ 40m ¦ CW ¦ nr=3 ¦ now ¦ ~
    F ¦ W1AW ¦ 599 12 ¦ 99
    R ¦ K1ABC ¦ 15m ¦ CW ¦ 599 ¦ 2147483647 ¦ 0 ¦ ~
    R ¦ K1ABD ¦ 15m ¦ CW ¦ 599 ¦ -5 ¦ 0 ¦ ~
    G ¦ all ¦ 160m;80m;40m;20m;15m;10m
    S ¦ iaru-hf ¦ test ¦ @iaru-hf.yaml ¦ OK1XOE ¦ ~ ¦ 28
    L ¦ DL1ABC ¦ 20m ¦ CW ¦ exch=28 ¦ now ¦ ~
    L ¦ DL2XYZ ¦ 20m ¦ CW ¦ exch=14 ¦ now ¦ ~
    L ¦ W1AW ¦ 20m ¦ CW ¦ exch=8 ¦ now ¦ ~
    L ¦ DA0HQ ¦ 20m ¦ CW ¦ exch=DARC ¦ now ¦ ~
    P ¦ TM0HQ ¦ 20m ¦ CW ¦ exch=REF ¦ ~
    P ¦ OK2XYZ ¦ 20m ¦ CW ¦ exch=28 ¦ ~
    L ¦ DL1ABC ¦ 20m ¦ SSB ¦ exch=28 ¦ now ¦ ~
    L ¦ DL1ABC ¦ 20m ¦ SSB ¦ exch=28 ¦ now ¦ ~
    L ¦ DA0HQ ¦ 40m ¦ CW ¦ exch=darc ¦ now ¦ ~
    M ¦ iaru_hq
    G ¦ binding:hq ¦ 40m;20m
    S ¦ iaru-hf-default-zone ¦ test ¦ @iaru-hf.yaml ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ OK1ABC ¦ 20m ¦ CW ¦ exch=28 ¦ 0 ¦ ~
    L ¦ DL1ABC ¦ 20m ¦ CW ¦ exch=28 ¦ 0 ¦ ~
    S ¦ qso-party ¦ test ¦ {schemaVersion: 1, id: test-qp, metadata: {name: "Test QSO Party"}, bands: [80m, 40m, 20m], modes: [CW, SSB], exchange: {sent: [{id: rst, type: RST, source: AUTO_RST}, {id: qth, type: TEXT, source: ROVER_QTH}], received: [{id: rst, type: RST, required: true}, {id: cnty, type: TEXT, required: true}]}, scoring: {qsoPoints: {mode: FIRST_MATCH, default: 1}, bonuses: [{id: bonus, when: {bonusStation: true}, value: {fixed: 100}, scope: PER_BAND_MODE}], total: "qsoPoints + bonusPoints"}, dupe: {scope: PER_BAND_MODE}, cabrillo: {contestName: TEST-QP, sentOrder: [rst, qth], receivedOrder: [rst, cnty]}} ¦ W1AW ¦ ~ ¦ ~
    L ¦ K1ABC ¦ 20m ¦ CW ¦ rst=599;cnty=ESX ¦ 1795867500 ¦ ~
    L ¦ K1ABC ¦ 20m ¦ CW ¦ rst=599;cnty=ESX ¦ 1795871100 ¦ ~
    T ¦ 1200/30
    L ¦ K1ABC ¦ 20m ¦ CW ¦ rst=599;cnty=ESX ¦ 1795867500 ¦ ~
    L ¦ K1ABC ¦ 20m ¦ CW ¦ rst=599;cnty=ESX ¦ 1795868100 ¦ ~
    L ¦ K1ABC ¦ 20m ¦ CW ¦ rst=599;cnty=ESX ¦ 1795869300 ¦ ~
    L ¦ K1ABC ¦ 20m ¦ CW ¦ rst=599;cnty=ESX ¦ ~ ¦ ~
    L ¦ K1ABC ¦ 20m ¦ CW ¦ rst=599;cnty=ESX ¦ ~ ¦ ~
    L ¦ K2ABC ¦ 40m ¦ CW ¦ rst=599;cnty=ESX ¦ 0 ¦ ~
    P ¦ K2ABC ¦ 40m ¦ CW ¦ rst=599;cnty=ESX ¦ ~
    T ¦ ~
    L ¦ K1ABC ¦ 20m ¦ CW ¦ rst=599;cnty=ESX ¦ 1795869300 ¦ ~
    L ¦ K3ABC ¦ 20m ¦ CW ¦ rst=599;cnty=ESX ¦ 1795867500 ¦ HAM
    L ¦ K3ABC ¦ 20m ¦ CW ¦ rst=599;cnty=ESX ¦ 1795867560 ¦ \u{0020}ham\u{0020}
    L ¦ K3ABC ¦ 20m ¦ CW ¦ rst=599;cnty=ESX ¦ 1795867620 ¦ FRA
    L ¦ K3ABC ¦ 20m ¦ CW ¦ rst=599;cnty=ESX ¦ 1795867680 ¦ \u{0020}
    O ¦ 599 DAD
    O ¦ \u{0020}599\u{0020}\u{0020}dad\u{0020}
    O ¦ 599\u{0009}DAD
    O ¦ 599\u{00A0}DAD
    O ¦ 599 -
    O ¦ 599
    O ¦ ~
    O ¦
    O ¦ 599 DAD JEF
    O ¦ \u{0001}
    R ¦ K4ABC ¦ 20m ¦ CW ¦ 599 ESX ¦ ~ ¦ 1795867500 ¦ DAD
    R ¦ K4ABC ¦ 20m ¦ CW ¦ 599 ESX ¦ ~ ¦ 1795867500 ¦ JEF
    E ¦ K4ABC ¦ rst=599;cnty=ESX
    E ¦ K4ABC ¦ rst=599;cnty=
    E ¦ K4ABC ¦ cnty=ESX
    B ¦ k1bon/m;;~;/;OK/DL1ABC/P
    L ¦ K1BON ¦ 20m ¦ CW ¦ rst=599;cnty=ESX ¦ 1795867500 ¦ ~
    L ¦ K1BON/M ¦ 40m ¦ CW ¦ rst=599;cnty=ESX ¦ 1795867560 ¦ ~
    L ¦ K1BON ¦ 20m ¦ CW ¦ rst=599;cnty=ESX ¦ 1795867620 ¦ ~
    L ¦ k1bon ¦ 20m ¦ SSB ¦ rst=59;cnty=ESX ¦ 1795867680 ¦ ~
    L ¦ DL1ABC ¦ 80m ¦ CW ¦ rst=599;cnty=ESX ¦ 1795867740 ¦ ~
    P ¦ OK/DL1ABC ¦ 80m ¦ SSB ¦ rst=59;cnty=ESX ¦ ~
    B ¦ ~
    L ¦ K1BON ¦ 80m ¦ CW ¦ rst=599;cnty=ESX ¦ 1795867800 ¦ ~
    B ¦ -
    S ¦ qso-party-bonus-tour ¦ test ¦ {id: qp2, modes: [CW], scoring: {qsoPoints: {default: 1}, bonuses: [{id: bonus, when: {bonusStation: true}, value: {fixed: 100}, scope: ONCE}], total: "qsoPoints + bonusPoints"}, dupe: {scope: PER_BAND}} ¦ W1AW ¦ ~ ¦ ~
    B ¦ K1BON
    T ¦ 0000/60
    L ¦ K1BON ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ K1BON ¦ 20m ¦ CW ¦ {} ¦ 3600 ¦ ~
    L ¦ K1BON ¦ 20m ¦ CW ¦ {} ¦ 3700 ¦ ~
    S ¦ wae-cw ¦ test ¦ @wae-cw.yaml ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ W1AW ¦ 80m ¦ CW ¦ rst=599;nr=1 ¦ now ¦ ~
    L ¦ W1AW ¦ 20m ¦ CW ¦ rst=599;nr=2 ¦ now ¦ ~
    L ¦ DL1ABC ¦ 20m ¦ CW ¦ rst=599;nr=3 ¦ now ¦ ~
    Q ¦ 5
    Q ¦ -3
    Q ¦ 2147483647
    Q ¦ 0
    G ¦ dxcc ¦ 80m;40m;20m
    S ¦ qtc-default-points ¦ test ¦ {id: q, scoring: {qtc: {maxPerStation: 3}, total: "qtcPoints"}} ¦ OK1XOE ¦ ~ ¦ ~
    Q ¦ 7
    S ¦ qtc-max ¦ test ¦ {id: q, scoring: {qtc: {points: 2147483647}, total: "qtcPoints"}} ¦ OK1XOE ¦ ~ ¦ ~
    Q ¦ 2147483647
    S ¦ qtc-none ¦ test ¦ {id: q, scoring: {total: "qtcPoints"}} ¦ OK1XOE ¦ ~ ¦ ~
    Q ¦ 7
    S ¦ dx ¦ test ¦ @dx.yaml ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ DL1ABC ¦ 20m ¦ CW ¦ rst=599 ¦ now ¦ ~
    L ¦ W1AW ¦ 40m ¦ SSB ¦ rst=59 ¦ now ¦ ~
    L ¦ OK2XYZ ¦ 17m ¦ RTTY ¦ rst=599 ¦ now ¦ ~
    L ¦ DL1ABC ¦ 20m ¦ CW ¦ rst=599 ¦ now ¦ ~
    L ¦ DL1ABC ¦ 20m ¦ SSB ¦ rst=59 ¦ now ¦ ~
    L ¦ DL1ABC ¦ 20m ¦ SSB ¦ rst=59 ¦ now ¦ ~
    G ¦ all ¦ 20m
    S ¦ long-qso-points ¦ test ¦ {id: b, scoring: {qsoPoints: {default: 2147483647}, total: "qsoPoints"}} ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ DL1ABC ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ DL2ABC ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ DL3ABC ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    S ¦ ww-digi ¦ test ¦ @ww-digi.yaml ¦ OK1XOE ¦ JN79 ¦ ~
    L ¦ DL1ABC ¦ 20m ¦ DIGITAL ¦ grid=JO60 ¦ now ¦ ~
    L ¦ W1AW ¦ 40m ¦ DIGITAL ¦ grid=FN31 ¦ now ¦ ~
    G ¦ set:grid_fields ¦ 160m;80m;40m;20m;15m;10m
    S ¦ grid-modes-empty ¦ test ¦ {id: g, modes: [], multipliers: [{id: c, set: dxcc_entities, from: callsign, scope: PER_BAND_MODE}], scoring: {qsoPoints: {default: 1}, total: "qsoPoints * multTotal"}} ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ DL1ABC ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ W1AW ¦ 20m ¦ SSB ¦ {} ¦ 0 ¦ ~
    G ¦ all ¦ 20m;40m
    S ¦ grid-modes-null ¦ test ¦ {id: g, modes: [~], multipliers: [{id: c, set: dxcc_entities, from: callsign, scope: PER_BAND_MODE}], scoring: {qsoPoints: {default: 1}, total: "qsoPoints * multTotal"}} ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ DL1ABC ¦ 20m ¦ ~ ¦ {} ¦ 0 ¦ ~
    G ¦ all ¦ 20m;40m
    S ¦ grid-no-multipliers ¦ test ¦ {id: g} ¦ OK1XOE ¦ ~ ¦ ~
    G ¦ all ¦ 20m
    S ¦ grid-once ¦ test ¦ {id: g, multipliers: [{id: p, set: wpx_prefixes, from: callsign, scope: ONCE}]} ¦ OK1XOE ¦ ~ ¦ ~
    L ¦ DL1ABC ¦ 20m ¦ CW ¦ {} ¦ 0 ¦ ~
    L ¦ W1AW ¦ 40m ¦ CW ¦ {} ¦ 0 ¦ ~
    G ¦ all ¦ 160m;80m;40m;20m;15m;10m
    """#

    /// Probe output: scenario name TAB step order TAB result TAB score.
    static let expected = #"""
    bonus-once	0	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=1 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=10 qtcCount=0
    bonus-once	1	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=2 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=10 qtcCount=0
    bonus-once	2	counted=true pts=0 dupe=false band=40m bonusStation=false qth=~ mults=[]	qsoCount=3 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=10 qtcCount=0
    bonus-once	3	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=4 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=10 qtcCount=0
    bonus-once	4	counted=true pts=0 dupe=false band=40m bonusStation=false qth=~ mults=[]	qsoCount=5 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=10 qtcCount=0
    bonus-once	5	counted=true pts=0 dupe=true band=20m bonusStation=false qth=~ mults=[]	qsoCount=6 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=10 qtcCount=0
    bonus-no-scope	0	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=1 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=0 qtcCount=0
    bonus-no-scope	1	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=2 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=0 qtcCount=0
    bonus-no-scope	2	counted=true pts=0 dupe=false band=40m bonusStation=false qth=~ mults=[]	qsoCount=3 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=0 qtcCount=0
    bonus-no-scope	3	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=4 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=0 qtcCount=0
    bonus-no-scope	4	counted=true pts=0 dupe=false band=40m bonusStation=false qth=~ mults=[]	qsoCount=5 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=0 qtcCount=0
    bonus-no-scope	5	counted=true pts=0 dupe=true band=20m bonusStation=false qth=~ mults=[]	qsoCount=6 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=0 qtcCount=0
    bonus-per-band	0	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=1 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=0 qtcCount=0
    bonus-per-band	1	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=2 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=0 qtcCount=0
    bonus-per-band	2	counted=true pts=0 dupe=false band=40m bonusStation=false qth=~ mults=[]	qsoCount=3 qsoPoints=0 mult=0 groups=[] bonus=20 qtc=0 total=0 qtcCount=0
    bonus-per-band	3	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=4 qsoPoints=0 mult=0 groups=[] bonus=20 qtc=0 total=0 qtcCount=0
    bonus-per-band	4	counted=true pts=0 dupe=false band=40m bonusStation=false qth=~ mults=[]	qsoCount=5 qsoPoints=0 mult=0 groups=[] bonus=20 qtc=0 total=0 qtcCount=0
    bonus-per-band	5	counted=true pts=0 dupe=true band=20m bonusStation=false qth=~ mults=[]	qsoCount=6 qsoPoints=0 mult=0 groups=[] bonus=20 qtc=0 total=0 qtcCount=0
    bonus-per-mode	0	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=1 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=0 qtcCount=0
    bonus-per-mode	1	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=2 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=0 qtcCount=0
    bonus-per-mode	2	counted=true pts=0 dupe=false band=40m bonusStation=false qth=~ mults=[]	qsoCount=3 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=0 qtcCount=0
    bonus-per-mode	3	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=4 qsoPoints=0 mult=0 groups=[] bonus=20 qtc=0 total=0 qtcCount=0
    bonus-per-mode	4	counted=true pts=0 dupe=false band=40m bonusStation=false qth=~ mults=[]	qsoCount=5 qsoPoints=0 mult=0 groups=[] bonus=20 qtc=0 total=0 qtcCount=0
    bonus-per-mode	5	counted=true pts=0 dupe=true band=20m bonusStation=false qth=~ mults=[]	qsoCount=6 qsoPoints=0 mult=0 groups=[] bonus=20 qtc=0 total=0 qtcCount=0
    bonus-per-band-mode	0	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=1 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=0 qtcCount=0
    bonus-per-band-mode	1	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=2 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=0 qtcCount=0
    bonus-per-band-mode	2	counted=true pts=0 dupe=false band=40m bonusStation=false qth=~ mults=[]	qsoCount=3 qsoPoints=0 mult=0 groups=[] bonus=20 qtc=0 total=0 qtcCount=0
    bonus-per-band-mode	3	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=4 qsoPoints=0 mult=0 groups=[] bonus=30 qtc=0 total=0 qtcCount=0
    bonus-per-band-mode	4	counted=true pts=0 dupe=false band=40m bonusStation=false qth=~ mults=[]	qsoCount=5 qsoPoints=0 mult=0 groups=[] bonus=40 qtc=0 total=0 qtcCount=0
    bonus-per-band-mode	5	counted=true pts=0 dupe=true band=20m bonusStation=false qth=~ mults=[]	qsoCount=6 qsoPoints=0 mult=0 groups=[] bonus=40 qtc=0 total=0 qtcCount=0
    bonus-when-cw	0	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=1 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=0 qtcCount=0
    bonus-when-cw	1	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=2 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=0 qtcCount=0
    bonus-when-cw	2	counted=true pts=0 dupe=false band=40m bonusStation=false qth=~ mults=[]	qsoCount=3 qsoPoints=0 mult=0 groups=[] bonus=20 qtc=0 total=0 qtcCount=0
    bonus-when-cw	3	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=4 qsoPoints=0 mult=0 groups=[] bonus=20 qtc=0 total=0 qtcCount=0
    bonus-when-cw	4	counted=true pts=0 dupe=false band=40m bonusStation=false qth=~ mults=[]	qsoCount=5 qsoPoints=0 mult=0 groups=[] bonus=20 qtc=0 total=0 qtcCount=0
    bonus-when-cw	5	counted=true pts=0 dupe=true band=20m bonusStation=false qth=~ mults=[]	qsoCount=6 qsoPoints=0 mult=0 groups=[] bonus=20 qtc=0 total=0 qtcCount=0
    bonus-two-same-id	0	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=1 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=0 qtcCount=0
    bonus-two-same-id	1	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=2 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=0 qtcCount=0
    bonus-two-same-id	2	counted=true pts=0 dupe=false band=40m bonusStation=false qth=~ mults=[]	qsoCount=3 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=0 qtcCount=0
    bonus-two-same-id	3	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=4 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=0 qtcCount=0
    bonus-two-same-id	4	counted=true pts=0 dupe=false band=40m bonusStation=false qth=~ mults=[]	qsoCount=5 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=0 qtcCount=0
    bonus-two-same-id	5	counted=true pts=0 dupe=true band=20m bonusStation=false qth=~ mults=[]	qsoCount=6 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=0 qtcCount=0
    bonus-null-id	0	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=1 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=0 qtcCount=0
    bonus-null-id	1	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=2 qsoPoints=0 mult=0 groups=[] bonus=10 qtc=0 total=0 qtcCount=0
    bonus-null-id	2	counted=true pts=0 dupe=false band=40m bonusStation=false qth=~ mults=[]	qsoCount=3 qsoPoints=0 mult=0 groups=[] bonus=20 qtc=0 total=0 qtcCount=0
    bonus-null-id	3	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=4 qsoPoints=0 mult=0 groups=[] bonus=20 qtc=0 total=0 qtcCount=0
    bonus-null-id	4	counted=true pts=0 dupe=false band=40m bonusStation=false qth=~ mults=[]	qsoCount=5 qsoPoints=0 mult=0 groups=[] bonus=20 qtc=0 total=0 qtcCount=0
    bonus-null-id	5	counted=true pts=0 dupe=true band=20m bonusStation=false qth=~ mults=[]	qsoCount=6 qsoPoints=0 mult=0 groups=[] bonus=20 qtc=0 total=0 qtcCount=0
    bonus-no-value	0	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=1 qsoPoints=0 mult=0 groups=[] bonus=0 qtc=0 total=0 qtcCount=0
    bonus-no-value	1	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=2 qsoPoints=0 mult=0 groups=[] bonus=0 qtc=0 total=0 qtcCount=0
    bonus-no-value	2	counted=true pts=0 dupe=false band=40m bonusStation=false qth=~ mults=[]	qsoCount=3 qsoPoints=0 mult=0 groups=[] bonus=0 qtc=0 total=0 qtcCount=0
    bonus-no-value	3	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=4 qsoPoints=0 mult=0 groups=[] bonus=0 qtc=0 total=0 qtcCount=0
    bonus-no-value	4	counted=true pts=0 dupe=false band=40m bonusStation=false qth=~ mults=[]	qsoCount=5 qsoPoints=0 mult=0 groups=[] bonus=0 qtc=0 total=0 qtcCount=0
    bonus-no-value	5	counted=true pts=0 dupe=true band=20m bonusStation=false qth=~ mults=[]	qsoCount=6 qsoPoints=0 mult=0 groups=[] bonus=0 qtc=0 total=0 qtcCount=0
    bonus-nil-element	0	EXC NullPointerException: Cannot\u0020invoke\u0020"cz.ok1xoe.maccontestlogger.contest.def.ContestDefinition$Bonus.when()"\u0020because\u0020"b"\u0020is\u0020null	qsoCount=0 qsoPoints=0 mult=0 groups=[] bonus=0 qtc=0 total=0 qtcCount=0
    bonus-nil-element	1	EXC NullPointerException: Cannot\u0020invoke\u0020"cz.ok1xoe.maccontestlogger.contest.def.ContestDefinition$Bonus.when()"\u0020because\u0020"b"\u0020is\u0020null	qsoCount=0 qsoPoints=0 mult=0 groups=[] bonus=0 qtc=0 total=0 qtcCount=0
    bonus-int-wrap	0	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=1 qsoPoints=0 mult=0 groups=[] bonus=2147483647 qtc=0 total=0 qtcCount=0
    bonus-int-wrap	1	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=2 qsoPoints=0 mult=0 groups=[] bonus=2147483647 qtc=0 total=0 qtcCount=0
    bonus-int-wrap	2	counted=true pts=0 dupe=false band=40m bonusStation=false qth=~ mults=[]	qsoCount=3 qsoPoints=0 mult=0 groups=[] bonus=4294967294 qtc=0 total=0 qtcCount=0
    bonus-int-wrap	3	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=4 qsoPoints=0 mult=0 groups=[] bonus=6442450941 qtc=0 total=0 qtcCount=0
    bonus-int-wrap	4	counted=true pts=0 dupe=false band=40m bonusStation=false qth=~ mults=[]	qsoCount=5 qsoPoints=0 mult=0 groups=[] bonus=8589934588 qtc=0 total=0 qtcCount=0
    bonus-int-wrap	5	counted=true pts=0 dupe=true band=20m bonusStation=false qth=~ mults=[]	qsoCount=6 qsoPoints=0 mult=0 groups=[] bonus=8589934588 qtc=0 total=0 qtcCount=0
    bonus-expr-first-wins	0	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=1 qsoPoints=0 mult=0 groups=[] bonus=7 qtc=0 total=0 qtcCount=0
    bonus-expr-first-wins	1	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=2 qsoPoints=0 mult=0 groups=[] bonus=7 qtc=0 total=0 qtcCount=0
    bonus-expr-first-wins	2	counted=true pts=0 dupe=false band=40m bonusStation=false qth=~ mults=[]	qsoCount=3 qsoPoints=0 mult=0 groups=[] bonus=14 qtc=0 total=0 qtcCount=0
    bonus-dupe-worth	0	counted=true pts=3 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=1 qsoPoints=3 mult=0 groups=[] bonus=10 qtc=0 total=13 qtcCount=0
    bonus-dupe-worth	1	counted=true pts=3 dupe=true band=40m bonusStation=false qth=~ mults=[]	qsoCount=2 qsoPoints=6 mult=0 groups=[] bonus=10 qtc=0 total=16 qtcCount=0
    bonus-dupe-worth	2	counted=true pts=3 dupe=false band=40m bonusStation=false qth=~ mults=[]	qsoCount=3 qsoPoints=9 mult=0 groups=[] bonus=20 qtc=0 total=29 qtcCount=0
    partial-bonus-expr	0	EXC IllegalArgumentException: Neo\u010Dek\u00E1van\u00FD\u0020konec\u0020v\u00FDrazu:\u00201\u0020+	qsoCount=0 qsoPoints=0 mult=1 groups=[c=1] bonus=7 qtc=0 total=7 qtcCount=0
    partial-bonus-expr	1	counted=true pts=1 dupe=false band=20m bonusStation=false qth=~ mults=[c,dxcc_entities,230,20m,KNOWN_ALREADY_WORKED,true,false]	qsoCount=0 qsoPoints=0 mult=1 groups=[c=1] bonus=7 qtc=0 total=7 qtcCount=0
    partial-bonus-expr	2	EXC IllegalArgumentException: Neo\u010Dek\u00E1van\u00FD\u0020konec\u0020v\u00FDrazu:\u00201\u0020+	qsoCount=0 qsoPoints=0 mult=1 groups=[c=1] bonus=7 qtc=0 total=7 qtcCount=0
    partial-bonus-value	0	EXC IllegalArgumentException: Neo\u010Dek\u00E1van\u00FD\u0020konec\u0020v\u00FDrazu:\u00202\u0020*	qsoCount=0 qsoPoints=0 mult=0 groups=[] bonus=0 qtc=0 total=0 qtcCount=0
    partial-bonus-value	1	counted=true pts=1 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=1 qsoPoints=1 mult=0 groups=[] bonus=0 qtc=0 total=1 qtcCount=0
    partial-points	0	EXC IllegalArgumentException: Neo\u010Dek\u00E1van\u00FD\u0020konec\u0020v\u00FDrazu:\u0020max(	qsoCount=0 qsoPoints=0 mult=0 groups=[c=0] bonus=0 qtc=0 total=0 qtcCount=0
    partial-points	1	EXC IllegalArgumentException: Neo\u010Dek\u00E1van\u00FD\u0020konec\u0020v\u00FDrazu:\u0020max(	qsoCount=0 qsoPoints=0 mult=0 groups=[c=0] bonus=0 qtc=0 total=0 qtcCount=0
    partial-unknown-set	0	EXC MultiplierException: multiplik\u00E1torov\u00E1\u0020sada\u0020'nope'\u0020nen\u00ED\u0020v\u0020registru	qsoCount=0 qsoPoints=0 mult=1 groups=[c=1,x=0] bonus=0 qtc=0 total=0 qtcCount=0
    partial-unknown-set	1	available=true worked=1 possible=4 rows=4 [503,Czech\u0020Republic,OK,EU,;291,United\u0020States,K,NA,;1,Canada,VE,NA,;230,Germany,DL,EU,20m+40m]	qsoCount=0 qsoPoints=0 mult=1 groups=[c=1,x=0] bonus=0 qtc=0 total=0 qtcCount=0
    exchange-overflow	0	EXC NumberFormatException: For\u0020input\u0020string:\u0020"2147483648"	qsoCount=0 qsoPoints=0 mult=0 groups=[zones=0,countries=0] bonus=0 qtc=0 total=0 qtcCount=0
    exchange-overflow	1	EXC NumberFormatException: For\u0020input\u0020string:\u0020"2147483648"	qsoCount=0 qsoPoints=0 mult=0 groups=[zones=0,countries=0] bonus=0 qtc=0 total=0 qtcCount=0
    exchange-overflow	2	complete=true	qsoCount=0 qsoPoints=0 mult=0 groups=[zones=0,countries=0] bonus=0 qtc=0 total=0 qtcCount=0
    exchange-overflow	3	complete=false	qsoCount=0 qsoPoints=0 mult=0 groups=[zones=0,countries=0] bonus=0 qtc=0 total=0 qtcCount=0
    exchange-overflow	4	complete=false	qsoCount=0 qsoPoints=0 mult=0 groups=[zones=0,countries=0] bonus=0 qtc=0 total=0 qtcCount=0
    exchange-overflow	5	counted=true pts=1 dupe=false band=20m bonusStation=false qth=~ mults=[zones,cq_zones,14,20m,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,230,20m,KNOWN_NEW_MULTIPLIER,true,true]	qsoCount=1 qsoPoints=1 mult=2 groups=[zones=1,countries=1] bonus=0 qtc=0 total=2 qtcCount=0
    cq-ww-cw	0	counted=true pts=1 dupe=false band=20m bonusStation=false qth=~ mults=[zones,cq_zones,14,20m,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,230,20m,KNOWN_NEW_MULTIPLIER,true,true]	qsoCount=1 qsoPoints=1 mult=2 groups=[zones=1,countries=1] bonus=0 qtc=0 total=2 qtcCount=0
    cq-ww-cw	1	counted=true pts=3 dupe=false band=20m bonusStation=false qth=~ mults=[zones,cq_zones,5,20m,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,291,20m,KNOWN_NEW_MULTIPLIER,true,true]	qsoCount=2 qsoPoints=4 mult=4 groups=[zones=2,countries=2] bonus=0 qtc=0 total=16 qtcCount=0
    cq-ww-cw	2	counted=true pts=1 dupe=false band=20m bonusStation=false qth=~ mults=[zones,cq_zones,14,20m,KNOWN_ALREADY_WORKED,true,false;countries,dxcc_entities,230,20m,KNOWN_ALREADY_WORKED,true,false]	qsoCount=3 qsoPoints=5 mult=4 groups=[zones=2,countries=2] bonus=0 qtc=0 total=20 qtcCount=0
    cq-ww-cw	3	counted=true pts=0 dupe=true band=20m bonusStation=false qth=~ mults=[zones,cq_zones,14,20m,KNOWN_ALREADY_WORKED,true,false;countries,dxcc_entities,230,20m,KNOWN_ALREADY_WORKED,true,false]	qsoCount=4 qsoPoints=5 mult=4 groups=[zones=2,countries=2] bonus=0 qtc=0 total=20 qtcCount=0
    cq-ww-cw	4	counted=true pts=1 dupe=true band=20m bonusStation=false qth=~ mults=[zones,cq_zones,14,20m,KNOWN_ALREADY_WORKED,true,false;countries,dxcc_entities,230,20m,KNOWN_ALREADY_WORKED,true,false]	qsoCount=4 qsoPoints=5 mult=4 groups=[zones=2,countries=2] bonus=0 qtc=0 total=20 qtcCount=0
    cq-ww-cw	5	counted=true pts=3 dupe=false band=40m bonusStation=false qth=~ mults=[zones,cq_zones,4,40m,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,1,40m,KNOWN_NEW_MULTIPLIER,true,true]	qsoCount=4 qsoPoints=5 mult=4 groups=[zones=2,countries=2] bonus=0 qtc=0 total=20 qtcCount=0
    cq-ww-cw	6	counted=false pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=4 qsoPoints=5 mult=4 groups=[zones=2,countries=2] bonus=0 qtc=0 total=20 qtcCount=0
    cq-ww-cw	7	counted=true pts=3 dupe=false band=20m bonusStation=false qth=~ mults=[zones,cq_zones,4,20m,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,1,20m,KNOWN_NEW_MULTIPLIER,true,true]	qsoCount=5 qsoPoints=8 mult=6 groups=[zones=3,countries=3] bonus=0 qtc=0 total=48 qtcCount=0
    cq-ww-cw	8	counted=false pts=0 dupe=false band=\u0020\u0020 bonusStation=false qth=~ mults=[]	qsoCount=5 qsoPoints=8 mult=6 groups=[zones=3,countries=3] bonus=0 qtc=0 total=48 qtcCount=0
    cq-ww-cw	9	counted=false pts=0 dupe=false band=~ bonusStation=false qth=~ mults=[]	qsoCount=5 qsoPoints=8 mult=6 groups=[zones=3,countries=3] bonus=0 qtc=0 total=48 qtcCount=0
    cq-ww-cw	10	counted=true pts=3 dupe=false band=\u00A0 bonusStation=false qth=~ mults=[zones,cq_zones,4,\u00A0,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,1,\u00A0,KNOWN_NEW_MULTIPLIER,true,true]	qsoCount=6 qsoPoints=11 mult=8 groups=[zones=4,countries=4] bonus=0 qtc=0 total=88 qtcCount=0
    cq-ww-cw	11	counted=true pts=3 dupe=false band=15m bonusStation=false qth=~ mults=[zones,cq_zones,4,15m,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,1,15m,KNOWN_NEW_MULTIPLIER,true,true]	qsoCount=7 qsoPoints=14 mult=10 groups=[zones=5,countries=5] bonus=0 qtc=0 total=140 qtcCount=0
    cq-ww-cw	12	counted=true pts=3 dupe=false band=10m bonusStation=false qth=~ mults=[zones,cq_zones,4,10m,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,1,10m,KNOWN_NEW_MULTIPLIER,true,true]	qsoCount=8 qsoPoints=17 mult=12 groups=[zones=6,countries=6] bonus=0 qtc=0 total=204 qtcCount=0
    cq-ww-cw	13	counted=true pts=0 dupe=true band=10m bonusStation=false qth=~ mults=[zones,cq_zones,4,10m,KNOWN_ALREADY_WORKED,true,false;countries,dxcc_entities,1,10m,KNOWN_ALREADY_WORKED,true,false]	qsoCount=9 qsoPoints=17 mult=12 groups=[zones=6,countries=6] bonus=0 qtc=0 total=204 qtcCount=0
    cq-ww-cw	14	counted=true pts=0 dupe=false band=10m bonusStation=false qth=~ mults=[zones,cq_zones,4,10m,KNOWN_ALREADY_WORKED,true,false;countries,dxcc_entities,~,10m,SUSPICIOUS,false,false]	qsoCount=10 qsoPoints=17 mult=12 groups=[zones=6,countries=6] bonus=0 qtc=0 total=204 qtcCount=0
    cq-ww-cw	15	counted=true pts=0 dupe=false band=10m bonusStation=false qth=~ mults=[zones,cq_zones,~,10m,INVALID_FORMAT,false,false;countries,dxcc_entities,~,10m,SUSPICIOUS,false,false]	qsoCount=11 qsoPoints=17 mult=12 groups=[zones=6,countries=6] bonus=0 qtc=0 total=204 qtcCount=0
    cq-ww-cw	16	available=true worked=6 possible=4 rows=4 [503,Czech\u0020Republic,OK,EU,;291,United\u0020States,K,NA,20m;1,Canada,VE,NA,20m+15m+10m;230,Germany,DL,EU,20m]	qsoCount=11 qsoPoints=17 mult=12 groups=[zones=6,countries=6] bonus=0 qtc=0 total=204 qtcCount=0
    cq-ww-cw	17	available=true worked=6 possible=40 rows=40 [1,1,,,;2,2,,,;3,3,,,;4,4,,,20m+15m+10m;5,5,,,20m;14,14,,,20m]	qsoCount=11 qsoPoints=17 mult=12 groups=[zones=6,countries=6] bonus=0 qtc=0 total=204 qtcCount=0
    cq-ww-cw	18	available=false worked=0 possible=0 rows=0 []	qsoCount=11 qsoPoints=17 mult=12 groups=[zones=6,countries=6] bonus=0 qtc=0 total=204 qtcCount=0
    cq-ww-cw	19	available=true worked=6 possible=4 rows=4 [503,Czech\u0020Republic,OK,EU,;291,United\u0020States,K,NA,20m;1,Canada,VE,NA,20m;230,Germany,DL,EU,20m]	qsoCount=11 qsoPoints=17 mult=12 groups=[zones=6,countries=6] bonus=0 qtc=0 total=204 qtcCount=0
    cq-ww-cw	20	fields=[rst;zone]	qsoCount=11 qsoPoints=17 mult=12 groups=[zones=6,countries=6] bonus=0 qtc=0 total=204 qtcCount=0
    cq-ww-cw	21	fields=[rst;zone]	qsoCount=11 qsoPoints=17 mult=12 groups=[zones=6,countries=6] bonus=0 qtc=0 total=204 qtcCount=0
    cq-ww-cw	22	received=[rst=599;zone=14]	qsoCount=11 qsoPoints=17 mult=12 groups=[zones=6,countries=6] bonus=0 qtc=0 total=204 qtcCount=0
    cq-ww-cw	23	received=[rst=599;zone=14]	qsoCount=11 qsoPoints=17 mult=12 groups=[zones=6,countries=6] bonus=0 qtc=0 total=204 qtcCount=0
    cq-ww-cw	24	received=[rst=599;zone=14]	qsoCount=11 qsoPoints=17 mult=12 groups=[zones=6,countries=6] bonus=0 qtc=0 total=204 qtcCount=0
    cq-ww-cw	25	received=[rst=599\u00A014]	qsoCount=11 qsoPoints=17 mult=12 groups=[zones=6,countries=6] bonus=0 qtc=0 total=204 qtcCount=0
    cq-ww-cw	26	received=[rst=599;nr=7]	qsoCount=11 qsoPoints=17 mult=12 groups=[zones=6,countries=6] bonus=0 qtc=0 total=204 qtcCount=0
    cq-ww-cw	27	received=[nr=7]	qsoCount=11 qsoPoints=17 mult=12 groups=[zones=6,countries=6] bonus=0 qtc=0 total=204 qtcCount=0
    cq-ww-cw	28	received=[rst=599;zone=14;nr=3]	qsoCount=11 qsoPoints=17 mult=12 groups=[zones=6,countries=6] bonus=0 qtc=0 total=204 qtcCount=0
    cq-ww-cw	29	received=[rst=599]	qsoCount=11 qsoPoints=17 mult=12 groups=[zones=6,countries=6] bonus=0 qtc=0 total=204 qtcCount=0
    cq-ww-cw	30	counted=true pts=0 dupe=false band=80m bonusStation=false qth=~ mults=[zones,cq_zones,15,80m,KNOWN_NEW_MULTIPLIER,true,true;countries,dxcc_entities,503,80m,KNOWN_NEW_MULTIPLIER,true,true]	qsoCount=12 qsoPoints=17 mult=14 groups=[zones=7,countries=7] bonus=0 qtc=0 total=238 qtcCount=0
    cq-ww-cw	31	counted=true pts=0 dupe=true band=80m bonusStation=false qth=~ mults=[zones,cq_zones,15,80m,KNOWN_ALREADY_WORKED,true,false;countries,dxcc_entities,503,80m,KNOWN_ALREADY_WORKED,true,false]	qsoCount=13 qsoPoints=17 mult=14 groups=[zones=7,countries=7] bonus=0 qtc=0 total=238 qtcCount=0
    cq-ww-cw	32	ownQth=~	qsoCount=13 qsoPoints=17 mult=14 groups=[zones=7,countries=7] bonus=0 qtc=0 total=238 qtcCount=0
    cq-ww-cw	33	labels=[1=VE;230=DL;291=K;503=OK]	qsoCount=13 qsoPoints=17 mult=14 groups=[zones=7,countries=7] bonus=0 qtc=0 total=238 qtcCount=0
    cq-ww-cw	34	labels=[]	qsoCount=13 qsoPoints=17 mult=14 groups=[zones=7,countries=7] bonus=0 qtc=0 total=238 qtcCount=0
    cq-ww-cw	35	labels=[]	qsoCount=13 qsoPoints=17 mult=14 groups=[zones=7,countries=7] bonus=0 qtc=0 total=238 qtcCount=0
    cq-ww-cw	36	labels=[]	qsoCount=13 qsoPoints=17 mult=14 groups=[zones=7,countries=7] bonus=0 qtc=0 total=238 qtcCount=0
    cq-ww-cw	37	qtcCount=5	qsoCount=13 qsoPoints=17 mult=14 groups=[zones=7,countries=7] bonus=0 qtc=0 total=238 qtcCount=5
    cq-ww-cw	38	base=W1AW	qsoCount=13 qsoPoints=17 mult=14 groups=[zones=7,countries=7] bonus=0 qtc=0 total=238 qtcCount=5
    cq-ww-cw	39	base=DL1ABC	qsoCount=13 qsoPoints=17 mult=14 groups=[zones=7,countries=7] bonus=0 qtc=0 total=238 qtcCount=5
    cq-ww-cw	40	base=K1ABC	qsoCount=13 qsoPoints=17 mult=14 groups=[zones=7,countries=7] bonus=0 qtc=0 total=238 qtcCount=5
    cq-ww-cw	41	base=K7ABC	qsoCount=13 qsoPoints=17 mult=14 groups=[zones=7,countries=7] bonus=0 qtc=0 total=238 qtcCount=5
    cq-ww-cw	42	base=AB1	qsoCount=13 qsoPoints=17 mult=14 groups=[zones=7,countries=7] bonus=0 qtc=0 total=238 qtcCount=5
    cq-ww-cw	43	base=/	qsoCount=13 qsoPoints=17 mult=14 groups=[zones=7,countries=7] bonus=0 qtc=0 total=238 qtcCount=5
    cq-ww-cw	44	base=	qsoCount=13 qsoPoints=17 mult=14 groups=[zones=7,countries=7] bonus=0 qtc=0 total=238 qtcCount=5
    cq-ww-cw	45	base=	qsoCount=13 qsoPoints=17 mult=14 groups=[zones=7,countries=7] bonus=0 qtc=0 total=238 qtcCount=5
    cq-ww-cw	46	base=ABC	qsoCount=13 qsoPoints=17 mult=14 groups=[zones=7,countries=7] bonus=0 qtc=0 total=238 qtcCount=5
    cq-ww-cw	47	base=W1AW	qsoCount=13 qsoPoints=17 mult=14 groups=[zones=7,countries=7] bonus=0 qtc=0 total=238 qtcCount=5
    cq-ww-cw	48	base=ABC/DEF	qsoCount=13 qsoPoints=17 mult=14 groups=[zones=7,countries=7] bonus=0 qtc=0 total=238 qtcCount=5
    cq-ww-cw	49	base=OK1\u0661ABC	qsoCount=13 qsoPoints=17 mult=14 groups=[zones=7,countries=7] bonus=0 qtc=0 total=238 qtcCount=5
    cq-ww-cw	50	base=W1\u000AAW/P	qsoCount=13 qsoPoints=17 mult=14 groups=[zones=7,countries=7] bonus=0 qtc=0 total=238 qtcCount=5
    cq-ww-cw	51	base=DL1	qsoCount=13 qsoPoints=17 mult=14 groups=[zones=7,countries=7] bonus=0 qtc=0 total=238 qtcCount=5
    cq-ww-cw	52	base=	qsoCount=13 qsoPoints=17 mult=14 groups=[zones=7,countries=7] bonus=0 qtc=0 total=238 qtcCount=5
    cq-wpx-cw	0	counted=true pts=3 dupe=false band=20m bonusStation=false qth=~ mults=[prefixes,wpx_prefixes,W1,*,KNOWN_NEW_MULTIPLIER,true,true]	qsoCount=1 qsoPoints=3 mult=1 groups=[prefixes=1] bonus=0 qtc=0 total=3 qtcCount=0
    cq-wpx-cw	1	counted=true pts=1 dupe=false band=20m bonusStation=false qth=~ mults=[prefixes,wpx_prefixes,DL1,*,KNOWN_NEW_MULTIPLIER,true,true]	qsoCount=2 qsoPoints=4 mult=2 groups=[prefixes=2] bonus=0 qtc=0 total=8 qtcCount=0
    cq-wpx-cw	2	counted=true pts=6 dupe=false band=40m bonusStation=false qth=~ mults=[prefixes,wpx_prefixes,W1,*,KNOWN_ALREADY_WORKED,true,false]	qsoCount=3 qsoPoints=10 mult=2 groups=[prefixes=2] bonus=0 qtc=0 total=20 qtcCount=0
    cq-wpx-cw	3	received=[rst=599;nr=12]	qsoCount=3 qsoPoints=10 mult=2 groups=[prefixes=2] bonus=0 qtc=0 total=20 qtcCount=0
    cq-wpx-cw	4	counted=true pts=3 dupe=false band=15m bonusStation=false qth=~ mults=[prefixes,wpx_prefixes,K1,*,KNOWN_NEW_MULTIPLIER,true,true]	qsoCount=4 qsoPoints=13 mult=3 groups=[prefixes=3] bonus=0 qtc=0 total=39 qtcCount=0
    cq-wpx-cw	5	counted=true pts=3 dupe=false band=15m bonusStation=false qth=~ mults=[prefixes,wpx_prefixes,K1,*,KNOWN_ALREADY_WORKED,true,false]	qsoCount=5 qsoPoints=16 mult=3 groups=[prefixes=3] bonus=0 qtc=0 total=48 qtcCount=0
    cq-wpx-cw	6	available=true worked=3 possible=-1 rows=3 [DL1,DL1,,,160m+80m+40m+20m+15m+10m;K1,K1,,,160m+80m+40m+20m+15m+10m;W1,W1,,,160m+80m+40m+20m+15m+10m]	qsoCount=5 qsoPoints=16 mult=3 groups=[prefixes=3] bonus=0 qtc=0 total=48 qtcCount=0
    iaru-hf	0	counted=true pts=1 dupe=false band=20m bonusStation=false qth=~ mults=[zones,itu_zones,28,20m,KNOWN_NEW_MULTIPLIER,true,true;hq,iaru_hq,~,20m,INVALID_FORMAT,false,false]	qsoCount=1 qsoPoints=1 mult=1 groups=[zones=1,hq=0] bonus=0 qtc=0 total=1 qtcCount=0
    iaru-hf	1	counted=true pts=3 dupe=false band=20m bonusStation=false qth=~ mults=[zones,itu_zones,14,20m,KNOWN_NEW_MULTIPLIER,true,true;hq,iaru_hq,~,20m,INVALID_FORMAT,false,false]	qsoCount=2 qsoPoints=4 mult=2 groups=[zones=2,hq=0] bonus=0 qtc=0 total=8 qtcCount=0
    iaru-hf	2	counted=true pts=5 dupe=false band=20m bonusStation=false qth=~ mults=[zones,itu_zones,8,20m,KNOWN_NEW_MULTIPLIER,true,true;hq,iaru_hq,~,20m,INVALID_FORMAT,false,false]	qsoCount=3 qsoPoints=9 mult=3 groups=[zones=3,hq=0] bonus=0 qtc=0 total=27 qtcCount=0
    iaru-hf	3	counted=true pts=1 dupe=false band=20m bonusStation=false qth=~ mults=[zones,itu_zones,~,20m,INVALID_FORMAT,false,false;hq,iaru_hq,DARC,20m,KNOWN_NEW_MULTIPLIER,true,true]	qsoCount=4 qsoPoints=10 mult=4 groups=[zones=3,hq=1] bonus=0 qtc=0 total=40 qtcCount=0
    iaru-hf	4	counted=true pts=1 dupe=false band=20m bonusStation=false qth=~ mults=[zones,itu_zones,~,20m,INVALID_FORMAT,false,false;hq,iaru_hq,REF,20m,KNOWN_NEW_MULTIPLIER,true,true]	qsoCount=4 qsoPoints=10 mult=4 groups=[zones=3,hq=1] bonus=0 qtc=0 total=40 qtcCount=0
    iaru-hf	5	counted=true pts=1 dupe=false band=20m bonusStation=false qth=~ mults=[zones,itu_zones,28,20m,KNOWN_ALREADY_WORKED,true,false;hq,iaru_hq,~,20m,INVALID_FORMAT,false,false]	qsoCount=4 qsoPoints=10 mult=4 groups=[zones=3,hq=1] bonus=0 qtc=0 total=40 qtcCount=0
    iaru-hf	6	counted=true pts=1 dupe=false band=20m bonusStation=false qth=~ mults=[zones,itu_zones,28,20m,KNOWN_ALREADY_WORKED,true,false;hq,iaru_hq,~,20m,INVALID_FORMAT,false,false]	qsoCount=5 qsoPoints=11 mult=4 groups=[zones=3,hq=1] bonus=0 qtc=0 total=44 qtcCount=0
    iaru-hf	7	counted=true pts=0 dupe=true band=20m bonusStation=false qth=~ mults=[zones,itu_zones,28,20m,KNOWN_ALREADY_WORKED,true,false;hq,iaru_hq,~,20m,INVALID_FORMAT,false,false]	qsoCount=6 qsoPoints=11 mult=4 groups=[zones=3,hq=1] bonus=0 qtc=0 total=44 qtcCount=0
    iaru-hf	8	counted=true pts=1 dupe=false band=40m bonusStation=false qth=~ mults=[zones,itu_zones,~,40m,INVALID_FORMAT,false,false;hq,iaru_hq,DARC,40m,KNOWN_NEW_MULTIPLIER,true,true]	qsoCount=7 qsoPoints=12 mult=5 groups=[zones=3,hq=2] bonus=0 qtc=0 total=60 qtcCount=0
    iaru-hf	9	labels=[]	qsoCount=7 qsoPoints=12 mult=5 groups=[zones=3,hq=2] bonus=0 qtc=0 total=60 qtcCount=0
    iaru-hf	10	available=true worked=2 possible=117 rows=117 [AARA,,,,;AARC,,,,;AC,,,,;DARC,,,,40m+20m]	qsoCount=7 qsoPoints=12 mult=5 groups=[zones=3,hq=2] bonus=0 qtc=0 total=60 qtcCount=0
    iaru-hf-default-zone	0	counted=true pts=1 dupe=false band=20m bonusStation=false qth=~ mults=[zones,itu_zones,28,20m,KNOWN_NEW_MULTIPLIER,true,true;hq,iaru_hq,~,20m,INVALID_FORMAT,false,false]	qsoCount=1 qsoPoints=1 mult=1 groups=[zones=1,hq=0] bonus=0 qtc=0 total=1 qtcCount=0
    iaru-hf-default-zone	1	counted=true pts=1 dupe=false band=20m bonusStation=false qth=~ mults=[zones,itu_zones,28,20m,KNOWN_ALREADY_WORKED,true,false;hq,iaru_hq,~,20m,INVALID_FORMAT,false,false]	qsoCount=2 qsoPoints=2 mult=1 groups=[zones=1,hq=0] bonus=0 qtc=0 total=2 qtcCount=0
    qso-party	0	counted=true pts=1 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=1 qsoPoints=1 mult=0 groups=[] bonus=0 qtc=0 total=1 qtcCount=0
    qso-party	1	counted=true pts=0 dupe=true band=20m bonusStation=false qth=~ mults=[]	qsoCount=2 qsoPoints=1 mult=0 groups=[] bonus=0 qtc=0 total=1 qtcCount=0
    qso-party	2	tour=1200/30	qsoCount=2 qsoPoints=1 mult=0 groups=[] bonus=0 qtc=0 total=1 qtcCount=0
    qso-party	3	counted=true pts=1 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=3 qsoPoints=2 mult=0 groups=[] bonus=0 qtc=0 total=2 qtcCount=0
    qso-party	4	counted=true pts=0 dupe=true band=20m bonusStation=false qth=~ mults=[]	qsoCount=4 qsoPoints=2 mult=0 groups=[] bonus=0 qtc=0 total=2 qtcCount=0
    qso-party	5	counted=true pts=1 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=5 qsoPoints=3 mult=0 groups=[] bonus=0 qtc=0 total=3 qtcCount=0
    qso-party	6	counted=true pts=0 dupe=true band=20m bonusStation=false qth=~ mults=[]	qsoCount=6 qsoPoints=3 mult=0 groups=[] bonus=0 qtc=0 total=3 qtcCount=0
    qso-party	7	counted=true pts=0 dupe=true band=20m bonusStation=false qth=~ mults=[]	qsoCount=7 qsoPoints=3 mult=0 groups=[] bonus=0 qtc=0 total=3 qtcCount=0
    qso-party	8	counted=true pts=1 dupe=false band=40m bonusStation=false qth=~ mults=[]	qsoCount=8 qsoPoints=4 mult=0 groups=[] bonus=0 qtc=0 total=4 qtcCount=0
    qso-party	9	counted=true pts=1 dupe=false band=40m bonusStation=false qth=~ mults=[]	qsoCount=8 qsoPoints=4 mult=0 groups=[] bonus=0 qtc=0 total=4 qtcCount=0
    qso-party	10	tour=~	qsoCount=8 qsoPoints=4 mult=0 groups=[] bonus=0 qtc=0 total=4 qtcCount=0
    qso-party	11	counted=true pts=0 dupe=true band=20m bonusStation=false qth=~ mults=[]	qsoCount=9 qsoPoints=4 mult=0 groups=[] bonus=0 qtc=0 total=4 qtcCount=0
    qso-party	12	counted=true pts=1 dupe=false band=20m bonusStation=false qth=HAM mults=[]	qsoCount=10 qsoPoints=5 mult=0 groups=[] bonus=0 qtc=0 total=5 qtcCount=0
    qso-party	13	counted=true pts=0 dupe=true band=20m bonusStation=false qth=HAM mults=[]	qsoCount=11 qsoPoints=5 mult=0 groups=[] bonus=0 qtc=0 total=5 qtcCount=0
    qso-party	14	counted=true pts=1 dupe=false band=20m bonusStation=false qth=FRA mults=[]	qsoCount=12 qsoPoints=6 mult=0 groups=[] bonus=0 qtc=0 total=6 qtcCount=0
    qso-party	15	counted=true pts=1 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=13 qsoPoints=7 mult=0 groups=[] bonus=0 qtc=0 total=7 qtcCount=0
    qso-party	16	ownQth=DAD	qsoCount=13 qsoPoints=7 mult=0 groups=[] bonus=0 qtc=0 total=7 qtcCount=0
    qso-party	17	ownQth=dad	qsoCount=13 qsoPoints=7 mult=0 groups=[] bonus=0 qtc=0 total=7 qtcCount=0
    qso-party	18	ownQth=DAD	qsoCount=13 qsoPoints=7 mult=0 groups=[] bonus=0 qtc=0 total=7 qtcCount=0
    qso-party	19	ownQth=~	qsoCount=13 qsoPoints=7 mult=0 groups=[] bonus=0 qtc=0 total=7 qtcCount=0
    qso-party	20	ownQth=~	qsoCount=13 qsoPoints=7 mult=0 groups=[] bonus=0 qtc=0 total=7 qtcCount=0
    qso-party	21	ownQth=~	qsoCount=13 qsoPoints=7 mult=0 groups=[] bonus=0 qtc=0 total=7 qtcCount=0
    qso-party	22	ownQth=~	qsoCount=13 qsoPoints=7 mult=0 groups=[] bonus=0 qtc=0 total=7 qtcCount=0
    qso-party	23	ownQth=~	qsoCount=13 qsoPoints=7 mult=0 groups=[] bonus=0 qtc=0 total=7 qtcCount=0
    qso-party	24	ownQth=DAD	qsoCount=13 qsoPoints=7 mult=0 groups=[] bonus=0 qtc=0 total=7 qtcCount=0
    qso-party	25	ownQth=~	qsoCount=13 qsoPoints=7 mult=0 groups=[] bonus=0 qtc=0 total=7 qtcCount=0
    qso-party	26	counted=true pts=1 dupe=false band=20m bonusStation=false qth=DAD mults=[]	qsoCount=14 qsoPoints=8 mult=0 groups=[] bonus=0 qtc=0 total=8 qtcCount=0
    qso-party	27	counted=true pts=1 dupe=false band=20m bonusStation=false qth=JEF mults=[]	qsoCount=15 qsoPoints=9 mult=0 groups=[] bonus=0 qtc=0 total=9 qtcCount=0
    qso-party	28	complete=true	qsoCount=15 qsoPoints=9 mult=0 groups=[] bonus=0 qtc=0 total=9 qtcCount=0
    qso-party	29	complete=false	qsoCount=15 qsoPoints=9 mult=0 groups=[] bonus=0 qtc=0 total=9 qtcCount=0
    qso-party	30	complete=false	qsoCount=15 qsoPoints=9 mult=0 groups=[] bonus=0 qtc=0 total=9 qtcCount=0
    qso-party	31	bonus=[/;DL1ABC;K1BON]	qsoCount=15 qsoPoints=9 mult=0 groups=[] bonus=0 qtc=0 total=9 qtcCount=0
    qso-party	32	counted=true pts=1 dupe=false band=20m bonusStation=true qth=~ mults=[]	qsoCount=16 qsoPoints=10 mult=0 groups=[] bonus=100 qtc=0 total=110 qtcCount=0
    qso-party	33	counted=true pts=1 dupe=false band=40m bonusStation=true qth=~ mults=[]	qsoCount=17 qsoPoints=11 mult=0 groups=[] bonus=200 qtc=0 total=211 qtcCount=0
    qso-party	34	counted=true pts=0 dupe=true band=20m bonusStation=true qth=~ mults=[]	qsoCount=18 qsoPoints=11 mult=0 groups=[] bonus=200 qtc=0 total=211 qtcCount=0
    qso-party	35	counted=true pts=1 dupe=false band=20m bonusStation=true qth=~ mults=[]	qsoCount=19 qsoPoints=12 mult=0 groups=[] bonus=300 qtc=0 total=312 qtcCount=0
    qso-party	36	counted=true pts=1 dupe=false band=80m bonusStation=true qth=~ mults=[]	qsoCount=20 qsoPoints=13 mult=0 groups=[] bonus=400 qtc=0 total=413 qtcCount=0
    qso-party	37	counted=true pts=1 dupe=false band=80m bonusStation=true qth=~ mults=[]	qsoCount=20 qsoPoints=13 mult=0 groups=[] bonus=400 qtc=0 total=413 qtcCount=0
    qso-party	38	bonus=[]	qsoCount=20 qsoPoints=13 mult=0 groups=[] bonus=400 qtc=0 total=413 qtcCount=0
    qso-party	39	counted=true pts=1 dupe=false band=80m bonusStation=false qth=~ mults=[]	qsoCount=21 qsoPoints=14 mult=0 groups=[] bonus=400 qtc=0 total=414 qtcCount=0
    qso-party	40	bonus=[]	qsoCount=21 qsoPoints=14 mult=0 groups=[] bonus=400 qtc=0 total=414 qtcCount=0
    qso-party-bonus-tour	0	bonus=[K1BON]	qsoCount=0 qsoPoints=0 mult=0 groups=[] bonus=0 qtc=0 total=0 qtcCount=0
    qso-party-bonus-tour	1	tour=0000/60	qsoCount=0 qsoPoints=0 mult=0 groups=[] bonus=0 qtc=0 total=0 qtcCount=0
    qso-party-bonus-tour	2	counted=true pts=1 dupe=false band=20m bonusStation=true qth=~ mults=[]	qsoCount=1 qsoPoints=1 mult=0 groups=[] bonus=100 qtc=0 total=101 qtcCount=0
    qso-party-bonus-tour	3	counted=true pts=1 dupe=false band=20m bonusStation=true qth=~ mults=[]	qsoCount=2 qsoPoints=2 mult=0 groups=[] bonus=100 qtc=0 total=102 qtcCount=0
    qso-party-bonus-tour	4	counted=true pts=0 dupe=true band=20m bonusStation=true qth=~ mults=[]	qsoCount=3 qsoPoints=2 mult=0 groups=[] bonus=100 qtc=0 total=102 qtcCount=0
    wae-cw	0	counted=true pts=1 dupe=false band=80m bonusStation=false qth=~ mults=[countries,dxcc_entities,291,80m,KNOWN_NEW_MULTIPLIER,true,true]	qsoCount=1 qsoPoints=1 mult=4 groups=[countries=4] bonus=0 qtc=0 total=4 qtcCount=0
    wae-cw	1	counted=true pts=1 dupe=false band=20m bonusStation=false qth=~ mults=[countries,dxcc_entities,291,20m,KNOWN_NEW_MULTIPLIER,true,true]	qsoCount=2 qsoPoints=2 mult=6 groups=[countries=6] bonus=0 qtc=0 total=12 qtcCount=0
    wae-cw	2	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=3 qsoPoints=2 mult=6 groups=[countries=6] bonus=0 qtc=0 total=12 qtcCount=0
    wae-cw	3	qtcCount=5	qsoCount=3 qsoPoints=2 mult=6 groups=[countries=6] bonus=0 qtc=5 total=42 qtcCount=5
    wae-cw	4	qtcCount=0	qsoCount=3 qsoPoints=2 mult=6 groups=[countries=6] bonus=0 qtc=0 total=12 qtcCount=0
    wae-cw	5	qtcCount=2147483647	qsoCount=3 qsoPoints=2 mult=6 groups=[countries=6] bonus=0 qtc=2147483647 total=12884901894 qtcCount=2147483647
    wae-cw	6	qtcCount=0	qsoCount=3 qsoPoints=2 mult=6 groups=[countries=6] bonus=0 qtc=0 total=12 qtcCount=0
    wae-cw	7	available=true worked=2 possible=4 rows=4 [503,Czech\u0020Republic,OK,EU,;291,United\u0020States,K,NA,80m+20m;1,Canada,VE,NA,]	qsoCount=3 qsoPoints=2 mult=6 groups=[countries=6] bonus=0 qtc=0 total=12 qtcCount=0
    qtc-default-points	0	qtcCount=7	qsoCount=0 qsoPoints=0 mult=0 groups=[] bonus=0 qtc=7 total=7 qtcCount=7
    qtc-max	0	qtcCount=2147483647	qsoCount=0 qsoPoints=0 mult=0 groups=[] bonus=0 qtc=4611686014132420609 total=4611686014132420608 qtcCount=2147483647
    qtc-none	0	qtcCount=7	qsoCount=0 qsoPoints=0 mult=0 groups=[] bonus=0 qtc=0 total=0 qtcCount=7
    dx	0	counted=true pts=1 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=1 qsoPoints=1 mult=0 groups=[] bonus=0 qtc=0 total=1 qtcCount=0
    dx	1	counted=true pts=1 dupe=false band=40m bonusStation=false qth=~ mults=[]	qsoCount=2 qsoPoints=2 mult=0 groups=[] bonus=0 qtc=0 total=2 qtcCount=0
    dx	2	counted=true pts=1 dupe=false band=17m bonusStation=false qth=~ mults=[]	qsoCount=3 qsoPoints=3 mult=0 groups=[] bonus=0 qtc=0 total=3 qtcCount=0
    dx	3	counted=true pts=1 dupe=true band=20m bonusStation=false qth=~ mults=[]	qsoCount=4 qsoPoints=4 mult=0 groups=[] bonus=0 qtc=0 total=4 qtcCount=0
    dx	4	counted=true pts=1 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=5 qsoPoints=5 mult=0 groups=[] bonus=0 qtc=0 total=5 qtcCount=0
    dx	5	counted=true pts=1 dupe=true band=20m bonusStation=false qth=~ mults=[]	qsoCount=6 qsoPoints=6 mult=0 groups=[] bonus=0 qtc=0 total=6 qtcCount=0
    dx	6	available=false worked=0 possible=0 rows=0 []	qsoCount=6 qsoPoints=6 mult=0 groups=[] bonus=0 qtc=0 total=6 qtcCount=0
    long-qso-points	0	counted=true pts=2147483647 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=1 qsoPoints=2147483647 mult=0 groups=[] bonus=0 qtc=0 total=2147483647 qtcCount=0
    long-qso-points	1	counted=true pts=2147483647 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=2 qsoPoints=4294967294 mult=0 groups=[] bonus=0 qtc=0 total=4294967294 qtcCount=0
    long-qso-points	2	counted=true pts=2147483647 dupe=false band=20m bonusStation=false qth=~ mults=[]	qsoCount=3 qsoPoints=6442450941 mult=0 groups=[] bonus=0 qtc=0 total=6442450941 qtcCount=0
    ww-digi	0	counted=true pts=1 dupe=false band=20m bonusStation=false qth=~ mults=[grids,grid_fields,JO,20m,UNKNOWN_ACCEPTED,true,true]	qsoCount=1 qsoPoints=1 mult=1 groups=[grids=1] bonus=0 qtc=0 total=1 qtcCount=0
    ww-digi	1	counted=true pts=3 dupe=false band=40m bonusStation=false qth=~ mults=[grids,grid_fields,FN,40m,UNKNOWN_ACCEPTED,true,true]	qsoCount=2 qsoPoints=4 mult=2 groups=[grids=2] bonus=0 qtc=0 total=8 qtcCount=0
    ww-digi	2	available=true worked=2 possible=-1 rows=2 [FN,FN,,,40m;JO,JO,,,20m]	qsoCount=2 qsoPoints=4 mult=2 groups=[grids=2] bonus=0 qtc=0 total=8 qtcCount=0
    grid-modes-empty	0	counted=true pts=1 dupe=false band=20m bonusStation=false qth=~ mults=[c,dxcc_entities,230,20m\u007CCW,KNOWN_NEW_MULTIPLIER,true,true]	qsoCount=1 qsoPoints=1 mult=1 groups=[c=1] bonus=0 qtc=0 total=1 qtcCount=0
    grid-modes-empty	1	counted=true pts=1 dupe=false band=20m bonusStation=false qth=~ mults=[c,dxcc_entities,291,20m\u007CSSB,KNOWN_NEW_MULTIPLIER,true,true]	qsoCount=2 qsoPoints=2 mult=2 groups=[c=2] bonus=0 qtc=0 total=4 qtcCount=0
    grid-modes-empty	2	available=true worked=2 possible=4 rows=4 [503,Czech\u0020Republic,OK,EU,;291,United\u0020States,K,NA,;1,Canada,VE,NA,;230,Germany,DL,EU,20m]	qsoCount=2 qsoPoints=2 mult=2 groups=[c=2] bonus=0 qtc=0 total=4 qtcCount=0
    grid-modes-null	0	counted=true pts=1 dupe=false band=20m bonusStation=false qth=~ mults=[c,dxcc_entities,230,20m\u007Cnull,KNOWN_NEW_MULTIPLIER,true,true]	qsoCount=1 qsoPoints=1 mult=1 groups=[c=1] bonus=0 qtc=0 total=1 qtcCount=0
    grid-modes-null	1	available=true worked=1 possible=4 rows=4 [503,Czech\u0020Republic,OK,EU,;291,United\u0020States,K,NA,;1,Canada,VE,NA,;230,Germany,DL,EU,20m]	qsoCount=1 qsoPoints=1 mult=1 groups=[c=1] bonus=0 qtc=0 total=1 qtcCount=0
    grid-no-multipliers	0	available=false worked=0 possible=0 rows=0 []	qsoCount=0 qsoPoints=0 mult=0 groups=[] bonus=0 qtc=0 total=0 qtcCount=0
    grid-once	0	counted=true pts=0 dupe=false band=20m bonusStation=false qth=~ mults=[p,wpx_prefixes,DL1,*,KNOWN_NEW_MULTIPLIER,true,true]	qsoCount=1 qsoPoints=0 mult=1 groups=[p=1] bonus=0 qtc=0 total=0 qtcCount=0
    grid-once	1	counted=true pts=0 dupe=false band=40m bonusStation=false qth=~ mults=[p,wpx_prefixes,W1,*,KNOWN_NEW_MULTIPLIER,true,true]	qsoCount=2 qsoPoints=0 mult=2 groups=[p=2] bonus=0 qtc=0 total=0 qtcCount=0
    grid-once	2	available=true worked=2 possible=-1 rows=2 [DL1,DL1,,,160m+80m+40m+20m+15m+10m;W1,W1,,,160m+80m+40m+20m+15m+10m]	qsoCount=2 qsoPoints=0 mult=2 groups=[p=2] bonus=0 qtc=0 total=0 qtcCount=0
    """#
}
