// Generated by the maintainer-only probe (JDK 21.0.2, en_US).
// Do not edit by hand — the inputs are built by ExportsFixture.swift.

enum ExportsMeasured {

    static let inputTestLog: [String] = [
        "1795867260000\tW1AW\t14025000\t20m\tCW\t\t\t\t\t\t\t\t\t\ttnx, \"73\"\tRUN\tfalse\tfalse\n",
        "1795867200000\tDL1ABC\t7010000\t40m\tCW\t\t\t\t\t\t\t\t\t\t\tRUN\tfalse\tfalse\n",
        "1795867320000\tG3AB\t14200000\t20m\tSSB\t\t\t\t\t\t\t\t\t\t\tRUN\tfalse\tfalse\n",
    ]

    static let inputEdgeLog: [String] = [
        "1795867320000\tW1AW\t14025050\t20m\tCW\t599\t599\t1\t15\t15\t05\tUnited States\tNA\tOK1XOE\ta,b\tRUN\tfalse\tfalse\n",
        "1795867200000\tOK1\u{017D}\u{00C1}\t7000250\t40m\tSSB\t\t\t\t\t\t\u{011B}\u{0161}\u{010D}\u{0159}\tCzech Republic\tEU\t\u{017D}ofie \u{1F600}\t\"x\"\tSEARCH_AND_POUNCE\ttrue\tfalse\n",
        "\tG3AB\t3500000\t80m\tCW\t\t\t\t\t\t\t\t\t\tline1\r\n",
        "line2\tRUN\tfalse\tfalse\n",
        "1795867320000\tDL1ABC\t0\t\t\t\t\t\t\t\t\tGermany\tEU\t\tcr\ronly\tRUN\tfalse\tfalse\n",
        "1795867260000\tDELETED\t14000000\t20m\tCW\t\t\t\t\t\t\t\t\t\t\tRUN\tfalse\ttrue\n",
        "1795867380000\tSP9XYZ\t14025150\t20m\tFT8\t\t\t\t-7\t\t\tPoland\tEU\t\u{017D}ofie \u{1F600}\t\"\u{0301} 73 \u{1F600}\tRUN\tfalse\tfalse\n",
        "1795867260000\tOK2ABC\t1845000\t160m\tCW\t5nn\t\t\t\t\t\tCzech Republic\tEU\tOK1XOE\t\tRUN\tfalse\tfalse\n",
        "1795910700000\tJA1ABC\t21000000\t15m\tSSB\t\t\t\t\t\t\tJapan\tAS\t  \t\tSEARCH_AND_POUNCE\tfalse\tfalse\n",
    ]

    static let inputEdgeTimedLog: [String] = [
        "1795867320000\tW1AW\t14025050\t20m\tCW\t599\t599\t1\t15\t15\t05\tUnited States\tNA\tOK1XOE\ta,b\tRUN\tfalse\tfalse\n",
        "1795867200000\tOK1\u{017D}\u{00C1}\t7000250\t40m\tSSB\t\t\t\t\t\t\u{011B}\u{0161}\u{010D}\u{0159}\tCzech Republic\tEU\t\u{017D}ofie \u{1F600}\t\"x\"\tSEARCH_AND_POUNCE\ttrue\tfalse\n",
        "1795867320000\tDL1ABC\t0\t\t\t\t\t\t\t\t\tGermany\tEU\t\tcr\ronly\tRUN\tfalse\tfalse\n",
        "1795867260000\tDELETED\t14000000\t20m\tCW\t\t\t\t\t\t\t\t\t\t\tRUN\tfalse\ttrue\n",
        "1795867380000\tSP9XYZ\t14025150\t20m\tFT8\t\t\t\t-7\t\t\tPoland\tEU\t\u{017D}ofie \u{1F600}\t\"\u{0301} 73 \u{1F600}\tRUN\tfalse\tfalse\n",
        "1795867260000\tOK2ABC\t1845000\t160m\tCW\t5nn\t\t\t\t\t\tCzech Republic\tEU\tOK1XOE\t\tRUN\tfalse\tfalse\n",
        "1795910700000\tJA1ABC\t21000000\t15m\tSSB\t\t\t\t\t\t\tJapan\tAS\t  \t\tSEARCH_AND_POUNCE\tfalse\tfalse\n",
    ]

    static let inputEdiTestLog: [String] = [
        "1785592800000\tDL1ABC\t144300000\t2m\tSSB\t59\t59\t1\t\t\t59 5 JO62QM\tGermany\t\t\t\tRUN\tfalse\tfalse\n",
        "1785593100000\tOK2XX\t144300000\t2m\tSSB\t59\t59\t2\t\t\t59 12 JN89AA\tCzech Republic\t\t\t\tRUN\tfalse\tfalse\n",
        "1785593340000\tDL1ABC\t144300000\t2m\tSSB\t59\t59\t3\t\t\t59 5 JO62QM\tGermany\t\t\t\tRUN\tfalse\tfalse\n",
    ]

    static let inputEdiEdgeLog: [String] = [
        "1785592800000\tDL1ABC\t144300000\t2m\tSSB\t59\t59\t1\t\t\t59 5 jo62qm\tGermany\t\t\t\tRUN\tfalse\tfalse\n",
        "1785592860000\tOK1KHL\t144300000\t2m\tCW\t 599 \t599\t\t2\t\t\t599 7 JO70FC\tCzech Republic\t\t\t\tRUN\tfalse\tfalse\n",
        "1785592920000\tOK2XX\t144300000\t2m\tFM\t59\t59\t3\t42\t\t59 12345 XX00\t\t\t\t\tRUN\tfalse\tfalse\n",
        "1785592980000\tDL1ABC\t144300000\t2m\tSSB\t59\t59\t4\t\t\t59 6 JO62QM\tGermany\t\t\t\tRUN\tfalse\tfalse\n",
        "1785593040000\tS51A\t144300000\t2m\t\t59\t59\t\t\t\t59 0012 JN76TO\tSlovenia\t\t\t\tRUN\ttrue\tfalse\n",
        "1785593100000\tOE3XYZ\t144300000\t2m\tAM\t59\t59\t5\t\t\t59 abc JN88\tAustria\t\t\t\tRUN\tfalse\tfalse\n",
        "1785593160000\t9A1A\t144300000\t2m\tFT8\t59\t59\t6\t\t\tjn75\tCroatia\t\t\t\tRUN\tfalse\tfalse\n",
        "1785593220000\tHA1A\t144300000\t2m\tRTTY\t59\t59\t7\t\t\t59 3 JN87AB extra JN97CD\tHungary\t\t\t\tRUN\tfalse\tfalse\n",
        "1785593280000\tYU1A\t144300000\t2m\tSSB\t59\t59\t8\t\t\t59 8 kn04aa\tSerbia\t\t\t\tRUN\tfalse\tfalse\n",
        "1785593340000\tOK1AAA\t432100000\t70cm\tSSB\t59\t59\t9\t\t\t59 1 JN79AA\tCzech Republic\t\t\t\tRUN\tfalse\tfalse\n",
        "1785593400000\tOK1DEL\t144300000\t2m\tSSB\t59\t59\t10\t\t\t59 1 JO80AA\t\t\t\t\tRUN\tfalse\ttrue\n",
        "\tOK1BBB\t144300000\t2m\tSSB\t59\t59\t11\t\t\t59 1 JO80AA\t\t\t\t\tRUN\tfalse\tfalse\n",
        "1785593460000\tSP2B\t144300000\t2m\tCW\t59\t59\t12\t-5\t\t59 10 JO94AA\tPoland\t\t\t\tRUN\tfalse\tfalse\n",
        "1785593460000\tSP1A\t144300000\t2m\tCW\t59\t59\t13\t\t\t59 9 JO93AA\tPoland\t\t\t\tRUN\tfalse\tfalse\n",
    ]

    static let testCsv: [String] = [
        "time_utc,call,band,freq_khz,mode,rst_sent,rst_rcvd,nr_sent,nr_rcvd,exch_sent,exch_rcvd,country,continent,run,operator,xqso,comment\r\n",
        "2026-11-28 12:00,DL1ABC,40m,7010.0,CW,,,,,,,,,RUN,,0,\r\n",
        "2026-11-28 12:01,W1AW,20m,14025.0,CW,,,,,,,,,RUN,,0,\"tnx, \"\"73\"\"\"\r\n",
        "2026-11-28 12:02,G3AB,20m,14200.0,SSB,,,,,,,,,RUN,,0,\r\n",
    ]

    static let testText: [String] = [
        "CQ WW CW \u{2014} OK1XOE\n",
        "--------------------\n",
        "    # \u{010C}as UTC          Vola\u{010D}ka      P\u{00E1}smo       kHz M\u{00F3}d   RSTs V\u{00FD}m\u{011B}na odesl. RSTp V\u{00FD}m\u{011B}na p\u{0159}ij.   Pozn.\n",
        "    1 2026-11-28 12:00 DL1ABC         40m    7010.0 CW                                          \n",
        "    2 2026-11-28 12:01 W1AW           20m   14025.0 CW                                          tnx, \"73\"\n",
        "    3 2026-11-28 12:02 G3AB           20m   14200.0 SSB                                         \n",
    ]

    static let testSummary: [String] = [
        "Souhrn z\u{00E1}vodu: CQ WW CW\n",
        "Stanice:       OK1XOE\n",
        "Obdob\u{00ED}:        2026-11-28 12:00 \u{2013} 2026-11-28 12:02 UTC\n",
        "QSO 3 \u{00B7} body 7 \u{00B7} n\u{00E1}sobi\u{010D}e 3 \u{00B7} sk\u{00F3}re 21\n",
        "\n",
        "P\u{00E1}smo      CW    SSB  Celkem\n",
        "40m         1      0       1\n",
        "20m         1      1       2\n",
        "Celkem      2      1       3\n",
    ]

    static let edgeCsv: [String] = [
        "time_utc,call,band,freq_khz,mode,rst_sent,rst_rcvd,nr_sent,nr_rcvd,exch_sent,exch_rcvd,country,continent,run,operator,xqso,comment\r\n",
        "2026-11-28 12:00,OK1\u{017D}\u{00C1},40m,7000.3,SSB,,,,,,\u{011B}\u{0161}\u{010D}\u{0159},Czech Republic,EU,SEARCH_AND_POUNCE,\u{017D}ofie \u{1F600},1,\"\"\"x\"\"\"\r\n",
        "2026-11-28 12:01,OK2ABC,160m,1845.0,CW,5nn,,,,,,Czech Republic,EU,RUN,OK1XOE,0,\r\n",
        "2026-11-28 12:02,W1AW,20m,14025.1,CW,599,599,1,15,15,05,United States,NA,RUN,OK1XOE,0,\"a,b\"\r\n",
        "2026-11-28 12:02,DL1ABC,,0.0,,,,,,,,Germany,EU,RUN,,0,\"cr\ronly\"\r\n",
        "2026-11-28 12:03,SP9XYZ,20m,14025.2,FT8,,,,-7,,,Poland,EU,RUN,\u{017D}ofie \u{1F600},0,\"\"\"\u{0301} 73 \u{1F600}\"\r\n",
        "2026-11-29 00:05,JA1ABC,15m,21000.0,SSB,,,,,,,Japan,AS,SEARCH_AND_POUNCE,  ,0,\r\n",
        ",G3AB,80m,3500.0,CW,,,,,,,,,RUN,,0,\"line1\r\n",
        "line2\"\r\n",
    ]

    static let edgeText: [String] = [
        "Mistrovstv\u{00ED} \u{010C}R \u{2014} OK1\u{017D}\u{00C1}/P \u{1F600}\n",
        "---------------------------\n",
        "    # \u{010C}as UTC          Vola\u{010D}ka      P\u{00E1}smo       kHz M\u{00F3}d   RSTs V\u{00FD}m\u{011B}na odesl. RSTp V\u{00FD}m\u{011B}na p\u{0159}ij.   Pozn.\n",
        "    1 2026-11-28 12:00 OK1\u{017D}\u{00C1}          40m    7000.3 SSB                          \u{011B}\u{0161}\u{010D}\u{0159}           X-QSO \"x\"\n",
        "    2 2026-11-28 12:01 OK2ABC        160m    1845.0 CW    5nn                                   \n",
        "    3 2026-11-28 12:02 W1AW           20m   14025.1 CW    599  15           599  05             a,b\n",
        "    4 2026-11-28 12:02 DL1ABC                   0.0                                             cr\ronly\n",
        "    5 2026-11-28 12:03 SP9XYZ         20m   14025.2 FT8                                         \"\u{0301} 73 \u{1F600}\n",
        "    6 2026-11-29 00:05 JA1ABC         15m   21000.0 SSB                                         \n",
        "    7                  G3AB           80m    3500.0 CW                                          line1\r\n",
        "line2\n",
    ]

    static let shortTitleText: [String] = [
        "Z\u{00E1}vod \u{1F600}\n",
        "--------------------\n",
        "    # \u{010C}as UTC          Vola\u{010D}ka      P\u{00E1}smo       kHz M\u{00F3}d   RSTs V\u{00FD}m\u{011B}na odesl. RSTp V\u{00FD}m\u{011B}na p\u{0159}ij.   Pozn.\n",
    ]

    static let edgeSummaryNil: [String] = [
        "Souhrn z\u{00E1}vodu: Z\u{00E1}vod\n",
        "Stanice:       OK1\u{017D}\u{00C1}\n",
        "Obdob\u{00ED}:        2026-11-28 12:00 \u{2013} 2026-11-29 00:05 UTC\n",
        "\n",
        "P\u{00E1}smo      CW    SSB      ?    FT8  Celkem\n",
        "160m        1      0      0      0       1\n",
        "40m         0      1      0      0       1\n",
        "20m         1      0      0      1       2\n",
        "15m         0      1      0      0       1\n",
        "?           0      0      1      0       1\n",
        "Celkem      2      2      1      1       6\n",
    ]

    static let edgeSummaryQtc: [String] = [
        "Souhrn z\u{00E1}vodu: WAE\n",
        "Stanice:       OK1XOE\n",
        "Obdob\u{00ED}:        2026-11-28 12:00 \u{2013} 2026-11-29 00:05 UTC\n",
        "QSO 5 \u{00B7} body 12 \u{00B7} n\u{00E1}sobi\u{010D}e 4 \u{00B7} QTC 3 \u{00B7} sk\u{00F3}re 60\n",
        "\n",
        "P\u{00E1}smo      CW    SSB      ?    FT8  Celkem\n",
        "160m        1      0      0      0       1\n",
        "40m         0      1      0      0       1\n",
        "20m         1      0      0      1       2\n",
        "15m         0      1      0      0       1\n",
        "?           0      0      1      0       1\n",
        "Celkem      2      2      1      1       6\n",
    ]

    static let edgeSummaryUntimedLast: [String] = [
        "EXC java.lang.NullPointerException: temporal",
    ]

    static let untimedOnlySummary: [String] = [
        "Souhrn z\u{00E1}vodu: Z\u{00E1}vod\n",
        "Stanice:       OK1XOE\n",
        "\n",
        "P\u{00E1}smo      CW  Celkem\n",
        "80m         1       1\n",
        "Celkem      1       1\n",
    ]

    static let emptySummary: [String] = [
        "Souhrn z\u{00E1}vodu: \n",
        "Stanice:       \n",
        "\n",
        "P\u{00E1}smo   Celkem\n",
        "Celkem       0\n",
    ]

    static let emptyCsv: [String] = [
        "time_utc,call,band,freq_khz,mode,rst_sent,rst_rcvd,nr_sent,nr_rcvd,exch_sent,exch_rcvd,country,continent,run,operator,xqso,comment\r\n",
    ]

    static let pivot_BAND_MODE: [String] = [
        "R 160m 1: CW=1 SSB=0 ?=0 FT8=0\n",
        "R 80m 1: CW=1 SSB=0 ?=0 FT8=0\n",
        "R 40m 1: CW=0 SSB=1 ?=0 FT8=0\n",
        "R 20m 2: CW=1 SSB=0 ?=0 FT8=1\n",
        "R 15m 1: CW=0 SSB=1 ?=0 FT8=0\n",
        "R ? 1: CW=0 SSB=0 ?=1 FT8=0\n",
        "C CW 3\n",
        "C SSB 2\n",
        "C ? 1\n",
        "C FT8 1\n",
        "T 7\n",
    ]

    static let pivot_MODE_BAND: [String] = [
        "R CW 3: 160m=1 80m=1 40m=0 20m=1 15m=0 ?=0\n",
        "R SSB 2: 160m=0 80m=0 40m=1 20m=0 15m=1 ?=0\n",
        "R ? 1: 160m=0 80m=0 40m=0 20m=0 15m=0 ?=1\n",
        "R FT8 1: 160m=0 80m=0 40m=0 20m=1 15m=0 ?=0\n",
        "C 160m 1\n",
        "C 80m 1\n",
        "C 40m 1\n",
        "C 20m 2\n",
        "C 15m 1\n",
        "C ? 1\n",
        "T 7\n",
    ]

    static let pivot_HOUR_COUNTRY: [String] = [
        "R 11-28 12Z 5: Czech Republic=2 ?=0 Germany=1 Japan=0 Poland=1 United States=1\n",
        "R 11-29 00Z 1: Czech Republic=0 ?=0 Germany=0 Japan=1 Poland=0 United States=0\n",
        "R ? 1: Czech Republic=0 ?=1 Germany=0 Japan=0 Poland=0 United States=0\n",
        "C Czech Republic 2\n",
        "C ? 1\n",
        "C Germany 1\n",
        "C Japan 1\n",
        "C Poland 1\n",
        "C United States 1\n",
        "T 7\n",
    ]

    static let pivot_DAY_OPERATOR: [String] = [
        "R 2026-11-28 5: ?=1 OK1XOE=2 \u{017D}ofie \u{1F600}=2\n",
        "R 2026-11-29 1: ?=1 OK1XOE=0 \u{017D}ofie \u{1F600}=0\n",
        "R ? 1: ?=1 OK1XOE=0 \u{017D}ofie \u{1F600}=0\n",
        "C ? 3\n",
        "C OK1XOE 2\n",
        "C \u{017D}ofie \u{1F600} 2\n",
        "T 7\n",
    ]

    static let pivot_CONTINENT_RUN_SP: [String] = [
        "R EU 4: RUN=3 SEARCH_AND_POUNCE=1\n",
        "R ? 1: RUN=1 SEARCH_AND_POUNCE=0\n",
        "R AS 1: RUN=0 SEARCH_AND_POUNCE=1\n",
        "R NA 1: RUN=1 SEARCH_AND_POUNCE=0\n",
        "C RUN 5\n",
        "C SEARCH_AND_POUNCE 2\n",
        "T 7\n",
    ]

    static let pivot_NONE_NONE: [String] = [
        "R Celkem 7: Celkem=7\n",
        "C Celkem 7\n",
        "T 7\n",
    ]

    static let ediTest: [String] = [
        "[REG1TEST;1]\r\n",
        "TName=IARU Region 1 VHF Contest (144 MHz)\r\n",
        "TDate=20260801;20260801\r\n",
        "PCall=OK1XOE\r\n",
        "PWWLo=JO70FC\r\n",
        "PExch=\r\n",
        "PAdr1=\r\n",
        "PAdr2=\r\n",
        "PSect=SINGLE\r\n",
        "PBand=144 MHz\r\n",
        "PClub=\r\n",
        "RName=\r\n",
        "RCall=OK1XOE\r\n",
        "RAdr1=\r\n",
        "RCity=\r\n",
        "RCoun=\r\n",
        "RHBBS=\r\n",
        "MOpe1=OK1XOE\r\n",
        "SPowe=100\r\n",
        "SAnte=yagi\r\n",
        "CQSOs=2;1\r\n",
        "CQSOP=446\r\n",
        "CWWLs=2;0;1\r\n",
        "CWWLB=0\r\n",
        "CExcs=0;0;1\r\n",
        "CExcB=0\r\n",
        "CDXCs=2;0;1\r\n",
        "CDXCB=0\r\n",
        "CToSc=446\r\n",
        "CODXC=DL1ABC;JO62QM;279\r\n",
        "[Remarks]\r\n",
        "[QSORecords;3]\r\n",
        "260801;1400;DL1ABC;1;59;001;59;005;;JO62QM;280;;N;N;\r\n",
        "260801;1405;OK2XX;1;59;002;59;012;;JN89AA;166;;N;N;\r\n",
        "260801;1409;DL1ABC;1;59;003;59;005;;JO62QM;0;;;;D\r\n",
    ]

    static let ediEdge: [String] = [
        "[REG1TEST;1]\r\n",
        "TName=IARU Region 1 VHF Contest (144 MHz)\r\n",
        "TDate=20260801;20260801\r\n",
        "PCall=OK1XOE\r\n",
        "PWWLo=JO70FC\r\n",
        "PExch=\r\n",
        "PAdr1=Na V\u{00FD}slun\u{00ED} 1\r\n",
        "PAdr2=\r\n",
        "PSect=SINGLE-OP\r\n",
        "PBand=144 MHz\r\n",
        "PClub=OK1KHL\r\n",
        "RName=Tom\u{00E1}\u{0161} \u{0160}\u{0165}astn\u{00FD}\r\n",
        "RCall=OK1XOE\r\n",
        "RAdr1=Na V\u{00FD}slun\u{00ED} 1\r\n",
        "RCity=Praha\r\n",
        "RCoun=Czech Republic\r\n",
        "RHBBS=ok1xoe@example.org\r\n",
        "MOpe1=OK1XOE OK1ABC\r\n",
        "SPowe=100\r\n",
        "SAnte=yagi 11el\r\n",
        "CQSOs=9;1\r\n",
        "CQSOP=2602\r\n",
        "CWWLs=8;0;1\r\n",
        "CWWLB=0\r\n",
        "CExcs=0;0;1\r\n",
        "CExcB=0\r\n",
        "CDXCs=7;0;1\r\n",
        "CDXCB=0\r\n",
        "CToSc=2602\r\n",
        "CODXC=YU1A;KN04AA;797\r\n",
        "[Remarks]\r\n",
        "Pozn\u{00E1}mka \u{0161}\r\n",
        "[QSORecords;11]\r\n",
        "260801;1400;DL1ABC;1;59;001;59;005;;JO62QM;280;;N;N;\r\n",
        "260801;1401;OK1KHL;2;599;002;599;007;;JO70FC;1;;N;N;\r\n",
        "260801;1402;OK2XX;6;59;003;59;042;;XX00;0;;N;;\r\n",
        "260801;1403;DL1ABC;1;59;004;59;006;;JO62QM;0;;;;D\r\n",
        "260801;1404;S51A;0;59;;59;012;;JN76TO;0;;;;D\r\n",
        "260801;1405;OE3XYZ;5;59;005;59;abc;;JN88;257;;N;N;\r\n",
        "260801;1406;9A1A;0;59;006;59;;;;0;;;N;\r\n",
        "260801;1407;HA1A;7;59;007;59;003;;JN87AB;358;;N;N;\r\n",
        "260801;1408;YU1A;1;59;008;59;;;KN04AA;798;;N;N;\r\n",
        "260801;1411;SP2B;2;59;012;59;-05;;JO94AA;500;;N;N;\r\n",
        "260801;1411;SP1A;2;59;013;59;009;;JO93AA;408;;N;;\r\n",
    ]

    static let ediEdge70cm: [String] = [
        "[REG1TEST;1]\r\n",
        "TName=IARU Region 1 VHF Contest (144 MHz)\r\n",
        "TDate=20260801;20260801\r\n",
        "PCall=OK1XOE\r\n",
        "PWWLo=JO70FC\r\n",
        "PExch=\r\n",
        "PAdr1=Na V\u{00FD}slun\u{00ED} 1\r\n",
        "PAdr2=\r\n",
        "PSect=SINGLE-OP\r\n",
        "PBand=432 MHz\r\n",
        "PClub=OK1KHL\r\n",
        "RName=Tom\u{00E1}\u{0161} \u{0160}\u{0165}astn\u{00FD}\r\n",
        "RCall=OK1XOE\r\n",
        "RAdr1=Na V\u{00FD}slun\u{00ED} 1\r\n",
        "RCity=Praha\r\n",
        "RCoun=Czech Republic\r\n",
        "RHBBS=ok1xoe@example.org\r\n",
        "MOpe1=OK1XOE OK1ABC\r\n",
        "SPowe=100\r\n",
        "SAnte=yagi 11el\r\n",
        "CQSOs=1;1\r\n",
        "CQSOP=125\r\n",
        "CWWLs=1;0;1\r\n",
        "CWWLB=0\r\n",
        "CExcs=0;0;1\r\n",
        "CExcB=0\r\n",
        "CDXCs=1;0;1\r\n",
        "CDXCB=0\r\n",
        "CToSc=125\r\n",
        "CODXC=OK1AAA;JN79AA;124\r\n",
        "[Remarks]\r\n",
        "Pozn\u{00E1}mka \u{0161}\r\n",
        "[QSORecords;1]\r\n",
        "260801;1409;OK1AAA;1;59;009;59;001;;JN79AA;125;;N;N;\r\n",
    ]

    static let ediEmptyBand: [String] = [
        "[REG1TEST;1]\r\n",
        "TName=IARU Region 1 VHF Contest (144 MHz)\r\n",
        "TDate=;\r\n",
        "PCall=OK1XOE\r\n",
        "PWWLo=\r\n",
        "PExch=\r\n",
        "PAdr1=Na V\u{00FD}slun\u{00ED} 1\r\n",
        "PAdr2=\r\n",
        "PSect=\r\n",
        "PBand=50 MHz\r\n",
        "PClub=OK1KHL\r\n",
        "RName=Tom\u{00E1}\u{0161} \u{0160}\u{0165}astn\u{00FD}\r\n",
        "RCall=OK1XOE\r\n",
        "RAdr1=Na V\u{00FD}slun\u{00ED} 1\r\n",
        "RCity=Praha\r\n",
        "RCoun=Czech Republic\r\n",
        "RHBBS=ok1xoe@example.org\r\n",
        "MOpe1=\r\n",
        "SPowe=\r\n",
        "SAnte=\r\n",
        "CQSOs=0;1\r\n",
        "CQSOP=0\r\n",
        "CWWLs=0;0;1\r\n",
        "CWWLB=0\r\n",
        "CExcs=0;0;1\r\n",
        "CExcB=0\r\n",
        "CDXCs=0;0;1\r\n",
        "CDXCB=0\r\n",
        "CToSc=0\r\n",
        "CODXC=\r\n",
        "[Remarks]\r\n",
        "[QSORecords;0]\r\n",
    ]

    static let distancesFromJO70FC: [String] = [
        "JO62QM 279.062689181954\n",
        "JN89AA 165.97877955431454\n",
        "JO70FC 0.0\n",
        "XX00 -1.0\n",
        "JN76TO 398.6021590148746\n",
        "JN88 256.448322794508\n",
        "JN87AB 357.6877955743529\n",
        "KN04AA 797.2438890883025\n",
        "JN79AA 124.15262687119021\n",
        "JO94AA 499.5302126887626\n",
        "JO93AA 407.98221824495283\n",
    ]

    static let bandNames: [String] = [
        "160m=1 MHz\n",
        "80m=3 MHz\n",
        "60m=5 MHz\n",
        "40m=7 MHz\n",
        "30m=10 MHz\n",
        "20m=14 MHz\n",
        "17m=18 MHz\n",
        "15m=21 MHz\n",
        "12m=24 MHz\n",
        "10m=28 MHz\n",
        "6m=50 MHz\n",
        "2m=144 MHz\n",
        "70cm=432 MHz\n",
    ]

    static let paginate: [String] = [
        "# exact 3/7\n",
        "TITLE|-----|cols|qso 1|qso 2|qso 3|qso 4\n",
        "TITLE|-----|cols|qso 5|qso 6|qso 7|qso 8\n",
        "# perPage<=header 3/3\n",
        "TITLE|-----|cols|qso 1\n",
        "TITLE|-----|cols|qso 2\n",
        "TITLE|-----|cols|qso 3\n",
        "TITLE|-----|cols|qso 4\n",
        "TITLE|-----|cols|qso 5\n",
        "TITLE|-----|cols|qso 6\n",
        "TITLE|-----|cols|qso 7\n",
        "TITLE|-----|cols|qso 8\n",
        "# header>size 20/7\n",
        "a|b\n",
        "# empty 3/7\n",
        "\n",
        "# no header 0/5\n",
        "TITLE|-----|cols|qso 1|qso 2\n",
        "qso 3|qso 4|qso 5|qso 6|qso 7\n",
        "qso 8\n",
        "# negative 0/-1\n",
        "a\n",
        "b\n",
    ]

    static let utcStamps: [String] = [
        "0|1970-01-01 00:00|700101;0000;19700101|01-01 00Z\n",
        "-1|1969-12-31 23:59|691231;2359;19691231|12-31 23Z\n",
        "951868799999|2000-02-29 23:59|000229;2359;20000229|02-29 23Z\n",
        "951868800000|2000-03-01 00:00|000301;0000;20000301|03-01 00Z\n",
        "-62167219200000|0001-01-01 00:00|010101;0000;00010101|01-01 00Z\n",
        "-62167219200001|0002-12-31 23:59|021231;2359;00021231|12-31 23Z\n",
        "-62198755200000|0002-01-01 00:00|020101;0000;00020101|01-01 00Z\n",
        "253402300799999|9999-12-31 23:59|991231;2359;99991231|12-31 23Z\n",
        "253402300800000|+10000-01-01 00:00|000101;0000;+100000101|01-01 00Z\n",
        "4102444800000|2100-01-01 00:00|000101;0000;21000101|01-01 00Z\n",
        "-2208988800000|1900-01-01 00:00|000101;0000;19000101|01-01 00Z\n",
        "1795910700000|2026-11-29 00:05|261129;0005;20261129|11-29 00Z\n",
    ]

}
