import Foundation

/// Declarative definition of a multiplier set (YAML in `<dir>/multipliers/`).
/// A set is either a fixed list (`FIXED` — inline `values`, `range`, or
/// `valuesFile`), generated by an algorithm (`ALGORITHM`, e.g. WPX), or derived
/// from external data (`EXTERNAL_DATA`, e.g. DXCC).
///
/// Port of Java `multiplier/MultiplierSetDefinition.java` (record + 6
/// nested records + 2 enums), read by Jackson. Hence:
/// - **Every Java field is read**, even those nobody uses
///   (`schemaVersion`, `enumerable`, `metadata`, `provider.data`): Jackson checks the
///   type for them too, so `enumerable: ano` rejects the definition.
/// - A Java primitive `int` is an `Int` with default `0` (`schemaVersion`,
///   `Range.min`/`max`), a Java `Integer`/`Boolean`/`String` is optional.
/// - The `values` list carries `nil` elements (`values: [~]` → `[nil]`), the map
///   `attributes` carries `nil` values (`{ c: ~ }`) — Java lets both through.
/// - Enums are case-sensitive (`kind: fixed` is an error) and also accept the ordinal
///   (`kind: 1` → `ALGORITHM`); the case order is Java's.
public struct MultiplierSetDefinition: YamlRecord, Equatable, Sendable {

    public enum SetKind: String, YamlEnum, Sendable {
        case FIXED, ALGORITHM, EXTERNAL_DATA
    }

    public enum KeyType: String, YamlEnum, Sendable {
        case INTEGER, TEXT, CALLSIGN_PREFIX
    }

    public struct Meta: YamlRecord, Equatable, Sendable {
        public var name: String?
        public var description: String?

        public init(name: String?, description: String?) {
            self.name = name
            self.description = description
        }

        public init(yaml object: YamlObject) {
            name = object.string("name")
            description = object.string("description")
        }
    }

    /// Range of integer keys `min…max` inclusive. A missing bound is `0`
    /// (Java `int`), so `range: { min: 1 }` gives an empty set.
    public struct Range: YamlRecord, Equatable, Sendable {
        public var min: Int
        public var max: Int

        public init(min: Int, max: Int) {
            self.min = min
            self.max = max
        }

        public init(yaml object: YamlObject) {
            min = object.int("min").map(Int.init) ?? 0
            max = object.int("max").map(Int.init) ?? 0
        }
    }

    public struct Validation: YamlRecord, Equatable, Sendable {
        public var keyPattern: String?

        public init(keyPattern: String?) {
            self.keyPattern = keyPattern
        }

        public init(yaml object: YamlObject) {
            keyPattern = object.string("keyPattern")
        }
    }

    public struct ValueDef: YamlRecord, Equatable, Sendable {
        public var key: String?
        public var label: String?
        /// Java `Map<String, String>` (`LinkedHashMap`): document order,
        /// scalars as text in their original spelling, `~` as `nil`.
        public var attributes: YamlOrderedMap<String>?

        public init(key: String?, label: String?, attributes: YamlOrderedMap<String>?) {
            self.key = key
            self.label = label
            self.attributes = attributes
        }

        public init(yaml object: YamlObject) {
            key = object.string("key")
            label = object.string("label")
            attributes = object.map("attributes", of: String.self)
        }
    }

    public struct Provider: YamlRecord, Equatable, Sendable {
        public var type: String?
        /// Nobody reads it (`"~/dxcc-json/dxcc.json"` — the caller supplies the resolver).
        public var data: String?

        public init(type: String?, data: String?) {
            self.type = type
            self.data = data
        }

        public init(yaml object: YamlObject) {
            type = object.string("type")
            data = object.string("data")
        }
    }

    public struct Algorithm: YamlRecord, Equatable, Sendable {
        public var type: String?

        public init(type: String?) {
            self.type = type
        }

        public init(yaml object: YamlObject) {
            type = object.string("type")
        }
    }

    /// Nobody reads it — no version check (unlike contest definitions).
    public var schemaVersion: Int
    public var id: String?
    public var kind: SetKind?
    public var keyType: KeyType?
    /// Nobody reads it — `FixedMultiplierSet.enumerable` is hard-wired to `true`.
    public var enumerable: Bool?
    /// Nobody reads it.
    public var metadata: Meta?
    public var range: Range?
    public var validation: Validation?
    public var values: [ValueDef?]?
    public var valuesFile: String?
    public var provider: Provider?
    public var algorithm: Algorithm?
    public var keyLength: Int?

    public init(schemaVersion: Int = 0, id: String?, kind: SetKind?, keyType: KeyType? = nil,
                enumerable: Bool? = nil, metadata: Meta? = nil, range: Range? = nil,
                validation: Validation? = nil, values: [ValueDef?]? = nil, valuesFile: String? = nil,
                provider: Provider? = nil, algorithm: Algorithm? = nil, keyLength: Int? = nil) {
        self.schemaVersion = schemaVersion
        self.id = id
        self.kind = kind
        self.keyType = keyType
        self.enumerable = enumerable
        self.metadata = metadata
        self.range = range
        self.validation = validation
        self.values = values
        self.valuesFile = valuesFile
        self.provider = provider
        self.algorithm = algorithm
        self.keyLength = keyLength
    }

    public init(yaml object: YamlObject) {
        schemaVersion = object.int("schemaVersion").map(Int.init) ?? 0
        id = object.string("id")
        kind = object.decode("kind", as: SetKind.self)
        keyType = object.decode("keyType", as: KeyType.self)
        enumerable = object.bool("enumerable")
        metadata = object.decode("metadata", as: Meta.self)
        range = object.decode("range", as: Range.self)
        validation = object.decode("validation", as: Validation.self)
        values = object.list("values", of: ValueDef.self)
        valuesFile = object.string("valuesFile")
        provider = object.decode("provider", as: Provider.self)
        algorithm = object.decode("algorithm", as: Algorithm.self)
        keyLength = object.int("keyLength").map(Int.init)
    }
}
