// Tables measured on Java (JDK 21.0.2) by the probe `ProbeSwiftRows.java`
// (maintainer-only probe). The rows are not edited
// by hand — on a change the probe is run again and the table regenerated; the source of the cases
// is `gen_cases.py` next to the probe.
//
// - `matchTable`: `Pattern.compile(pattern)`, then `matcher(input).matches()`, all
//   `find()` hits as `start-end` in UTF-16 units and the groups of the first
//   hit; or `PatternSyntaxException.getDescription()` and `getIndex()`.
// - `splitTable`: `Pattern.compile(pattern).split(input, limit)`.
// - `replaceFirstTable`: `matcher(input).replaceFirst(Matcher.quoteReplacement(replacement))`.

enum JavaMeasuredRegex {
    enum Outcome: Sendable {
        case ok(matches: Bool, finds: String, groups: [String?])
        case error(String, Int)
    }

    static let matchTable: [(pattern: String, input: String, outcome: Outcome)] = [
        ("\\d+", "12", .ok(matches: true, finds: "0-2", groups: [])),
        ("\\d+", "\u{663}", .ok(matches: false, finds: "", groups: [])),
        ("\\d+", "\u{FF11}", .ok(matches: false, finds: "", groups: [])),
        ("\\d+", "1\u{663}", .ok(matches: false, finds: "0-1", groups: [])),
        ("\\D", "\u{663}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\D", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\D", "1", .ok(matches: false, finds: "", groups: [])),
        ("\\s", " ", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\s", "\u{A0}", .ok(matches: false, finds: "", groups: [])),
        ("\\s", "\u{B}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\s", "\u{C}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\s", "\u{1C}", .ok(matches: false, finds: "", groups: [])),
        ("\\s", "\u{85}", .ok(matches: false, finds: "", groups: [])),
        ("\\s", "\u{2028}", .ok(matches: false, finds: "", groups: [])),
        ("\\s", "\u{3000}", .ok(matches: false, finds: "", groups: [])),
        ("\\s", "\u{9}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\S", "\u{A0}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\S", "\u{B}", .ok(matches: false, finds: "", groups: [])),
        ("\\w+", "a_1Z", .ok(matches: true, finds: "0-4", groups: [])),
        ("\\w+", "\u{E9}", .ok(matches: false, finds: "", groups: [])),
        ("\\w+", "\u{663}", .ok(matches: false, finds: "", groups: [])),
        ("\\w+", "\u{130}", .ok(matches: false, finds: "", groups: [])),
        ("\\W", "\u{E9}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\W", "_", .ok(matches: false, finds: "", groups: [])),
        ("\\b", "\u{E9}", .ok(matches: false, finds: "", groups: [])),
        ("\\b", "ab cd", .ok(matches: false, finds: "0-0 2-2 3-3 5-5", groups: [])),
        ("\\b", "a\u{301}", .ok(matches: false, finds: "0-0 2-2", groups: [])),
        ("\\b", "a\u{301} b", .ok(matches: false, finds: "0-0 2-2 3-3 4-4", groups: [])),
        ("\\b", "\u{E9}\u{301} ", .ok(matches: false, finds: "1-1 2-2", groups: [])),
        ("\\b", " \u{301}a", .ok(matches: false, finds: "2-2 3-3", groups: [])),
        ("\\b", "\u{301}", .ok(matches: false, finds: "", groups: [])),
        ("\\b", "x\u{301}\u{302}y", .ok(matches: false, finds: "0-0 4-4", groups: [])),
        ("\\b", "\u{663}\u{301}", .ok(matches: false, finds: "1-1 2-2", groups: [])),
        ("\\b", "\u{1D400}\u{301}", .ok(matches: false, finds: "", groups: [])),
        ("\\b", "a\u{1D167}", .ok(matches: false, finds: "0-0", groups: [])),
        ("\\b", "a\u{1D167}b", .ok(matches: false, finds: "0-0 3-3 4-4", groups: [])),
        ("\\b", "_\u{301}", .ok(matches: false, finds: "0-0 1-1", groups: [])),
        ("\\b", "", .ok(matches: false, finds: "", groups: [])),
        ("\\b", "a", .ok(matches: false, finds: "0-0 1-1", groups: [])),
        ("\\B", "\u{E9}", .ok(matches: false, finds: "0-0 1-1", groups: [])),
        ("\\B", "ab cd", .ok(matches: false, finds: "1-1 4-4", groups: [])),
        ("\\B", "a\u{301}", .ok(matches: false, finds: "1-1", groups: [])),
        ("\\B", "", .ok(matches: true, finds: "0-0", groups: [])),
        ("\\bx", "\u{E9}x", .ok(matches: false, finds: "1-2", groups: [])),
        ("\\bx", "ax", .ok(matches: false, finds: "", groups: [])),
        ("\\bx", " x", .ok(matches: false, finds: "1-2", groups: [])),
        ("x\\b", "x\u{E9}", .ok(matches: false, finds: "0-1", groups: [])),
        ("x\\b", "xa", .ok(matches: false, finds: "", groups: [])),
        ("x\\b", "x ", .ok(matches: false, finds: "0-1", groups: [])),
        (".", "\u{A}", .ok(matches: false, finds: "", groups: [])),
        (".", "\u{D}", .ok(matches: false, finds: "", groups: [])),
        (".", "\u{85}", .ok(matches: false, finds: "", groups: [])),
        (".", "\u{2028}", .ok(matches: false, finds: "", groups: [])),
        (".", "\u{2029}", .ok(matches: false, finds: "", groups: [])),
        (".", "\u{B}", .ok(matches: true, finds: "0-1", groups: [])),
        (".", "\u{C}", .ok(matches: true, finds: "0-1", groups: [])),
        (".", "\u{1F600}", .ok(matches: true, finds: "0-2", groups: [])),
        (".", "a", .ok(matches: true, finds: "0-1", groups: [])),
        (".", "\u{0}", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?s).", "\u{A}", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?s).", "\u{D}", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?s).", "\u{85}", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?d).", "\u{A}", .ok(matches: false, finds: "", groups: [])),
        ("(?d).", "\u{D}", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?d).", "\u{85}", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?d).", "\u{2028}", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?s:.).", "\u{A}\u{A}", .ok(matches: false, finds: "", groups: [])),
        ("(?s:.).", "\u{A}a", .ok(matches: true, finds: "0-2", groups: [])),
        ("a$", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("a$", "a\u{A}", .ok(matches: false, finds: "0-1", groups: [])),
        ("a$", "a\u{D}\u{A}", .ok(matches: false, finds: "0-1", groups: [])),
        ("a$", "a\u{D}", .ok(matches: false, finds: "0-1", groups: [])),
        ("a$", "a\u{B}", .ok(matches: false, finds: "", groups: [])),
        ("a$", "a\u{C}", .ok(matches: false, finds: "", groups: [])),
        ("a$", "a\u{85}", .ok(matches: false, finds: "0-1", groups: [])),
        ("a$", "a\u{2028}", .ok(matches: false, finds: "0-1", groups: [])),
        ("a$", "a\u{2029}", .ok(matches: false, finds: "0-1", groups: [])),
        ("a$", "a\u{A}\u{A}", .ok(matches: false, finds: "", groups: [])),
        ("a$", "a\u{A}\u{D}", .ok(matches: false, finds: "", groups: [])),
        ("$", "", .ok(matches: true, finds: "0-0", groups: [])),
        ("$", "a\u{D}\u{A}", .ok(matches: false, finds: "1-1 3-3", groups: [])),
        ("$", "\u{D}\u{A}", .ok(matches: false, finds: "0-0 2-2", groups: [])),
        ("$", "\u{A}", .ok(matches: false, finds: "0-0 1-1", groups: [])),
        ("$", "a\u{A}b", .ok(matches: false, finds: "3-3", groups: [])),
        ("(?m)$", "", .ok(matches: true, finds: "0-0", groups: [])),
        ("(?m)$", "a\u{D}\u{A}b\u{B}c\u{C}", .ok(matches: false, finds: "1-1 7-7", groups: [])),
        ("(?m)$", "a\u{A}b\u{85}c\u{2028}d\u{2029}", .ok(matches: false, finds: "1-1 3-3 5-5 7-7 8-8", groups: [])),
        ("(?m)$", "\u{D}\u{A}\u{D}\u{A}", .ok(matches: false, finds: "0-0 2-2 4-4", groups: [])),
        ("(?m)^", "", .ok(matches: false, finds: "", groups: [])),
        ("(?m)^", "\u{A}", .ok(matches: false, finds: "0-0", groups: [])),
        ("(?m)^", "a\u{D}\u{A}b\u{B}c\u{C}d\u{A}", .ok(matches: false, finds: "0-0 3-3", groups: [])),
        ("(?m)^", "a\u{D}b\u{85}c\u{2028}d\u{2029}e", .ok(matches: false, finds: "0-0 2-2 4-4 6-6 8-8", groups: [])),
        ("(?m)^", "\u{D}\u{D}\u{A}", .ok(matches: false, finds: "0-0 1-1", groups: [])),
        ("^a", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("^a", "ba", .ok(matches: false, finds: "", groups: [])),
        ("^a", "b\u{A}a", .ok(matches: false, finds: "", groups: [])),
        ("(?m)^a$", "x\u{A}a\u{A}y", .ok(matches: false, finds: "2-3", groups: [])),
        ("(?m)^a$", "x\u{D}\u{A}a\u{D}\u{A}", .ok(matches: false, finds: "3-4", groups: [])),
        ("(?m)^a$", "x\u{B}a", .ok(matches: false, finds: "", groups: [])),
        ("(?d)a$", "a\u{A}", .ok(matches: false, finds: "0-1", groups: [])),
        ("(?d)a$", "a\u{D}", .ok(matches: false, finds: "", groups: [])),
        ("(?d)a$", "a\u{85}", .ok(matches: false, finds: "", groups: [])),
        ("(?dm)$", "a\u{A}b\u{D}c", .ok(matches: false, finds: "1-1 5-5", groups: [])),
        ("(?dm)^", "a\u{A}b\u{D}c\u{A}", .ok(matches: false, finds: "0-0 2-2", groups: [])),
        ("a\\Z", "a\u{A}", .ok(matches: false, finds: "0-1", groups: [])),
        ("a\\Z", "a\u{B}", .ok(matches: false, finds: "", groups: [])),
        ("a\\Z", "a\u{D}\u{A}", .ok(matches: false, finds: "0-1", groups: [])),
        ("a\\Z", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?d)a\\Z", "a\u{A}", .ok(matches: false, finds: "0-1", groups: [])),
        ("(?d)a\\Z", "a\u{D}", .ok(matches: false, finds: "", groups: [])),
        ("a\\z", "a\u{A}", .ok(matches: false, finds: "", groups: [])),
        ("a\\z", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\Aa", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\Aa", "ba", .ok(matches: false, finds: "", groups: [])),
        ("\\R", "\u{D}\u{A}", .ok(matches: true, finds: "0-2", groups: [])),
        ("\\R", "\u{B}\u{C}", .ok(matches: false, finds: "0-1 1-2", groups: [])),
        ("\\R", "\u{85}\u{2028}\u{2029}", .ok(matches: false, finds: "0-1 1-2 2-3", groups: [])),
        ("\\R", "\u{A}\u{D}", .ok(matches: false, finds: "0-1 1-2", groups: [])),
        ("\\R", "a", .ok(matches: false, finds: "", groups: [])),
        ("\\R\\n", "\u{D}\u{A}", .ok(matches: true, finds: "0-2", groups: [])),
        ("\\h", "\u{180E}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\h", "\u{A0}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\h", "\u{2007}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\h", "\u{1680}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\h", "\u{9}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\h", "\u{A}", .ok(matches: false, finds: "", groups: [])),
        ("\\h", "\u{205F}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\h", "\u{200B}", .ok(matches: false, finds: "", groups: [])),
        ("\\H", "\u{180E}", .ok(matches: false, finds: "", groups: [])),
        ("\\H", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\v", "\u{B}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\v", "\u{85}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\v", "\u{2028}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\v", "\u{9}", .ok(matches: false, finds: "", groups: [])),
        ("\\V", "\u{B}", .ok(matches: false, finds: "", groups: [])),
        ("\\V", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("[\\v-\\r]", "\u{B}", .ok(matches: true, finds: "0-1", groups: [])),
        ("[\\v-\\r]", "\u{C}", .ok(matches: true, finds: "0-1", groups: [])),
        ("[\\v-\\r]", "\u{A}", .ok(matches: false, finds: "", groups: [])),
        ("a**", "", .error("Dangling meta character '*'", 2)),
        ("a{2,1}", "", .error("Illegal repetition range", 5)),
        ("a{2147483648}", "", .error("Illegal repetition range", 11)),
        ("x{,3}", "", .error("Illegal repetition", 2)),
        ("x{", "", .error("Illegal repetition", 2)),
        ("x{1", "", .error("Unclosed counted closure", 3)),
        ("*a", "", .error("Dangling meta character '*'", 0)),
        ("+", "", .error("Dangling meta character '+'", 0)),
        ("?", "", .error("Dangling meta character '?'", 0)),
        ("a|*", "", .error("Dangling meta character '*'", 2)),
        ("(?q)a", "", .error("Unknown inline modifier", 2)),
        ("(?i", "", .error("Unknown inline modifier", 3)),
        ("(a", "", .error("Unclosed group", 2)),
        ("a)", "", .error("Unmatched closing ')'", 0)),
        ("\\", "", .error("Unescaped trailing backslash", 1)),
        ("\\q", "", .error("Illegal/unsupported escape sequence", 1)),
        ("\\y", "", .error("Illegal/unsupported escape sequence", 1)),
        ("\\E", "", .error("Illegal/unsupported escape sequence", 1)),
        ("\\0", "", .error("Illegal octal escape sequence", 2)),
        ("\\08", "", .error("Illegal octal escape sequence", 2)),
        ("\\x", "", .error("Illegal hexadecimal escape sequence", 2)),
        ("\\xg", "", .error("Illegal hexadecimal escape sequence", 2)),
        ("\\x{", "", .error("Illegal hexadecimal escape sequence", 2)),
        ("\\x{110000}", "", .error("Hexadecimal codepoint is too big", 8)),
        ("\\x{41", "", .error("Unclosed hexadecimal escape sequence", 5)),
        ("\\u12", "", .error("Illegal Unicode escape sequence", 4)),
        ("\\c", "", .error("Illegal control escape sequence", 1)),
        ("[a-\\d]", "", .error("Illegal character range", 4)),
        ("[z-a]", "", .error("Illegal character range", 3)),
        ("[]", "", .error("Unclosed character class", 1)),
        ("[^]", "", .error("Unclosed character class", 2)),
        ("[a", "", .error("Unclosed character class", 1)),
        ("[\\b]", "", .error("Illegal/unsupported escape sequence", 2)),
        ("\\k<n>(?<n>a)", "", .error("named capturing group <n> does not exist", 4)),
        ("(?<1n>a)", "", .error("capturing group name does not start with a Latin letter", 3)),
        ("(?<n>a)(?<n>b)", "", .error("Named capturing group <n> is already defined", 11)),
        ("(?<n", "", .error("named capturing group is missing trailing '>'", 4)),
        ("\\k", "", .error("\\k is not followed by '<' for named capturing group", 2)),
        ("\\kn", "", .error("\\k is not followed by '<' for named capturing group", 2)),
        ("\\p{XX}", "", .error("Unknown character property name {XX}", 5)),
        ("\\p{", "", .error("Unclosed character family", 3)),
        ("\\p{}", "", .error("Empty character family", 3)),
        ("\\p", "", .error("Unknown character property name {\u{0}}", 2)),
        ("\\p{gc=xx}", "", .error("Unknown Unicode property {name=<gc>, value=<xx>}", 8)),
        ("\\p{foo=bar}", "", .error("Unknown Unicode property {name=<foo>, value=<bar>}", 10)),
        ("(?$)", "", .error("Unknown group type", 2)),
        ("(?@)", "", .error("Unknown group type", 2)),
        ("(?-i-m)", "", .error("Unknown inline modifier", 4)),
        ("(?i-)a", "", .ok(matches: false, finds: "", groups: [])),
        ("a{1,2", "", .error("Unclosed counted closure", 5)),
        ("a{a}", "", .error("Illegal repetition", 2)),
        ("{1}", "", .ok(matches: true, finds: "0-0", groups: [])),
        ("{a}", "", .error("Illegal repetition", 1)),
        ("a{1}{2}", "", .ok(matches: false, finds: "", groups: [])),
        ("a*{2}", "", .ok(matches: true, finds: "0-0", groups: [])),
        ("[a&&]", "", .ok(matches: false, finds: "", groups: [])),
        ("[&&a]", "", .ok(matches: false, finds: "", groups: [])),
        ("[a&&&b]", "", .ok(matches: false, finds: "", groups: [])),
        ("[[a]&&[b]]", "", .ok(matches: false, finds: "", groups: [])),
        ("[&&]", "", .error("Bad class syntax", 2)),
        ("[a&&[b]&c]", "", .ok(matches: false, finds: "", groups: [])),
        ("[a&&b&&c]", "", .ok(matches: false, finds: "", groups: [])),
        ("[ab&&bc]", "", .ok(matches: false, finds: "", groups: [])),
        ("[^a[b]]", "", .ok(matches: false, finds: "", groups: [])),
        ("[a[^b]]", "", .ok(matches: false, finds: "", groups: [])),
        ("[a-c[x-z]]", "", .ok(matches: false, finds: "", groups: [])),
        ("[a-]", "", .ok(matches: false, finds: "", groups: [])),
        ("[-a]", "", .ok(matches: false, finds: "", groups: [])),
        ("[]a]", "", .ok(matches: false, finds: "", groups: [])),
        ("[^]a]", "", .ok(matches: false, finds: "", groups: [])),
        ("[a-[b]]", "", .ok(matches: false, finds: "", groups: [])),
        ("[\\d-z]", "", .ok(matches: false, finds: "", groups: [])),
        ("[a\\]]", "", .ok(matches: false, finds: "", groups: [])),
        ("[\\Q]\\E]", "", .ok(matches: false, finds: "", groups: [])),
        ("[\\Q^\\E]", "", .ok(matches: false, finds: "", groups: [])),
        ("\\Qa.b\\E", "", .ok(matches: false, finds: "", groups: [])),
        ("\\Qa.b", "", .ok(matches: false, finds: "", groups: [])),
        ("\\Q1\\E", "", .ok(matches: false, finds: "", groups: [])),
        ("\\Q\\d\\E", "", .ok(matches: false, finds: "", groups: [])),
        ("\\Q\\E", "", .ok(matches: true, finds: "0-0", groups: [])),
        ("a\\Q\\", "", .ok(matches: false, finds: "", groups: [])),
        ("x\\Q(\\E*", "", .ok(matches: false, finds: "", groups: [])),
        ("\\0101", "", .ok(matches: false, finds: "", groups: [])),
        ("\\0377", "", .ok(matches: false, finds: "", groups: [])),
        ("\\0400", "", .ok(matches: false, finds: "", groups: [])),
        ("\\x41", "", .ok(matches: false, finds: "", groups: [])),
        ("\\x{1F600}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\u0041", "", .ok(matches: false, finds: "", groups: [])),
        ("\\uD83D\\uDE00", "", .ok(matches: false, finds: "", groups: [])),
        ("\\cA", "", .ok(matches: false, finds: "", groups: [])),
        ("\\c@", "", .ok(matches: false, finds: "", groups: [])),
        ("\\e", "", .ok(matches: false, finds: "", groups: [])),
        ("\\a", "", .ok(matches: false, finds: "", groups: [])),
        ("\\t\\n\\r\\f", "", .ok(matches: false, finds: "", groups: [])),
        ("\\-\\.\\ \\#", "", .ok(matches: false, finds: "", groups: [])),
        ("a{0}", "", .ok(matches: true, finds: "0-0", groups: [])),
        ("a{0,1}?", "", .ok(matches: true, finds: "0-0", groups: [])),
        ("a{2,}+", "", .ok(matches: false, finds: "", groups: [])),
        ("a??", "", .ok(matches: true, finds: "0-0", groups: [])),
        ("a*+", "", .ok(matches: true, finds: "0-0", groups: [])),
        ("a++b", "", .ok(matches: false, finds: "", groups: [])),
        ("(?:)", "", .ok(matches: true, finds: "0-0", groups: [])),
        ("()", "", .ok(matches: true, finds: "0-0", groups: [""])),
        ("|", "", .ok(matches: true, finds: "0-0", groups: [])),
        ("a|", "", .ok(matches: true, finds: "0-0", groups: [])),
        ("|a", "", .ok(matches: true, finds: "0-0", groups: [])),
        ("(|a)", "", .ok(matches: true, finds: "0-0", groups: [""])),
        ("]", "", .ok(matches: false, finds: "", groups: [])),
        ("}", "", .ok(matches: false, finds: "", groups: [])),
        ("a}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\b{g}", "", .ok(matches: true, finds: "0-0", groups: [])),
        ("\\b{x}", "", .error("Illegal repetition", 3)),
        ("\\b{", "", .error("Illegal repetition", 3)),
        ("\\N{LATIN SMALL LETTER A}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\X", "", .ok(matches: false, finds: "", groups: [])),
        ("\\G", "", .ok(matches: true, finds: "0-0", groups: [])),
        ("(?x)a b", "", .ok(matches: false, finds: "", groups: [])),
        ("(?u)a", "", .ok(matches: false, finds: "", groups: [])),
        ("(?U)a", "", .ok(matches: false, finds: "", groups: [])),
        ("(?c)a", "", .ok(matches: false, finds: "", groups: [])),
        ("(?i)(a)\\1", "", .ok(matches: false, finds: "", groups: [])),
        ("\\1(a)", "", .ok(matches: false, finds: "", groups: [])),
        ("(a)\\2", "", .ok(matches: false, finds: "", groups: [])),
        ("(a)\\1", "", .ok(matches: false, finds: "", groups: [])),
        ("(a)\\11", "", .ok(matches: false, finds: "", groups: [])),
        ("(a)(b)(c)(d)(e)(f)(g)(h)(i)(j)\\10", "", .ok(matches: false, finds: "", groups: [])),
        ("(?<n>a)\\k<n>", "", .ok(matches: false, finds: "", groups: [])),
        ("(?<n1>a)", "", .ok(matches: false, finds: "", groups: [])),
        ("(?>a|ab)c", "", .ok(matches: false, finds: "", groups: [])),
        ("(?=a)*", "", .ok(matches: true, finds: "0-0", groups: [])),
        ("^*", "", .ok(matches: true, finds: "0-0", groups: [])),
        ("\\b+", "", .ok(matches: false, finds: "", groups: [])),
        ("$?", "", .ok(matches: true, finds: "0-0", groups: [])),
        ("(?<=a+)b", "", .ok(matches: false, finds: "", groups: [])),
        ("(?<=a{1,3})b", "", .ok(matches: false, finds: "", groups: [])),
        ("(?<!a|bc)d", "", .ok(matches: false, finds: "", groups: [])),
        ("(?<=(a)\\1)b", "", .error("Look-behind group does not have an obvious maximum length", 8)),
        ("(?i-i)a", "", .ok(matches: false, finds: "", groups: [])),
        ("(?-)a", "", .ok(matches: false, finds: "", groups: [])),
        ("(?)a", "", .ok(matches: false, finds: "", groups: [])),
        ("a{16777215}", "", .ok(matches: false, finds: "", groups: [])),
        ("a{16777216}", "", .ok(matches: false, finds: "", groups: [])),
        ("a{0,16777216}", "", .ok(matches: true, finds: "0-0", groups: [])),
        ("a{16777216,}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{L}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\pL", "", .ok(matches: false, finds: "", groups: [])),
        ("\\PL", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{IsL}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Lu}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{javaLowerCase}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{IsLatin}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{InGreek}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Lower}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Alpha}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{IsAlphabetic}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{IsAlpha}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{sc=Latin}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{gc=Lu}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{general_category=L}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{LC}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{LD}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{L1}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{all}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{ASCII}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Punct}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Graph}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Print}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Blank}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Cntrl}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{XDigit}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Space}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Digit}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Alnum}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Upper}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Cn}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Zs}", "", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Sc}", "", .ok(matches: false, finds: "", groups: [])),
        ("[\\p{L}&&[^a-z]]", "", .ok(matches: false, finds: "", groups: [])),
        ("[^\\p{L}]", "", .ok(matches: false, finds: "", groups: [])),
        ("[\\P{L}a]", "", .ok(matches: false, finds: "", groups: [])),
        ("\u{0}", "", .ok(matches: false, finds: "", groups: [])),
        ("a**", "a", .error("Dangling meta character '*'", 2)),
        ("[a&&]", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("[a&&]", "b", .ok(matches: false, finds: "", groups: [])),
        ("[&&a]", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("[a&&&b]", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("[a&&&b]", "&", .ok(matches: true, finds: "0-1", groups: [])),
        ("[a&&&b]", "b", .ok(matches: true, finds: "0-1", groups: [])),
        ("[[a]&&[b]]", "a", .ok(matches: false, finds: "", groups: [])),
        ("[a&&[b]&c]", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("[a&&[b]&c]", "b", .ok(matches: false, finds: "", groups: [])),
        ("[a&&[b]&c]", "c", .ok(matches: true, finds: "0-1", groups: [])),
        ("[a&&[b]&c]", "&", .ok(matches: true, finds: "0-1", groups: [])),
        ("[a&&b&&c]", "a", .ok(matches: false, finds: "", groups: [])),
        ("[ab&&bc]", "a", .ok(matches: false, finds: "", groups: [])),
        ("[ab&&bc]", "b", .ok(matches: true, finds: "0-1", groups: [])),
        ("[ab&&bc]", "c", .ok(matches: false, finds: "", groups: [])),
        ("[^a[b]]", "a", .ok(matches: false, finds: "", groups: [])),
        ("[^a[b]]", "b", .ok(matches: false, finds: "", groups: [])),
        ("[^a[b]]", "c", .ok(matches: true, finds: "0-1", groups: [])),
        ("[a[^b]]", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("[a[^b]]", "b", .ok(matches: false, finds: "", groups: [])),
        ("[a[^b]]", "c", .ok(matches: true, finds: "0-1", groups: [])),
        ("[a-z&&[^aeiou]]", "e", .ok(matches: false, finds: "", groups: [])),
        ("[a-z&&[^aeiou]]", "b", .ok(matches: true, finds: "0-1", groups: [])),
        ("[a-c&&b-d]", "a", .ok(matches: false, finds: "", groups: [])),
        ("[a-c&&b-d]", "b", .ok(matches: true, finds: "0-1", groups: [])),
        ("[a-c&&b-d]", "d", .ok(matches: false, finds: "", groups: [])),
        ("[]a]", "]", .ok(matches: true, finds: "0-1", groups: [])),
        ("[]a]", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("[^]a]", "b", .ok(matches: true, finds: "0-1", groups: [])),
        ("[^]a]", "]", .ok(matches: false, finds: "", groups: [])),
        ("[a-]", "-", .ok(matches: true, finds: "0-1", groups: [])),
        ("[a-]", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("[-a]", "-", .ok(matches: true, finds: "0-1", groups: [])),
        ("[a-[b]]", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("[a-[b]]", "-", .ok(matches: true, finds: "0-1", groups: [])),
        ("[a-[b]]", "b", .ok(matches: true, finds: "0-1", groups: [])),
        ("[a-[b]]", "c", .ok(matches: false, finds: "", groups: [])),
        ("[\\d-z]", "-", .ok(matches: true, finds: "0-1", groups: [])),
        ("[\\d-z]", "5", .ok(matches: true, finds: "0-1", groups: [])),
        ("[\\d-z]", "z", .ok(matches: true, finds: "0-1", groups: [])),
        ("[\\d-z]", "a", .ok(matches: false, finds: "", groups: [])),
        ("[a\\]]", "]", .ok(matches: true, finds: "0-1", groups: [])),
        ("[\\Q]\\E]", "]", .ok(matches: true, finds: "0-1", groups: [])),
        ("[\\Q^\\E]", "^", .ok(matches: true, finds: "0-1", groups: [])),
        ("[\\Q^\\E]", "a", .ok(matches: false, finds: "", groups: [])),
        ("[\\w&&[^\\d]]", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("[\\w&&[^\\d]]", "5", .ok(matches: false, finds: "", groups: [])),
        ("[\\w&&[^\\d]]", "_", .ok(matches: true, finds: "0-1", groups: [])),
        ("[^\\s]", " ", .ok(matches: false, finds: "", groups: [])),
        ("[^\\s]", "\u{A0}", .ok(matches: true, finds: "0-1", groups: [])),
        ("[\\S\\s]", "\u{A}", .ok(matches: true, finds: "0-1", groups: [])),
        ("[\\S\\s]", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("[\\p{L}&&[^a-z]]", "a", .ok(matches: false, finds: "", groups: [])),
        ("[\\p{L}&&[^a-z]]", "A", .ok(matches: true, finds: "0-1", groups: [])),
        ("[\\p{L}&&[^a-z]]", "\u{E9}", .ok(matches: true, finds: "0-1", groups: [])),
        ("[^\\p{L}]", "a", .ok(matches: false, finds: "", groups: [])),
        ("[^\\p{L}]", "1", .ok(matches: true, finds: "0-1", groups: [])),
        ("[\\P{L}a]", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("[\\P{L}a]", "b", .ok(matches: false, finds: "", groups: [])),
        ("[\\P{L}a]", "1", .ok(matches: true, finds: "0-1", groups: [])),
        ("[\\x{1F600}-\\x{1F64F}]", "\u{1F600}", .ok(matches: true, finds: "0-2", groups: [])),
        ("[\\x{1F600}-\\x{1F64F}]", "\u{1F650}", .ok(matches: false, finds: "", groups: [])),
        ("[^a]", "\u{1F600}", .ok(matches: true, finds: "0-2", groups: [])),
        ("[A-Z]", "A", .ok(matches: true, finds: "0-1", groups: [])),
        ("[A-Z]", "a", .ok(matches: false, finds: "", groups: [])),
        ("[\\0101]", "A", .ok(matches: true, finds: "0-1", groups: [])),
        ("[\\cA]", "\u{1}", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?i)k", "\u{212A}", .ok(matches: false, finds: "", groups: [])),
        ("(?i)k", "K", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?i)k", "k", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?i)s", "\u{17F}", .ok(matches: false, finds: "", groups: [])),
        ("(?i)s", "S", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?i)\u{10D}", "\u{10C}", .ok(matches: false, finds: "", groups: [])),
        ("(?i)\u{10D}", "\u{10D}", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?i)ss", "\u{DF}", .ok(matches: false, finds: "", groups: [])),
        ("(?i)ss", "SS", .ok(matches: true, finds: "0-2", groups: [])),
        ("(?i)[a-z]", "K", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?i)[a-z]", "\u{E9}", .ok(matches: false, finds: "", groups: [])),
        ("(?i)[a-z]", "\u{212A}", .ok(matches: false, finds: "", groups: [])),
        ("(?i)[k]", "\u{212A}", .ok(matches: false, finds: "", groups: [])),
        ("(?i)[k]", "K", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?i)[^a]", "A", .ok(matches: false, finds: "", groups: [])),
        ("(?i)[^a]", "b", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?i)[Z-a]", "z", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?i)[Z-a]", "A", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?i)[Z-a]", "_", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?i)[Z-a]", "y", .ok(matches: false, finds: "", groups: [])),
        ("(?i)[Z-a]", "B", .ok(matches: false, finds: "", groups: [])),
        ("(?i)[\u{E0}-\u{17E}]", "\u{C0}", .ok(matches: false, finds: "", groups: [])),
        ("(?i)[\u{E0}-\u{17E}]", "\u{E0}", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?i)\\x41", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?i)\\Qab\\E", "AB", .ok(matches: true, finds: "0-2", groups: [])),
        ("(?i)a(?-i)b", "AB", .ok(matches: false, finds: "", groups: [])),
        ("(?i)a(?-i)b", "Ab", .ok(matches: true, finds: "0-2", groups: [])),
        ("(?i)a(?-i)b", "ab", .ok(matches: true, finds: "0-2", groups: [])),
        ("(?i:a)b", "Ab", .ok(matches: true, finds: "0-2", groups: [])),
        ("(?i:a)b", "AB", .ok(matches: false, finds: "", groups: [])),
        ("(a(?i)b)c", "aBc", .ok(matches: true, finds: "0-3", groups: ["aB"])),
        ("(a(?i)b)c", "aBC", .ok(matches: false, finds: "", groups: [])),
        ("a(?i)b|c", "C", .ok(matches: true, finds: "0-1", groups: [])),
        ("a(?i)b|c", "aB", .ok(matches: true, finds: "0-2", groups: [])),
        ("(?i)[@-\\[]", "`", .ok(matches: false, finds: "", groups: [])),
        ("(?i)[@-\\[]", "{", .ok(matches: false, finds: "", groups: [])),
        ("(?i)[@-\\[]", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?i)[@-\\[]", "@", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?i)\\p{Lower}", "A", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?i)\\p{Lower}", "\u{E9}", .ok(matches: false, finds: "", groups: [])),
        ("(?i)\\p{Upper}", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?i)\\p{Lu}", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?i)\\p{Lu}", "\u{1C5}", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?i)\\p{Lu}", "1", .ok(matches: false, finds: "", groups: [])),
        ("(?i)\\p{Ll}", "A", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?i)\\p{Lt}", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?i)(?<=A)b", "aB", .ok(matches: false, finds: "1-2", groups: [])),
        ("(a)\\1", "aa", .ok(matches: true, finds: "0-2", groups: ["a"])),
        ("(a)\\1", "ab", .ok(matches: false, finds: "", groups: [])),
        ("(a)\\11", "aa1", .ok(matches: true, finds: "0-3", groups: ["a"])),
        ("\\1(a)", "a", .ok(matches: false, finds: "", groups: [])),
        ("(a)\\2", "a", .ok(matches: false, finds: "", groups: [])),
        ("(a)?\\1b", "b", .ok(matches: false, finds: "", groups: [])),
        ("(a)?\\1b", "aab", .ok(matches: true, finds: "0-3", groups: ["a"])),
        ("(?<n>a)\\k<n>", "aa", .ok(matches: true, finds: "0-2", groups: ["a"])),
        ("(a)(b)(c)(d)(e)(f)(g)(h)(i)(j)\\10", "abcdefghijj", .ok(matches: true, finds: "0-11", groups: ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"])),
        ("(a)(b)(c)(d)(e)(f)(g)(h)(i)(j)\\10", "abcdefghija0", .ok(matches: false, finds: "", groups: [])),
        ("(?>a|ab)c", "abc", .ok(matches: false, finds: "", groups: [])),
        ("(?>a|ab)c", "ac", .ok(matches: true, finds: "0-2", groups: [])),
        ("(?=a)*", "a", .ok(matches: false, finds: "0-0 1-1", groups: [])),
        ("^*", "a", .ok(matches: false, finds: "0-0 1-1", groups: [])),
        ("\\b+", "a", .ok(matches: false, finds: "0-0 1-1", groups: [])),
        ("$?", "a", .ok(matches: false, finds: "0-0 1-1", groups: [])),
        ("(?<=a+)b", "ab", .ok(matches: false, finds: "1-2", groups: [])),
        ("(?<=a{1,3})b", "ab", .ok(matches: false, finds: "1-2", groups: [])),
        ("(?<=a{1,3})b", "aaaab", .ok(matches: false, finds: "4-5", groups: [])),
        ("(?<!a|bc)d", "d", .ok(matches: true, finds: "0-1", groups: [])),
        ("(?<!a|bc)d", "ad", .ok(matches: false, finds: "", groups: [])),
        ("(?<!a|bc)d", "bcd", .ok(matches: false, finds: "", groups: [])),
        ("a{1}{2}", "aa", .ok(matches: false, finds: "0-1 1-2", groups: [])),
        ("a*{2}", "aa", .ok(matches: true, finds: "0-2 2-2", groups: [])),
        ("{1}", "a", .ok(matches: false, finds: "0-0 1-1", groups: [])),
        ("a{0}", "a", .ok(matches: false, finds: "0-0 1-1", groups: [])),
        ("a{0,1}?", "a", .ok(matches: true, finds: "0-0 1-1", groups: [])),
        ("a{2,}+", "aaa", .ok(matches: true, finds: "0-3", groups: [])),
        ("a??", "a", .ok(matches: true, finds: "0-0 1-1", groups: [])),
        ("a*+a", "aa", .ok(matches: false, finds: "", groups: [])),
        ("a++b", "aab", .ok(matches: true, finds: "0-3", groups: [])),
        ("(?:)", "ab", .ok(matches: false, finds: "0-0 1-1 2-2", groups: [])),
        ("()", "a", .ok(matches: false, finds: "0-0 1-1", groups: [""])),
        ("|", "ab", .ok(matches: false, finds: "0-0 1-1 2-2", groups: [])),
        ("a|", "ab", .ok(matches: false, finds: "0-1 1-1 2-2", groups: [])),
        ("|a", "a", .ok(matches: true, finds: "0-0 1-1", groups: [])),
        ("(|a)", "a", .ok(matches: true, finds: "0-0 1-1", groups: [""])),
        ("", "", .ok(matches: true, finds: "0-0", groups: [])),
        ("", "abc", .ok(matches: false, finds: "0-0 1-1 2-2 3-3", groups: [])),
        ("", "\u{1F600}", .ok(matches: false, finds: "0-0 1-1 2-2", groups: [])),
        ("x*", "axb", .ok(matches: false, finds: "0-0 1-2 2-2 3-3", groups: [])),
        ("x*", "\u{1F600}", .ok(matches: false, finds: "0-0 1-1 2-2", groups: [])),
        ("x*", "", .ok(matches: true, finds: "0-0", groups: [])),
        ("(\\d{1,2})(\\d{2})/(\\d{1,4})", "1200/30", .ok(matches: true, finds: "0-7", groups: ["12", "00", "30"])),
        ("(\\d{1,2})(\\d{2})/(\\d{1,4})", "900/1200", .ok(matches: true, finds: "0-8", groups: ["9", "00", "1200"])),
        ("(\\d{1,2})(\\d{2})/(\\d{1,4})", "\u{663}00/1", .ok(matches: false, finds: "", groups: [])),
        ("]", "]", .ok(matches: true, finds: "0-1", groups: [])),
        ("}", "}", .ok(matches: true, finds: "0-1", groups: [])),
        ("a}", "a}", .ok(matches: true, finds: "0-2", groups: [])),
        ("\\b{x}", "b", .error("Illegal repetition", 3)),
        ("\\-\\.\\ \\#", "-. #", .ok(matches: true, finds: "0-4", groups: [])),
        ("\\t\\n\\r\\f", "\u{9}\u{A}\u{D}\u{C}", .ok(matches: true, finds: "0-4", groups: [])),
        ("\\e\\a", "\u{1B}\u{7}", .ok(matches: true, finds: "0-2", groups: [])),
        ("\\cA\\c@", "\u{1}\u{0}", .ok(matches: true, finds: "0-2", groups: [])),
        ("\\0101\\0377\\0400", "A\u{FF} 0", .ok(matches: true, finds: "0-4", groups: [])),
        ("\\x41\\x{1F600}", "A\u{1F600}", .ok(matches: true, finds: "0-3", groups: [])),
        ("A\u{1F600}", "A\u{1F600}", .ok(matches: true, finds: "0-3", groups: [])),
        ("\\Qa.b\\E", "a.b", .ok(matches: true, finds: "0-3", groups: [])),
        ("\\Qa.b\\E", "axb", .ok(matches: false, finds: "", groups: [])),
        ("\\Qa.b", "a.b", .ok(matches: true, finds: "0-3", groups: [])),
        ("\\Q1\\E", "1", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\Q\\d\\E", "\\d", .ok(matches: true, finds: "0-2", groups: [])),
        ("\\Q\\E", "", .ok(matches: true, finds: "0-0", groups: [])),
        ("x\\Q(\\E*", "x((", .ok(matches: true, finds: "0-3", groups: [])),
        ("x\\Q(\\E*", "x", .ok(matches: true, finds: "0-1", groups: [])),
        ("\u{0}", "\u{0}", .ok(matches: true, finds: "0-1", groups: [])),
        ("a{16777215}", "a", .ok(matches: false, finds: "", groups: [])),
        ("\\p{L}", "\u{E9}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{L}", "1", .ok(matches: false, finds: "", groups: [])),
        ("\\p{L}", "\u{2EBF0}", .ok(matches: false, finds: "", groups: [])),
        ("\\pL", "\u{E9}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\PL", "\u{E9}", .ok(matches: false, finds: "", groups: [])),
        ("\\PL", "1", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{IsL}", "\u{E9}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{Lu}", "\u{C9}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{Lu}", "\u{E9}", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Lower}", "\u{E9}", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Lower}", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{Alpha}", "\u{E9}", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Alpha}", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{gc=Lu}", "A", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{general_category=L}", "a", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{LC}", "\u{1C5}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{LC}", "\u{2B0}", .ok(matches: false, finds: "", groups: [])),
        ("\\p{LD}", "\u{663}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{LD}", "\u{2B0}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{L1}", "\u{FF}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{L1}", "\u{100}", .ok(matches: false, finds: "", groups: [])),
        ("\\p{all}", "\u{A}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{ASCII}", "\u{7F}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{ASCII}", "\u{80}", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Punct}", "!", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{Punct}", "\u{A1}", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Graph}", "~", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{Graph}", " ", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Print}", " ", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{Print}", "\u{7F}", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Blank}", "\u{9}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{Blank}", "\u{A0}", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Cntrl}", "\u{7F}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{Cntrl}", "\u{85}", .ok(matches: false, finds: "", groups: [])),
        ("\\p{XDigit}", "f", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{XDigit}", "g", .ok(matches: false, finds: "", groups: [])),
        ("\\p{XDigit}", "\u{FF10}", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Space}", "\u{B}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{Space}", "\u{A0}", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Digit}", "5", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{Digit}", "\u{663}", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Alnum}", "z", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{Alnum}", "\u{E9}", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Upper}", "Z", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{Upper}", "\u{C9}", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Cn}", "\u{378}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{Cn}", "a", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Zs}", "\u{A0}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{Zs}", "\u{9}", .ok(matches: false, finds: "", groups: [])),
        ("\\p{Sc}", "$", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{Sc}", "\u{20AC}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{Mn}", "\u{301}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{Nd}", "\u{663}", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{IsLu}", "A", .ok(matches: true, finds: "0-1", groups: [])),
        ("\\p{Isgc}", "A", .error("Unknown character property name {Isgc}", 7)),
        ("\\d+", "007", .ok(matches: true, finds: "0-3", groups: [])),
        ("\\d+", " 7", .ok(matches: false, finds: "1-2", groups: [])),
        ("\\d+", "1\u{A0}", .ok(matches: false, finds: "0-1", groups: [])),
        ("^([1-9]|[1-3][0-9]|40)$", "40", .ok(matches: true, finds: "0-2", groups: ["40"])),
        ("^([1-9]|[1-3][0-9]|40)$", "41", .ok(matches: false, finds: "", groups: [])),
        ("^([1-9]|[1-3][0-9]|40)$", "4\u{A}", .ok(matches: false, finds: "0-1", groups: ["4"])),
        ("^([1-9]|[1-3][0-9]|40)$", "05", .ok(matches: false, finds: "", groups: [])),
        ("^(?=.*[A-Za-z])[A-Za-z0-9/]{1,12}$", "DARC", .ok(matches: true, finds: "0-4", groups: [])),
        ("^(?=.*[A-Za-z])[A-Za-z0-9/]{1,12}$", "123", .ok(matches: false, finds: "", groups: [])),
        ("^(?=.*[A-Za-z])[A-Za-z0-9/]{1,12}$", "R1\u{A}", .ok(matches: false, finds: "0-2", groups: [])),
        ("^[A-Z]{2}$", "AB", .ok(matches: true, finds: "0-2", groups: [])),
        ("^[A-Z]{2}$", "ab", .ok(matches: false, finds: "", groups: [])),
        ("^[A-Z]{2}$", "AB\u{A}", .ok(matches: false, finds: "0-2", groups: [])),
        ("^[A-R]{2}[0-9]{2}([A-X]{2})?$", "JO70", .ok(matches: true, finds: "0-4", groups: [nil])),
        ("^[A-R]{2}[0-9]{2}([A-X]{2})?$", "JO70FC", .ok(matches: true, finds: "0-6", groups: ["FC"])),
        ("^[A-R]{2}[0-9]{2}([A-X]{2})?$", "JO7", .ok(matches: false, finds: "", groups: [])),
        ("^([1-9]|[1-6][0-9]|7[0-5])$", "75", .ok(matches: true, finds: "0-2", groups: ["75"])),
        ("^([1-9]|[1-6][0-9]|7[0-5])$", "76", .ok(matches: false, finds: "", groups: [])),
        ("^[A-Ra-r]{2}[0-9]{2}[A-Xa-x]{2}$", "jo70fc", .ok(matches: true, finds: "0-6", groups: [])),
        ("^[A-Ra-r]{2}[0-9]{2}[A-Xa-x]{2}$", "JO70FC\u{D}\u{A}", .ok(matches: false, finds: "0-6", groups: [])),
        ("[a-z0-9][a-z0-9_-]*", "cq-ww", .ok(matches: true, finds: "0-5", groups: [])),
        ("[a-z0-9][a-z0-9_-]*", "Cq", .ok(matches: false, finds: "1-2", groups: [])),
        ("[a-z0-9][a-z0-9_-]*", "_a", .ok(matches: false, finds: "1-2", groups: [])),
        ("[A-Z0-9/-]{1,10}", "AB/1", .ok(matches: true, finds: "0-4", groups: [])),
        ("[A-Z0-9/-]{1,10}", "ABCDEFGHIJK", .ok(matches: false, finds: "0-10 10-11", groups: [])),
        ("[A-Z0-9/-]{1,10}", "\u{C1}", .ok(matches: false, finds: "", groups: [])),
        ("[a-z0-9_]+", "abc_1", .ok(matches: true, finds: "0-5", groups: [])),
        ("[a-z0-9_]+", "ab-c", .ok(matches: false, finds: "0-2 3-4", groups: [])),
        ("(?m)^id:\\s*.*$", "id: x", .ok(matches: true, finds: "0-5", groups: [])),
        ("(?m)^id:\\s*.*$", "a: 1\u{A}id: x\u{A}b: 2", .ok(matches: false, finds: "5-10", groups: [])),
        ("(?m)^id:\\s*.*$", "id:\u{A}\u{A}name: y", .ok(matches: true, finds: "0-12", groups: [])),
        ("(?m)^id:\\s*.*$", "id: x\u{D}\u{A}", .ok(matches: false, finds: "0-5", groups: [])),
        ("(?m)^id:\\s*.*$", "id:\u{B}x\u{85}y", .ok(matches: false, finds: "0-5", groups: [])),
        ("\\s*[,;\\t]\\s*", "AB ; Name", .ok(matches: false, finds: "2-5", groups: [])),
        ("\\s*[,;\\t]\\s*", "AB\u{A0},x", .ok(matches: false, finds: "3-4", groups: [])),
        ("\\s+", "a\u{A0}b", .ok(matches: false, finds: "", groups: [])),
        ("\\s+", "a \u{B}b", .ok(matches: false, finds: "1-3", groups: [])),
        ("[1-5][1-9][1-9]?", "599", .ok(matches: true, finds: "0-3", groups: [])),
        ("[A-R]{2}[0-9]{2}([A-X]{2})?", "JO70", .ok(matches: true, finds: "0-4", groups: [nil])),
        ("[A-Z]{2}-?\\d{1,3}", "EU-123", .ok(matches: true, finds: "0-6", groups: [])),
        ("[A-Z]{2}-?\\d{1,3}", "EU\u{663}", .ok(matches: false, finds: "", groups: [])),
        (".*[A-Z].*", "a\u{A}B", .ok(matches: false, finds: "2-3", groups: [])),
        (".*[A-Z].*", "aB", .ok(matches: true, finds: "0-2", groups: [])),
        ("[A-Z0-9/\\-]{1,10}", "A-1", .ok(matches: true, finds: "0-3", groups: [])),
        (".*\\d.*", "a\u{663}", .ok(matches: false, finds: "", groups: [])),
        (".*\\d.*", "a1", .ok(matches: true, finds: "0-2", groups: [])),
    ]

    static let splitTable: [(pattern: String, input: String, limit: Int, result: [String])] = [
        (",", "a,,b,,", 0, ["a", "", "b"]),
        (",", "a,,b,,", 1, ["a,,b,,"]),
        (",", "a,,b,,", 2, ["a", ",b,,"]),
        (",", "a,,b,,", 3, ["a", "", "b,,"]),
        (",", "a,,b,,", -1, ["a", "", "b", "", ""]),
        (",", "", 0, [""]),
        (",", "", 1, [""]),
        (",", "", 2, [""]),
        (",", "", 3, [""]),
        (",", "", -1, [""]),
        (",", ",", 0, []),
        (",", ",", 1, [","]),
        (",", ",", 2, ["", ""]),
        (",", ",", 3, ["", ""]),
        (",", ",", -1, ["", ""]),
        (",", ",a", 0, ["", "a"]),
        (",", ",a", 1, [",a"]),
        (",", ",a", 2, ["", "a"]),
        (",", ",a", 3, ["", "a"]),
        (",", ",a", -1, ["", "a"]),
        (",", "a", 0, ["a"]),
        (",", "a", 1, ["a"]),
        (",", "a", 2, ["a"]),
        (",", "a", 3, ["a"]),
        (",", "a", -1, ["a"]),
        (",", ",,", 0, []),
        (",", ",,", 1, [",,"]),
        (",", ",,", 2, ["", ","]),
        (",", ",,", 3, ["", "", ""]),
        (",", ",,", -1, ["", "", ""]),
        ("(?=\\d)", "a1b2c", 0, ["a", "1b", "2c"]),
        ("(?=\\d)", "a1b2c", 2, ["a", "1b2c"]),
        ("(?=\\d)", "a1b2c", -1, ["a", "1b", "2c"]),
        ("", "abc", 0, ["a", "b", "c"]),
        ("", "abc", 2, ["a", "bc"]),
        ("", "abc", -1, ["a", "b", "c", ""]),
        ("x*", "abc", 0, ["a", "b", "c"]),
        ("x*", "abc", 2, ["a", "bc"]),
        ("x*", "abc", -1, ["a", "b", "c", ""]),
        ("x*", "axb", 0, ["a", "", "b"]),
        ("x*", "axb", 2, ["a", "b"]),
        ("x*", "axb", -1, ["a", "", "b", ""]),
        ("x*", "", 0, [""]),
        ("\\d", "1a", 0, ["", "a"]),
        ("\\d", "1a", 2, ["", "a"]),
        ("\\d", "1a", -1, ["", "a"]),
        ("\\s+", "a b  c", 0, ["a", "b", "c"]),
        ("\\s+", "a b  c", 2, ["a", "b  c"]),
        ("\\s+", "a b  c", -1, ["a", "b", "c"]),
        ("\\s+", " a b ", 0, ["", "a", "b"]),
        ("\\s+", " a b ", -1, ["", "a", "b", ""]),
        ("\\s*[,;\\t]\\s*", "AB ; Name, x", 0, ["AB", "Name", "x"]),
        ("\\s*[,;\\t]\\s*", "AB ; Name, x", 2, ["AB", "Name, x"]),
        ("\\s*[,;\\t]\\s*", "AB", 2, ["AB"]),
        ("\\s+", "AB", 2, ["AB"]),
        ("\\s+", "\u{A0}a", 0, ["\u{A0}a"]),
        ("\\s+", "AB\u{9}Name", 2, ["AB", "Name"]),
        ("\\s*[,;\\t]\\s*", "AB\u{9}Name", 2, ["AB", "Name"]),
        ("^", "ab", 0, ["ab"]),
        ("(?m)^", "a\u{A}b", 0, ["a\u{A}", "b"]),
        ("\\b", "ab cd", 0, ["ab", " ", "cd"]),
        ("\\b", "ab cd", -1, ["ab", " ", "cd", ""]),
        ("a", "aaa", 0, []),
        ("a", "aaa", -1, ["", "", "", ""]),
        ("a", "aaa", 2, ["", "aa"]),
        ("", "", 0, [""]),
        (",", "a,b,c", -5, ["a", "b", "c"]),
    ]

    static let replaceFirstTable: [(pattern: String, input: String, replacement: String, result: String)] = [
        ("(?m)^id:\\s*.*$", "id: old\u{A}name: x", "id: new", "id: new\u{A}name: x"),
        ("(?m)^id:\\s*.*$", "name: x\u{A}id: old\u{A}", "id: $1\\\\x", "name: x\u{A}id: $1\\\\x\u{A}"),
        ("(?m)^id:\\s*.*$", "id:\u{A}\u{A}name: y", "id: n", "id: n"),
        ("(?m)^id:\\s*.*$", "id: n\u{D}\u{A}name: y", "id: m", "id: m\u{D}\u{A}name: y"),
        ("(?m)^id:\\s*.*$", "name: y", "id: m", "name: y"),
        ("a", "bab", "$0", "b$0b"),
        ("", "ab", "X", "Xab"),
        ("x*", "\u{1F600}", "-", "-\u{1F600}"),
    ]
}
