import Testing
@testable import MCLCore

/// Tests of the domain type `DxccEntity` and the error type `DxccError`.
///
/// The Java `DxccEntity` is a `record`, so equality, `hashCode` and the three constructors
/// are generated by the language. Behaviour of the constructors and equality (esp. for `NaN`) is measured on
/// a running Java v1.1.1; pinned here.
@Suite struct DxccEntityTests {

    // MARK: constructors

    @Test func fullInitKeepsBothNumbersApart() {
        let e = DxccEntity(entityCode: 42, name: "Test", countryCode: "TT", continents: ["EU"],
                           cq: [15], itu: [28], lat: 50.0, lon: 14.0, primaryPrefix: "OK", adifDxcc: 503)
        #expect(e.entityCode == 42)
        #expect(e.adifDxcc == 503)
        #expect(e.primaryPrefix == "OK")
    }

    /// Constructor without `adifDxcc`: Java measurement `C9 primaryPrefix=OK adif=7`.
    @Test func initWithoutAdifDxccCopiesEntityCode() {
        let e = DxccEntity(entityCode: 7, name: "N", countryCode: "NN", continents: ["EU"],
                           cq: [1], itu: [1], lat: 1.0, lon: 2.0, primaryPrefix: "OK")
        #expect(e.adifDxcc == 7)
        #expect(e.primaryPrefix == "OK")
    }

    /// Constructor without prefix: Java measurement `C8 primaryPrefix=NN adif=7`
    /// — the prefix is taken from `countryCode`.
    @Test func initWithoutPrefixUsesCountryCode() {
        let e = DxccEntity(entityCode: 7, name: "N", countryCode: "NN", continents: ["EU"],
                           cq: [1], itu: [1], lat: 1.0, lon: 2.0)
        #expect(e.primaryPrefix == "NN")
        #expect(e.adifDxcc == 7)
    }

    // MARK: primaryContinent

    @Test func primaryContinentIsNilForMissingOrEmptyList() {
        let withoutList = DxccEntity(entityCode: 1, name: "n", countryCode: "c", continents: nil,
                                    cq: nil, itu: nil, lat: 0, lon: 0)
        let blankEntity = DxccEntity(entityCode: 1, name: "n", countryCode: "c", continents: [],
                                 cq: nil, itu: nil, lat: 0, lon: 0)
        #expect(withoutList.primaryContinent == nil)
        #expect(blankEntity.primaryContinent == nil)
    }

    @Test func primaryContinentIsFirstOfList() {
        let e = DxccEntity(entityCode: 1, name: "n", countryCode: "c", continents: ["EU", "AS"],
                           cq: nil, itu: nil, lat: 0, lon: 0)
        #expect(e.primaryContinent == "EU")
    }

    // MARK: hasLatLon

    @Test func hasLatLonRequiresBothCoordinates() {
        let nan = DxccEntity(entityCode: 1, name: "X", countryCode: "XX", continents: [],
                             cq: [], itu: [], lat: .nan, lon: .nan)
        let zero = DxccEntity(entityCode: 1, name: "X", countryCode: "XX", continents: [],
                              cq: [], itu: [], lat: 0.0, lon: 0.0)
        let half = DxccEntity(entityCode: 1, name: "X", countryCode: "XX", continents: [],
                               cq: [], itu: [], lat: 50.0, lon: .nan)
        #expect(nan.hasLatLon == false)
        #expect(zero.hasLatLon == true)
        #expect(half.hasLatLon == false)
    }

    // MARK: equality (Java record: Double.compare, not ==)

    /// Java measurement `EQ[NaN==NaN] true`: the record compares `double` via
    /// `Double.compare`, so two unknown coordinates are equal. Swift's
    /// `Double.==` would say `false`, hence the type has its own `==`.
    @Test func entitiesWithUnknownCoordinatesAreEqual() {
        let a = DxccEntity(entityCode: 1, name: "X", countryCode: "XX", continents: ["EU"],
                           cq: [15], itu: [28], lat: .nan, lon: .nan, primaryPrefix: "OK")
        let b = DxccEntity(entityCode: 1, name: "X", countryCode: "XX", continents: ["EU"],
                           cq: [15], itu: [28], lat: .nan, lon: .nan, primaryPrefix: "OK")
        #expect(a == b)
    }

    /// Java measurement `EQ[0.0==-0.0] false` — `Double.compare` distinguishes the sign of zero.
    @Test func positiveAndNegativeZeroAreDifferent() {
        let a = DxccEntity(entityCode: 1, name: "X", countryCode: "XX", continents: [],
                           cq: [], itu: [], lat: 0.0, lon: 0.0, primaryPrefix: "OK")
        let b = DxccEntity(entityCode: 1, name: "X", countryCode: "XX", continents: [],
                           cq: [], itu: [], lat: -0.0, lon: 0.0, primaryPrefix: "OK")
        #expect(a != b)
    }

    @Test func differentFieldsMakeEntitiesDifferent() {
        let base = DxccEntity(entityCode: 1, name: "X", countryCode: "XX", continents: ["EU"],
                                cq: [15], itu: [28], lat: 1.0, lon: 2.0, primaryPrefix: "OK", adifDxcc: 1)
        #expect(base != DxccEntity(entityCode: 2, name: "X", countryCode: "XX", continents: ["EU"],
                                     cq: [15], itu: [28], lat: 1.0, lon: 2.0, primaryPrefix: "OK", adifDxcc: 1))
        #expect(base != DxccEntity(entityCode: 1, name: "Y", countryCode: "XX", continents: ["EU"],
                                     cq: [15], itu: [28], lat: 1.0, lon: 2.0, primaryPrefix: "OK", adifDxcc: 1))
        #expect(base != DxccEntity(entityCode: 1, name: "X", countryCode: "XX", continents: ["AS"],
                                     cq: [15], itu: [28], lat: 1.0, lon: 2.0, primaryPrefix: "OK", adifDxcc: 1))
        #expect(base != DxccEntity(entityCode: 1, name: "X", countryCode: "XX", continents: ["EU"],
                                     cq: [14], itu: [28], lat: 1.0, lon: 2.0, primaryPrefix: "OK", adifDxcc: 1))
        #expect(base != DxccEntity(entityCode: 1, name: "X", countryCode: "XX", continents: ["EU"],
                                     cq: [15], itu: [27], lat: 1.0, lon: 2.0, primaryPrefix: "OK", adifDxcc: 1))
        #expect(base != DxccEntity(entityCode: 1, name: "X", countryCode: "XX", continents: ["EU"],
                                     cq: [15], itu: [28], lat: 9.0, lon: 2.0, primaryPrefix: "OK", adifDxcc: 1))
        #expect(base != DxccEntity(entityCode: 1, name: "X", countryCode: "XX", continents: ["EU"],
                                     cq: [15], itu: [28], lat: 1.0, lon: 9.0, primaryPrefix: "OK", adifDxcc: 1))
        #expect(base != DxccEntity(entityCode: 1, name: "X", countryCode: "XX", continents: ["EU"],
                                     cq: [15], itu: [28], lat: 1.0, lon: 2.0, primaryPrefix: "OL", adifDxcc: 1))
        #expect(base != DxccEntity(entityCode: 1, name: "X", countryCode: "XX", continents: ["EU"],
                                     cq: [15], itu: [28], lat: 1.0, lon: 2.0, primaryPrefix: "OK", adifDxcc: nil))
        #expect(base != DxccEntity(entityCode: 1, name: "X", countryCode: "YY", continents: ["EU"],
                                     cq: [15], itu: [28], lat: 1.0, lon: 2.0, primaryPrefix: "OK", adifDxcc: 1))
    }

    /// `null` in a Java record = `nil` in Swift; an empty list is not the same as a missing one.
    @Test func missingListIsNotEmptyList() {
        let without = DxccEntity(entityCode: 1, name: nil, countryCode: nil, continents: nil,
                             cq: nil, itu: nil, lat: .nan, lon: .nan, primaryPrefix: nil, adifDxcc: nil)
        let blankOnes = DxccEntity(entityCode: 1, name: nil, countryCode: nil, continents: [],
                                 cq: [], itu: [], lat: .nan, lon: .nan, primaryPrefix: nil, adifDxcc: nil)
        #expect(without != blankOnes)
    }

    // MARK: error type

    @Test func errorCarriesCzechMessageAndCause() {
        let failure = DxccError(message: "Nelze parsovat DXCC data", cause: "neuzavřené pole")
        #expect(failure.message == "Nelze parsovat DXCC data")
        #expect(failure.kind == .parse)
        #expect(failure.cause == "neuzavřené pole")
        #expect(failure.description.contains("Nelze parsovat DXCC data"))
        #expect(failure.description.contains("neuzavřené pole"))
    }

    /// The second kind of error exists only because the Java `DxccResolver.fromStream`
    /// throws `NullPointerException` (not `DxccException`) for a missing `dxcc` field
    /// (and both types for a `null` element of that array) (measured). Swift has no `NPE`,
    /// so the situation has to be distinguished some other way.
    @Test func nullPointerIsItsOwnKind() {
        let failure = DxccError(kind: .nullPointer, message: "Data DXCC neobsahují pole dxcc")
        #expect(failure.kind == .nullPointer)
        #expect(failure != DxccError(message: "Data DXCC neobsahují pole dxcc"))
    }
}
