// Generated by a maintainer-only probe from the probe output
// (profile-merge-probe.tsv, rows CLASS/PROP/ENUM). Do not edit; regenerate.

extension ProfileMergeSchema {

    /// Jackson's bean deserializers of v1.1.1 reachable from `AppConfig`, by Java class name (without the
    /// hand-maintained Swift-only properties, see `ProfileMergeSchema.swiftOnlyProperties`).
    static let generatedClasses: [String: BeanClass] = {
        var table: [String: BeanClass] = [:]
        table["cz.ok1xoe.maccontestlogger.config.AppConfig"] = appConfig()
        table["cz.ok1xoe.maccontestlogger.config.WindowGeometry"] = windowGeometry()
        table["cz.ok1xoe.maccontestlogger.config.BandNote"] = bandNote()
        table["cz.ok1xoe.maccontestlogger.config.RigConfig"] = rigConfig()
        table["cz.ok1xoe.maccontestlogger.config.WsjtxConfig"] = wsjtxConfig()
        table["cz.ok1xoe.maccontestlogger.config.DigitalConfig"] = digitalConfig()
        table["cz.ok1xoe.maccontestlogger.config.AdifUdpConfig"] = adifUdpConfig()
        table["cz.ok1xoe.maccontestlogger.config.ClubLogConfig"] = clubLogConfig()
        table["cz.ok1xoe.maccontestlogger.config.StationConfig"] = stationConfig()
        table["cz.ok1xoe.maccontestlogger.config.CwKeyerConfig"] = cwKeyerConfig()
        table["cz.ok1xoe.maccontestlogger.config.VoiceKeyerConfig"] = voiceKeyerConfig()
        table["cz.ok1xoe.maccontestlogger.config.InfoWindowConfig"] = infoWindowConfig()
        table["cz.ok1xoe.maccontestlogger.config.BroadcastConfig"] = broadcastConfig()
        table["cz.ok1xoe.maccontestlogger.config.DxClusterConfig"] = dxClusterConfig()
        table["cz.ok1xoe.maccontestlogger.config.ContestSetup"] = contestSetup()
        table["cz.ok1xoe.maccontestlogger.config.RunModeConfig"] = runModeConfig()
        table["cz.ok1xoe.maccontestlogger.config.AntennaEntry"] = antennaEntry()
        table["cz.ok1xoe.maccontestlogger.config.MapConfig"] = mapConfig()
        table["cz.ok1xoe.maccontestlogger.config.N1mmRecvConfig"] = n1mmRecvConfig()
        table["cz.ok1xoe.maccontestlogger.config.TransverterEntry"] = transverterEntry()
        table["cz.ok1xoe.maccontestlogger.config.HamQthConfig"] = hamQthConfig()
        table["cz.ok1xoe.maccontestlogger.config.QrzConfig"] = qrzConfig()
        table["cz.ok1xoe.maccontestlogger.config.ClusterConfig"] = clusterConfig()
        table["cz.ok1xoe.maccontestlogger.config.EsmConfig"] = esmConfig()
        table["cz.ok1xoe.maccontestlogger.config.FunctionKeyMessage"] = functionKeyMessage()
        table["cz.ok1xoe.maccontestlogger.config.DxClusterCommand"] = dxClusterCommand()
        table["cz.ok1xoe.maccontestlogger.config.DxClusterFavorite"] = dxClusterFavorite()
        table["cz.ok1xoe.maccontestlogger.config.BlacklistEntry"] = blacklistEntry()
        table["cz.ok1xoe.maccontestlogger.config.SkedEntry"] = skedEntry()
        return table
    }()

    /// The enum types: constants by ordinal and in the order of `CompactStringObjectMap.keys()` (the order of
    /// Jackson's "not one of the values accepted" message).
    static let enums: [String: EnumType] = {
        var table: [String: EnumType] = [:]
        table["cz.ok1xoe.maccontestlogger.config.PinState"] = EnumType(constants: ["UNSET", "ON", "OFF"],
                                  keys: ["UNSET", "OFF", "ON"])
        table["cz.ok1xoe.maccontestlogger.config.ConnectionMode"] = EnumType(constants: ["LAUNCH_DAEMON", "CONNECT_RUNNING"],
                                  keys: ["LAUNCH_DAEMON", "CONNECT_RUNNING"])
        table["cz.ok1xoe.maccontestlogger.config.SerialParity"] = EnumType(constants: ["NONE", "EVEN", "ODD", "MARK", "SPACE"],
                                  keys: ["NONE", "EVEN", "MARK", "SPACE", "ODD"])
        table["cz.ok1xoe.maccontestlogger.config.FlowControl"] = EnumType(constants: ["AUTO", "NONE", "XONXOFF", "HARDWARE"],
                                  keys: ["HARDWARE", "XONXOFF", "AUTO", "NONE"])
        table["cz.ok1xoe.maccontestlogger.config.DigitalConfig$Engine"] = EnumType(constants: ["NONE", "FLDIGI"],
                                  keys: ["NONE", "FLDIGI"])
        table["cz.ok1xoe.maccontestlogger.config.CwKeyerConfig$Method"] = EnumType(constants: ["NONE", "CAT", "WINKEYER"],
                                  keys: ["WINKEYER", "CAT", "NONE"])
        table["cz.ok1xoe.maccontestlogger.keyer.CutStyle"] = EnumType(constants: ["LEADING_T", "LEADING_O", "ALL_T", "ALL_O", "TN", "ON", "TAN", "TAEN", "TAUEDN"],
                                  keys: ["TAN", "ALL_T", "TAUEDN", "TN", "LEADING_T", "ON", "ALL_O", "TAEN", "LEADING_O"])
        table["cz.ok1xoe.maccontestlogger.contest.engine.OperatingGuard$Enforcement"] = EnumType(constants: ["OFF", "WARN", "BLOCK"],
                                  keys: ["BLOCK", "WARN", "OFF"])
        table["cz.ok1xoe.maccontestlogger.cluster.Interlock$Scope"] = EnumType(constants: ["NONE", "ALL", "SAME_BAND"],
                                  keys: ["NONE", "ALL", "SAME_BAND"])
        table["cz.ok1xoe.maccontestlogger.contest.engine.OperatingGuard$StationType"] = EnumType(constants: ["NONE", "RUN", "MULT"],
                                  keys: ["MULT", "RUN", "NONE"])
        return table
    }()

    private static func appConfig() -> BeanClass {
        let known: [String] = [
            "windowGeometry",
            "recordContest",
            "antennaViaRig",
            "rotorUdpPort",
            "recordingsDir",
            "bandNotes",
            "keyBindings",
            "rig",
            "wsjtx",
            "scoreReportingUrl",
            "databasesDir",
            "digital",
            "cwSpeedStep",
            "adifUdp",
            "rig2",
            "rttyAfsk",
            "rxAudioDevice",
            "tuneStepCwHz",
            "clubLog",
            "rotorUdpHost",
            "tuneStepSsbHz",
            "lastDatabase",
            "station",
            "cwKeyer",
            "voiceKeyer",
            "scpFile",
            "infoWindow",
            "modeRule",
            "goals",
            "broadcast",
            "footswitchPort",
            "scoreReportingBreakdown",
            "dxCluster",
            "contestSetups",
            "ntpServer",
            "runMode",
            "contestDataDir",
            "antennas",
            "autoReloadLastContest",
            "language",
            "openWindows",
            "map",
            "cwPitchHz",
            "scoreReportingEnabled",
            "n1mmRecv",
            "otrspPort",
            "transverters",
            "hamQth",
            "callHistoryFile",
            "themeAccent",
            "rotatorHost",
            "autoBackupKeep",
            "footswitchAction",
            "qrz",
            "cluster",
            "autoBackupDir",
            "esm",
            "scoreReportingMinutes",
            "themeMode",
            "footswitchPin",
            "ritClearAfterLog",
            "ntpCorrectQsoTime",
            "radioMode",
            "autoBackupMinutes",
            "dataMode",
            "ttsVoice",
            "rotatorPort",
            "rotorUdpName",
            "modeAlways",
            "beepOnDupe",
        ]
        var properties: [Property] = []
        properties.append(Property("windowGeometry", .map(.bean("cz.ok1xoe.maccontestlogger.config.WindowGeometry")), .fieldDefault))
        properties.append(Property("recordContest", .boolean, .fieldDefault))
        properties.append(Property("antennaViaRig", .boolean, .fieldDefault))
        properties.append(Property("rotorUdpPort", .int, .fieldDefault))
        properties.append(Property("recordingsDir", .string, .fieldDefault))
        properties.append(Property("bandNotes", .list(.bean("cz.ok1xoe.maccontestlogger.config.BandNote")), .fieldDefault))
        properties.append(Property("keyBindings", .map(.string), .fieldDefault))
        properties.append(Property("rig", .bean("cz.ok1xoe.maccontestlogger.config.RigConfig"), .null))
        properties.append(Property("wsjtx", .bean("cz.ok1xoe.maccontestlogger.config.WsjtxConfig"), .fieldDefault))
        properties.append(Property("scoreReportingUrl", .string, .fieldDefault))
        properties.append(Property("databasesDir", .string, .fieldDefault))
        properties.append(Property("digital", .bean("cz.ok1xoe.maccontestlogger.config.DigitalConfig"), .fieldDefault))
        properties.append(Property("cwSpeedStep", .int, .fieldDefault))
        properties.append(Property("adifUdp", .bean("cz.ok1xoe.maccontestlogger.config.AdifUdpConfig"), .fieldDefault))
        properties.append(Property("rig2", .bean("cz.ok1xoe.maccontestlogger.config.RigConfig"), .fieldDefault))
        properties.append(Property("rttyAfsk", .boolean, .fieldDefault))
        properties.append(Property("rxAudioDevice", .string, .fieldDefault))
        properties.append(Property("tuneStepCwHz", .int, .fieldDefault))
        properties.append(Property("clubLog", .bean("cz.ok1xoe.maccontestlogger.config.ClubLogConfig"), .fieldDefault))
        properties.append(Property("rotorUdpHost", .string, .fieldDefault))
        properties.append(Property("tuneStepSsbHz", .int, .fieldDefault))
        properties.append(Property("lastDatabase", .string, .fieldDefault))
        properties.append(Property("station", .bean("cz.ok1xoe.maccontestlogger.config.StationConfig"), .null))
        properties.append(Property("cwKeyer", .bean("cz.ok1xoe.maccontestlogger.config.CwKeyerConfig"), .fieldDefault))
        properties.append(Property("voiceKeyer", .bean("cz.ok1xoe.maccontestlogger.config.VoiceKeyerConfig"), .fieldDefault))
        properties.append(Property("scpFile", .string, .fieldDefault))
        properties.append(Property("infoWindow", .bean("cz.ok1xoe.maccontestlogger.config.InfoWindowConfig"), .fieldDefault))
        properties.append(Property("modeRule", .string, .fieldDefault))
        properties.append(Property("goals", .map(.integer), .fieldDefault))
        properties.append(Property("broadcast", .bean("cz.ok1xoe.maccontestlogger.config.BroadcastConfig"), .fieldDefault))
        properties.append(Property("footswitchPort", .string, .fieldDefault))
        properties.append(Property("scoreReportingBreakdown", .boolean, .value(.bool(false))))
        properties.append(Property("dxCluster", .bean("cz.ok1xoe.maccontestlogger.config.DxClusterConfig"), .fieldDefault))
        properties.append(Property("contestSetups", .map(.bean("cz.ok1xoe.maccontestlogger.config.ContestSetup")), .fieldDefault))
        properties.append(Property("ntpServer", .string, .value(.string(""))))
        properties.append(Property("runMode", .bean("cz.ok1xoe.maccontestlogger.config.RunModeConfig"), .fieldDefault))
        properties.append(Property("contestDataDir", .string, .null))
        properties.append(Property("antennas", .list(.bean("cz.ok1xoe.maccontestlogger.config.AntennaEntry")), .fieldDefault))
        properties.append(Property("autoReloadLastContest", .boolean, .fieldDefault))
        properties.append(Property("language", .string, .fieldDefault))
        properties.append(Property("openWindows", .list(.string), .value(.array([]))))
        properties.append(Property("map", .bean("cz.ok1xoe.maccontestlogger.config.MapConfig"), .fieldDefault))
        properties.append(Property("cwPitchHz", .int, .fieldDefault))
        properties.append(Property("scoreReportingEnabled", .boolean, .fieldDefault))
        properties.append(Property("n1mmRecv", .bean("cz.ok1xoe.maccontestlogger.config.N1mmRecvConfig"), .fieldDefault))
        properties.append(Property("otrspPort", .string, .fieldDefault))
        properties.append(Property("transverters", .list(.bean("cz.ok1xoe.maccontestlogger.config.TransverterEntry")), .fieldDefault))
        properties.append(Property("hamQth", .bean("cz.ok1xoe.maccontestlogger.config.HamQthConfig"), .fieldDefault))
        properties.append(Property("callHistoryFile", .string, .fieldDefault))
        properties.append(Property("themeAccent", .string, .fieldDefault))
        properties.append(Property("rotatorHost", .string, .fieldDefault))
        properties.append(Property("autoBackupKeep", .int, .fieldDefault))
        properties.append(Property("footswitchAction", .string, .fieldDefault))
        properties.append(Property("qrz", .bean("cz.ok1xoe.maccontestlogger.config.QrzConfig"), .fieldDefault))
        properties.append(Property("cluster", .bean("cz.ok1xoe.maccontestlogger.config.ClusterConfig"), .null))
        properties.append(Property("autoBackupDir", .string, .fieldDefault))
        properties.append(Property("esm", .bean("cz.ok1xoe.maccontestlogger.config.EsmConfig"), .fieldDefault))
        properties.append(Property("scoreReportingMinutes", .int, .value(.int(2))))
        properties.append(Property("themeMode", .string, .fieldDefault))
        properties.append(Property("footswitchPin", .string, .fieldDefault))
        properties.append(Property("ritClearAfterLog", .boolean, .value(.bool(false))))
        properties.append(Property("ntpCorrectQsoTime", .boolean, .fieldDefault))
        properties.append(Property("radioMode", .string, .fieldDefault))
        properties.append(Property("autoBackupMinutes", .int, .value(.int(0))))
        properties.append(Property("dataMode", .string, .fieldDefault))
        properties.append(Property("ttsVoice", .string, .fieldDefault))
        properties.append(Property("rotatorPort", .int, .fieldDefault))
        properties.append(Property("rotorUdpName", .string, .fieldDefault))
        properties.append(Property("modeAlways", .string, .fieldDefault))
        properties.append(Property("beepOnDupe", .boolean, .fieldDefault))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.AppConfig", known: known, properties: properties)
    }

    private static func windowGeometry() -> BeanClass {
        let known: [String] = [
            "x",
            "y",
            "width",
            "height",
        ]
        var properties: [Property] = []
        properties.append(Property("x", .int, .fieldDefault))
        properties.append(Property("y", .int, .fieldDefault))
        properties.append(Property("width", .int, .fieldDefault))
        properties.append(Property("height", .int, .fieldDefault))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.WindowGeometry", known: known, properties: properties)
    }

    private static func bandNote() -> BeanClass {
        let known: [String] = [
            "band",
            "freqKHz",
            "text",
        ]
        var properties: [Property] = []
        properties.append(Property("band", .string, .fieldDefault))
        properties.append(Property("freqKHz", .double, .fieldDefault))
        properties.append(Property("text", .string, .fieldDefault))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.BandNote", known: known, properties: properties)
    }

    private static func rigConfig() -> BeanClass {
        let known: [String] = [
            "port",
            "dtr",
            "mode",
            "host",
            "model",
            "modelLabel",
            "parity",
            "baud",
            "flowControl",
            "dataBits",
            "rts",
            "device",
            "stopBits",
        ]
        var properties: [Property] = []
        properties.append(Property("port", .int, .value(.int(0))))
        properties.append(Property("dtr", .enumeration("cz.ok1xoe.maccontestlogger.config.PinState"), .null))
        properties.append(Property("mode", .enumeration("cz.ok1xoe.maccontestlogger.config.ConnectionMode"), .null))
        properties.append(Property("host", .string, .null))
        properties.append(Property("model", .int, .value(.int(0))))
        properties.append(Property("modelLabel", .string, .null))
        properties.append(Property("parity", .enumeration("cz.ok1xoe.maccontestlogger.config.SerialParity"), .null))
        properties.append(Property("baud", .int, .value(.int(0))))
        properties.append(Property("flowControl", .enumeration("cz.ok1xoe.maccontestlogger.config.FlowControl"), .null))
        properties.append(Property("dataBits", .int, .value(.int(0))))
        properties.append(Property("rts", .enumeration("cz.ok1xoe.maccontestlogger.config.PinState"), .null))
        properties.append(Property("device", .string, .null))
        properties.append(Property("stopBits", .int, .value(.int(0))))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.RigConfig", known: known, properties: properties)
    }

    private static func wsjtxConfig() -> BeanClass {
        let known: [String] = [
            "receiveBind",
            "sendEnabled",
            "sendTargets",
            "receiveEnabled",
        ]
        var properties: [Property] = []
        properties.append(Property("receiveBind", .string, .value(.string(""))))
        properties.append(Property("sendEnabled", .boolean, .fieldDefault))
        properties.append(Property("sendTargets", .string, .fieldDefault))
        properties.append(Property("receiveEnabled", .boolean, .fieldDefault))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.WsjtxConfig", known: known, properties: properties)
    }

    private static func digitalConfig() -> BeanClass {
        let known: [String] = [
            "spMessages",
            "engine",
            "fldigiHost",
            "fldigiPort",
            "runMessages",
        ]
        var properties: [Property] = []
        properties.append(Property("spMessages", .list(.bean("cz.ok1xoe.maccontestlogger.config.FunctionKeyMessage")), .fieldDefault))
        properties.append(Property("engine", .enumeration("cz.ok1xoe.maccontestlogger.config.DigitalConfig$Engine"), .fieldDefault))
        properties.append(Property("fldigiHost", .string, .fieldDefault))
        properties.append(Property("fldigiPort", .int, .fieldDefault))
        properties.append(Property("runMessages", .list(.bean("cz.ok1xoe.maccontestlogger.config.FunctionKeyMessage")), .fieldDefault))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.DigitalConfig", known: known, properties: properties)
    }

    private static func adifUdpConfig() -> BeanClass {
        let known: [String] = [
            "receiveBind",
            "receiveEnabled",
        ]
        var properties: [Property] = []
        properties.append(Property("receiveBind", .string, .value(.string(""))))
        properties.append(Property("receiveEnabled", .boolean, .fieldDefault))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.AdifUdpConfig", known: known, properties: properties)
    }

    private static func clubLogConfig() -> BeanClass {
        let known: [String] = [
            "enabled",
            "callsign",
            "email",
            "apiKey",
            "appPassword",
        ]
        var properties: [Property] = []
        properties.append(Property("enabled", .boolean, .fieldDefault))
        properties.append(Property("callsign", .string, .fieldDefault))
        properties.append(Property("email", .string, .fieldDefault))
        properties.append(Property("apiKey", .string, .fieldDefault))
        properties.append(Property("appPassword", .string, .fieldDefault))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.ClubLogConfig", known: known, properties: properties)
    }

    private static func stationConfig() -> BeanClass {
        let known: [String] = [
            "zip",
            "gridSquare",
            "operator",
            "power",
            "name",
            "latitude",
            "antHeight",
            "longitude",
            "state",
            "country",
            "cqZone",
            "email",
            "address1",
            "call",
            "roverQth",
            "license",
            "antenna",
            "city",
            "ituZone",
            "asl",
            "address2",
            "stationTxRx",
            "arrlSection",
            "club",
        ]
        var properties: [Property] = []
        properties.append(Property("zip", .string, .fieldDefault))
        properties.append(Property("gridSquare", .string, .null))
        properties.append(Property("operator", .string, .null))
        properties.append(Property("power", .string, .fieldDefault))
        properties.append(Property("name", .string, .null))
        properties.append(Property("latitude", .string, .fieldDefault))
        properties.append(Property("antHeight", .string, .fieldDefault))
        properties.append(Property("longitude", .string, .fieldDefault))
        properties.append(Property("state", .string, .fieldDefault))
        properties.append(Property("country", .string, .fieldDefault))
        properties.append(Property("cqZone", .string, .fieldDefault))
        properties.append(Property("email", .string, .fieldDefault))
        properties.append(Property("address1", .string, .fieldDefault))
        properties.append(Property("call", .string, .null))
        properties.append(Property("roverQth", .string, .fieldDefault))
        properties.append(Property("license", .string, .fieldDefault))
        properties.append(Property("antenna", .string, .fieldDefault))
        properties.append(Property("city", .string, .fieldDefault))
        properties.append(Property("ituZone", .string, .fieldDefault))
        properties.append(Property("asl", .string, .fieldDefault))
        properties.append(Property("address2", .string, .fieldDefault))
        properties.append(Property("stationTxRx", .string, .fieldDefault))
        properties.append(Property("arrlSection", .string, .fieldDefault))
        properties.append(Property("club", .string, .fieldDefault))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.StationConfig", known: known, properties: properties)
    }

    private static func cwKeyerConfig() -> BeanClass {
        let known: [String] = [
            "method",
            "leadingZeros",
            "speed",
            "cutNumbers",
            "spMessages",
            "cutStyle",
            "winkeyerPort",
            "runMessages",
        ]
        var properties: [Property] = []
        properties.append(Property("method", .enumeration("cz.ok1xoe.maccontestlogger.config.CwKeyerConfig$Method"), .value(.string("NONE"))))
        properties.append(Property("leadingZeros", .boolean, .fieldDefault))
        properties.append(Property("speed", .int, .value(.int(5))))
        properties.append(Property("cutNumbers", .boolean, .fieldDefault))
        properties.append(Property("spMessages", .list(.bean("cz.ok1xoe.maccontestlogger.config.FunctionKeyMessage")), .fieldDefault))
        properties.append(Property("cutStyle", .enumeration("cz.ok1xoe.maccontestlogger.keyer.CutStyle"), .fieldDefault))
        properties.append(Property("winkeyerPort", .string, .fieldDefault))
        properties.append(Property("runMessages", .list(.bean("cz.ok1xoe.maccontestlogger.config.FunctionKeyMessage")), .fieldDefault))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.CwKeyerConfig", known: known, properties: properties)
    }

    private static func voiceKeyerConfig() -> BeanClass {
        let known: [String] = [
            "inputDevice",
            "wavDir",
            "lettersPath",
            "outputDevice",
            "pttViaCat",
            "pttDelayMs",
            "maxRecordSeconds",
            "runMessages",
            "spMessages",
        ]
        var properties: [Property] = []
        properties.append(Property("inputDevice", .string, .fieldDefault))
        properties.append(Property("wavDir", .string, .fieldDefault))
        properties.append(Property("lettersPath", .string, .fieldDefault))
        properties.append(Property("outputDevice", .string, .fieldDefault))
        properties.append(Property("pttViaCat", .boolean, .value(.bool(false))))
        properties.append(Property("pttDelayMs", .int, .value(.int(0))))
        properties.append(Property("maxRecordSeconds", .int, .value(.int(1))))
        properties.append(Property("runMessages", .list(.bean("cz.ok1xoe.maccontestlogger.config.FunctionKeyMessage")), .fieldDefault))
        properties.append(Property("spMessages", .list(.bean("cz.ok1xoe.maccontestlogger.config.FunctionKeyMessage")), .fieldDefault))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.VoiceKeyerConfig", known: known, properties: properties)
    }

    private static func infoWindowConfig() -> BeanClass {
        let known: [String] = [
            "trendMinutes",
            "showGoals",
            "showCallframeSpot",
            "showCountryInfo",
            "showWwv",
            "showTimers",
            "offTimeMode",
            "showSunTimes",
            "showMessages",
        ]
        var properties: [Property] = []
        properties.append(Property("trendMinutes", .int, .fieldDefault))
        properties.append(Property("showGoals", .boolean, .value(.bool(false))))
        properties.append(Property("showCallframeSpot", .boolean, .value(.bool(false))))
        properties.append(Property("showCountryInfo", .boolean, .value(.bool(false))))
        properties.append(Property("showWwv", .boolean, .value(.bool(false))))
        properties.append(Property("showTimers", .boolean, .value(.bool(false))))
        properties.append(Property("offTimeMode", .string, .throwsNullPointer))
        properties.append(Property("showSunTimes", .boolean, .value(.bool(false))))
        properties.append(Property("showMessages", .boolean, .value(.bool(false))))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.InfoWindowConfig", known: known, properties: properties)
    }

    private static func broadcastConfig() -> BeanClass {
        let known: [String] = [
            "scoreTargets",
            "appInfoEnabled",
            "appInfoTargets",
            "radioEnabled",
            "radioTargets",
            "contactsEnabled",
            "contactsTargets",
            "scoreEnabled",
        ]
        var properties: [Property] = []
        properties.append(Property("scoreTargets", .string, .fieldDefault))
        properties.append(Property("appInfoEnabled", .boolean, .fieldDefault))
        properties.append(Property("appInfoTargets", .string, .fieldDefault))
        properties.append(Property("radioEnabled", .boolean, .fieldDefault))
        properties.append(Property("radioTargets", .string, .fieldDefault))
        properties.append(Property("contactsEnabled", .boolean, .fieldDefault))
        properties.append(Property("contactsTargets", .string, .fieldDefault))
        properties.append(Property("scoreEnabled", .boolean, .fieldDefault))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.BroadcastConfig", known: known, properties: properties)
    }

    private static func dxClusterConfig() -> BeanClass {
        let known: [String] = [
            "minSkimmers",
            "commands",
            "autoSplit",
            "wheelStepShiftHz",
            "selfSpotThresholdHz",
            "blacklistedSpotters",
            "lastFavorite",
            "favorites",
            "wheelStepHz",
            "showBandPlan",
            "spotBufferMinutes",
            "spotterBlacklist",
            "callBlacklist",
            "blacklistedCalls",
        ]
        var properties: [Property] = []
        properties.append(Property("minSkimmers", .int, .value(.int(0))))
        properties.append(Property("commands", .list(.bean("cz.ok1xoe.maccontestlogger.config.DxClusterCommand")), .fieldDefault))
        properties.append(Property("autoSplit", .boolean, .value(.bool(false))))
        properties.append(Property("wheelStepShiftHz", .int, .fieldDefault))
        properties.append(Property("selfSpotThresholdHz", .int, .fieldDefault))
        properties.append(Property("blacklistedSpotters", .list(.string), .fieldDefault))
        properties.append(Property("lastFavorite", .string, .fieldDefault))
        properties.append(Property("favorites", .list(.bean("cz.ok1xoe.maccontestlogger.config.DxClusterFavorite")), .fieldDefault))
        properties.append(Property("wheelStepHz", .int, .fieldDefault))
        properties.append(Property("showBandPlan", .boolean, .value(.bool(false))))
        properties.append(Property("spotBufferMinutes", .int, .fieldDefault))
        properties.append(Property("spotterBlacklist", .list(.bean("cz.ok1xoe.maccontestlogger.config.BlacklistEntry")), .fieldDefault))
        properties.append(Property("callBlacklist", .list(.bean("cz.ok1xoe.maccontestlogger.config.BlacklistEntry")), .fieldDefault))
        properties.append(Property("blacklistedCalls", .list(.string), .fieldDefault))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.DxClusterConfig", known: known, properties: properties)
    }

    private static func contestSetup() -> BeanClass {
        let known: [String] = [
            "soapbox",
            "startedAt",
            "tour",
            "sentExchange",
            "skeds",
            "endedAt",
            "category",
            "operators",
            "bonusStations",
        ]
        var properties: [Property] = []
        properties.append(Property("soapbox", .string, .fieldDefault))
        properties.append(Property("startedAt", .string, .fieldDefault))
        properties.append(Property("tour", .string, .fieldDefault))
        properties.append(Property("sentExchange", .map(.string), .fieldDefault))
        properties.append(Property("skeds", .list(.bean("cz.ok1xoe.maccontestlogger.config.SkedEntry")), .fieldDefault))
        properties.append(Property("endedAt", .string, .fieldDefault))
        properties.append(Property("category", .map(.string), .fieldDefault))
        properties.append(Property("operators", .string, .fieldDefault))
        properties.append(Property("bonusStations", .list(.string), .fieldDefault))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.ContestSetup", known: known, properties: properties)
    }

    private static func runModeConfig() -> BeanClass {
        let known: [String] = [
            "autoSwitch",
            "runOnCqFrequency",
            "repeatSeconds",
        ]
        var properties: [Property] = []
        properties.append(Property("autoSwitch", .boolean, .value(.bool(false))))
        properties.append(Property("runOnCqFrequency", .boolean, .value(.bool(false))))
        properties.append(Property("repeatSeconds", .double, .value(.double(0.2))))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.RunModeConfig", known: known, properties: properties)
    }

    private static func antennaEntry() -> BeanClass {
        let known: [String] = [
            "name",
            "code",
            "bands",
            "sector",
        ]
        var properties: [Property] = []
        properties.append(Property("name", .string, .fieldDefault))
        properties.append(Property("code", .int, .fieldDefault))
        properties.append(Property("bands", .string, .fieldDefault))
        properties.append(Property("sector", .string, .fieldDefault))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.AntennaEntry", known: known, properties: properties)
    }

    private static func mapConfig() -> BeanClass {
        let known: [String] = [
            "scheme",
            "political",
        ]
        var properties: [Property] = []
        properties.append(Property("scheme", .string, .fieldDefault))
        properties.append(Property("political", .boolean, .fieldDefault))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.MapConfig", known: known, properties: properties)
    }

    private static func n1mmRecvConfig() -> BeanClass {
        let known: [String] = [
            "receiveBind",
            "receiveEnabled",
        ]
        var properties: [Property] = []
        properties.append(Property("receiveBind", .string, .value(.string(""))))
        properties.append(Property("receiveEnabled", .boolean, .fieldDefault))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.N1mmRecvConfig", known: known, properties: properties)
    }

    private static func transverterEntry() -> BeanClass {
        let known: [String] = [
            "enabled",
            "offsetKHz",
            "name",
            "ifLowKHz",
            "ifHighKHz",
        ]
        var properties: [Property] = []
        properties.append(Property("enabled", .boolean, .value(.bool(false))))
        properties.append(Property("offsetKHz", .long, .fieldDefault))
        properties.append(Property("name", .string, .fieldDefault))
        properties.append(Property("ifLowKHz", .long, .fieldDefault))
        properties.append(Property("ifHighKHz", .long, .fieldDefault))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.TransverterEntry", known: known, properties: properties)
    }

    private static func hamQthConfig() -> BeanClass {
        let known: [String] = [
            "enabled",
            "callModes",
            "password",
            "username",
            "fetchFields",
        ]
        var properties: [Property] = []
        properties.append(Property("enabled", .boolean, .value(.bool(false))))
        properties.append(Property("callModes", .list(.string), .value(.array([]))))
        properties.append(Property("password", .string, .fieldDefault))
        properties.append(Property("username", .string, .fieldDefault))
        properties.append(Property("fetchFields", .list(.string), .value(.array([]))))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.HamQthConfig", known: known, properties: properties)
    }

    private static func qrzConfig() -> BeanClass {
        let known: [String] = [
            "enabled",
            "callModes",
            "password",
            "username",
            "fetchFields",
        ]
        var properties: [Property] = []
        properties.append(Property("enabled", .boolean, .value(.bool(false))))
        properties.append(Property("callModes", .list(.string), .value(.array([]))))
        properties.append(Property("password", .string, .fieldDefault))
        properties.append(Property("username", .string, .fieldDefault))
        properties.append(Property("fetchFields", .list(.string), .value(.array([]))))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.QrzConfig", known: known, properties: properties)
    }

    private static func clusterConfig() -> BeanClass {
        let known: [String] = [
            "enabled",
            "shareSpots",
            "ruleEnforcement",
            "username",
            "interlock",
            "password",
            "stationType",
            "stationId",
            "brokerHost",
            "serialServer",
            "tls",
            "port",
        ]
        var properties: [Property] = []
        properties.append(Property("enabled", .boolean, .fieldDefault))
        properties.append(Property("shareSpots", .boolean, .value(.bool(false))))
        properties.append(Property("ruleEnforcement", .enumeration("cz.ok1xoe.maccontestlogger.contest.engine.OperatingGuard$Enforcement"), .fieldDefault))
        properties.append(Property("username", .string, .null))
        properties.append(Property("interlock", .enumeration("cz.ok1xoe.maccontestlogger.cluster.Interlock$Scope"), .fieldDefault))
        properties.append(Property("password", .string, .null))
        properties.append(Property("stationType", .enumeration("cz.ok1xoe.maccontestlogger.contest.engine.OperatingGuard$StationType"), .fieldDefault))
        properties.append(Property("stationId", .string, .null))
        properties.append(Property("brokerHost", .string, .null))
        properties.append(Property("serialServer", .boolean, .fieldDefault))
        properties.append(Property("tls", .boolean, .fieldDefault))
        properties.append(Property("port", .int, .value(.int(0))))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.ClusterConfig", known: known, properties: properties)
    }

    private static func esmConfig() -> BeanClass {
        let known: [String] = [
            "enabled",
            "spCallOnce",
            "workDupes",
        ]
        var properties: [Property] = []
        properties.append(Property("enabled", .boolean, .fieldDefault))
        properties.append(Property("spCallOnce", .boolean, .fieldDefault))
        properties.append(Property("workDupes", .boolean, .value(.bool(false))))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.EsmConfig", known: known, properties: properties)
    }

    private static func functionKeyMessage() -> BeanClass {
        let known: [String] = [
            "label",
            "text",
        ]
        var properties: [Property] = []
        properties.append(Property("label", .string, .fieldDefault))
        properties.append(Property("text", .string, .fieldDefault))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.FunctionKeyMessage", known: known, properties: properties)
    }

    private static func dxClusterCommand() -> BeanClass {
        let known: [String] = [
            "command",
            "label",
        ]
        var properties: [Property] = []
        properties.append(Property("command", .string, .fieldDefault))
        properties.append(Property("label", .string, .fieldDefault))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.DxClusterCommand", known: known, properties: properties)
    }

    private static func dxClusterFavorite() -> BeanClass {
        let known: [String] = [
            "port",
            "parallel",
            "host",
            "login",
            "name",
            "password",
        ]
        var properties: [Property] = []
        properties.append(Property("port", .int, .value(.int(0))))
        properties.append(Property("parallel", .boolean, .fieldDefault))
        properties.append(Property("host", .string, .fieldDefault))
        properties.append(Property("login", .string, .fieldDefault))
        properties.append(Property("name", .string, .fieldDefault))
        properties.append(Property("password", .string, .fieldDefault))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.DxClusterFavorite", known: known, properties: properties)
    }

    private static func blacklistEntry() -> BeanClass {
        let known: [String] = [
            "value",
            "note",
            "addedAtUtc",
        ]
        var properties: [Property] = []
        properties.append(Property("value", .string, .fieldDefault))
        properties.append(Property("note", .string, .fieldDefault))
        properties.append(Property("addedAtUtc", .string, .fieldDefault))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.BlacklistEntry", known: known, properties: properties)
    }

    private static func skedEntry() -> BeanClass {
        let known: [String] = [
            "atUtc",
            "note",
            "mode",
            "freqHz",
            "id",
            "call",
        ]
        var properties: [Property] = []
        properties.append(Property("atUtc", .string, .fieldDefault))
        properties.append(Property("note", .string, .fieldDefault))
        properties.append(Property("mode", .string, .fieldDefault))
        properties.append(Property("freqHz", .long, .fieldDefault))
        properties.append(Property("id", .string, .fieldDefault))
        properties.append(Property("call", .string, .fieldDefault))
        return BeanClass(name: "cz.ok1xoe.maccontestlogger.config.SkedEntry", known: known, properties: properties)
    }
}
