import Foundation
import Testing
@testable import MCLCore

/// The `ScoreCheck` core against Java v1.1.1 over synthetic edge logs.
///
/// The reference `Fixtures/scorecheck-edge-java.tsv` is the output of the probe
/// a maintainer-only probe (procedure in the README there):
/// - rows `L` — each log from `Fixtures/scorecheck-edge/` (generated by `make_edge_logs.py`)
///   via `scoreCheck` (strict UTF-8, `skipReason`, `evaluate`, an exception = a log error)
///   in two DXCC modes: `json` (a directory with only `dxcc.json` = `dxcc-test.json`) and `cty`
///   (a directory with `cty.dat` = `scorecheck-cty-mini.dat`), both via `loadDxcc`;
/// - rows `F` — helper functions (`stripBlank`, `stripTrailingYear`, `parseLong`, `band`, `mode`,
///   `header`, `detectOwnGrid`, `isChecklog`, `skipReason`) over inputs from `functions.txt`.
///
/// The whole row is compared as text (the gate tuple + the error text even for `EXC`).
@Suite struct ScoreCheckMeasuredTests {

    static func ctyMini() throws -> Data {
        let url = try #require(Bundle.module.url(forResource: "scorecheck-cty-mini", withExtension: "dat"))
        return try Data(contentsOf: url)
    }

    private static func reference() throws -> [[String]] {
        let url = try #require(Bundle.module.url(forResource: "scorecheck-edge-java", withExtension: "tsv"))
        let text = try String(contentsOf: url, encoding: .utf8)
        return text.split(separator: "\n", omittingEmptySubsequences: true).map {
            $0.split(separator: "\t", omittingEmptySubsequences: false).map(String.init)
        }
    }

    @Test func logsMatchJava() throws {
        let rows = try Self.reference()
        let edgeDir = try #require(Bundle.module.url(forResource: "scorecheck-edge", withExtension: nil))
        let files = try FileManager.default.contentsOfDirectory(atPath: edgeDir.path).sorted()
        #expect(files.count == 74)

        let root = FileManager.default.temporaryDirectory
            .appendingPathComponent("scorecheck-edge-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: root) }
        let jsonDir = root.appendingPathComponent("json")
        let ctyDir = root.appendingPathComponent("cty")
        try FileManager.default.createDirectory(at: jsonDir, withIntermediateDirectories: true)
        try FileManager.default.createDirectory(at: ctyDir, withIntermediateDirectories: true)
        try DxccTestFixture.data().write(to: jsonDir.appendingPathComponent("dxcc.json"))
        try Self.ctyMini().write(to: ctyDir.appendingPathComponent("cty.dat"))

        let contestData = try SessionFixture.contestData()
        let defs = try ContestCatalog.fromDir(contestData.appendingPathComponent("contests"))
        var checked = 0
        for (tag, dir) in [("json", jsonDir), ("cty", ctyDir)] {
            let loaded = try #require(ScoreCheck.loadDxcc(directory: dir))
            let source = rows.first { $0.first == "dxcc" && $0[1] == tag }
            #expect(source?[2] == (loaded.source == .ctyDat ? "cty" : "json"), "\(tag)")
            let registry = try MultiplierSetRegistry(dxcc: loaded.lookup)
                .loadDir(contestData.appendingPathComponent("multipliers"))
            let expected = Dictionary(uniqueKeysWithValues: rows.filter { $0.first == "L" && $0[1] == tag }
                .map { ($0[2], $0[3...].joined(separator: "\t")) })
            #expect(expected.count == files.count, "\(tag)")
            for file in files {
                let data = try Data(contentsOf: edgeDir.appendingPathComponent(file))
                let outcome = ScoreCheck.check(fileName: file, data: data, definitions: defs,
                                               dxcc: loaded.lookup, registry: registry)
                #expect(Self.row(outcome) == expected[file], "\(tag) \(file)")
                checked += 1
            }
        }
        #expect(checked == 2 * files.count)
    }

    @Test func functionsMatchJava() throws {
        let rows = try Self.reference().filter { $0.first == "F" }
        #expect(rows.count == 177)
        for row in rows {
            let fn = row[1]
            let input = Self.unescape(row[2])
            let arg = row.count == 5 ? row[3] : nil
            let expected = row[row.count - 1]
            let actual: String?
            switch fn {
            case "stripBlank": actual = ScoreCheck.stripBlank(input)
            case "stripTrailingYear": actual = ScoreCheck.stripTrailingYear(input)
            case "parseLong": actual = ScoreCheck.parseLong(input).map { String($0) }
            case "band": actual = ScoreCheck.band(input)
            case "mode": actual = ScoreCheck.mode(input)
            case "header":
                let key = try #require(arg)
                do throws(ScoreCheck.Failure) {
                    actual = try ScoreCheck.header(input, key)
                } catch {
                    actual = "EXC " + error.javaClass + ": " + error.message
                }
            case "detectOwnGrid":
                let sent = try #require(arg.flatMap { Int($0) })
                actual = ScoreCheck.detectOwnGrid(input, sent: sent)
            case "isChecklog": actual = ScoreCheck.isChecklog(input) ? "true" : "false"
            case "skipReason": actual = ScoreCheck.skipReason(input)
            default:
                Issue.record("unknown function \(fn)")
                continue
            }
            #expect(Self.escape(actual) == expected, "\(fn) \(row[2])")
        }
    }

    // MARK: - probe format

    /// A probe `L` row without the first three columns (`L`, mode, file).
    static func row(_ outcome: ScoreCheck.LogOutcome) -> String {
        let r = outcome.result
        let groups = r.multByGroup.entries.map { escape($0.key) + "=" + ($0.value.map { String($0) } ?? "null") }
        let error: String?
        if outcome.status == .exception {
            error = (outcome.exceptionClass ?? "?") + ": " + (r.error ?? "null")
        } else {
            error = r.error
        }
        let columns: [String] = [
            outcome.status.rawValue, escape(r.contest), String(r.qsoCount), String(r.qsoPoints),
            String(r.multTotal), groups.joined(separator: ","), String(r.computed),
            r.claimed.map { String($0) } ?? "\\N", r.pass ? "true" : "false",
            String(r.unresolvedCalls.count), escape(outcome.skipReason), escape(error),
        ]
        return columns.joined(separator: "\t")
    }

    /// The probe's Java `esc`: `\` → `\\`, outside `0x20..0x7E` → `\uXXXX` by UTF-16, `nil` → `\N`.
    static func escape(_ text: String?) -> String {
        guard let text else { return "\\N" }
        var out = ""
        for unit in text.utf16 {
            if unit == 0x5C {
                out += "\\\\"
            } else if unit >= 0x20 && unit < 0x7F {
                out.unicodeScalars.append(Unicode.Scalar(UInt8(unit)))
            } else {
                let hex = String(unit, radix: 16)
                out += "\\u" + String(repeating: "0", count: 4 - hex.count) + hex
            }
        }
        return out
    }

    /// The inverse of `escape` (inputs are valid UTF-16, surrogate pairs are composed).
    static func unescape(_ text: String) -> String {
        var units: [UInt16] = []
        let chars = Array(text.utf16)
        var i = 0
        while i < chars.count {
            if chars[i] == 0x5C && i + 1 < chars.count {
                let next = chars[i + 1]
                if next == 0x75 { // u
                    let hex = String(decoding: chars[(i + 2)..<(i + 6)], as: UTF16.self)
                    units.append(UInt16(hex, radix: 16) ?? 0)
                    i += 6
                    continue
                }
                switch next {
                case 0x74: units.append(0x09)
                case 0x6E: units.append(0x0A)
                case 0x72: units.append(0x0D)
                default: units.append(next)
                }
                i += 2
                continue
            }
            units.append(chars[i])
            i += 1
        }
        return String(decoding: units, as: UTF16.self)
    }
}
