// Generated by a maintainer-only probe from `out-en_US.tsv` — do not edit.

/// Rows of the `ProbeRigctld` probe (`key\tvalue`, ASCII, `\uXXXX` by UTF-16 units).
enum RigctldProbeRows {
    static let tsv: String = #"""
basic.1	RigState[freqHz=14074000, mode=SSB, rawMode=USB, passband=2400, split=false, txFreqHz=0]
basic.2	ok
basic.3	ok
basic.4	ok
basic.5	ok
basic.6	ok
basic.7	ok
basic.8	ok
basic.9	ok
basic.10	ok
basic.11	true
basic.12	false
basic.13	EXC CatException: Chyba z\u00E1pisu p\u0159\u00EDkazu 'f' do rigctld <- java.net.SocketException: Socket closed
basic.14	EXC CatException: Chyba z\u00E1pisu p\u0159\u00EDkazu 'F 1' do rigctld <- java.net.SocketException: Socket closed
basic.sent	f|m|s|F 14200000|M LSB 0|M USB 0|M USB 0|T 1|T 0|b CQ TEST ?? 5NN|\u005Cstop_morse|L KEYSPD 28|Y 2 0|V VFOB|V VFOA|G XCHG|J -50|U RIT 1|J 0|U RIT 0
basic.log	\u2192 f|\u2190 14074000|\u2192 m|\u2190 USB|\u2190 2400|\u2192 s|\u2190 0|\u2190 VFOA|\u2192 F 14200000|\u2190 RPRT 0|\u2192 M LSB 0|\u2190 RPRT 0|\u2192 M USB 0|\u2190 RPRT 0|\u2192 M USB 0|\u2190 RPRT 0|\u2192 T 1|\u2190 RPRT 0|\u2192 T 0|\u2190 RPRT 0|\u2192 b CQ TEST \u017E\uD83D\uDE00 5NN|\u2190 RPRT 0|\u2192 \u005Cstop_morse|\u2190 RPRT 0|\u2192 L KEYSPD 28|\u2190 RPRT 0|\u2192 Y 2 0|\u2190 RPRT 0|\u2192 V VFOB|\u2190 RPRT 0|\u2192 V VFOA|\u2190 RPRT 0|\u2192 G XCHG|\u2190 RPRT 0|\u2192 J -50|\u2190 RPRT 0|\u2192 U RIT 1|\u2190 RPRT 0|\u2192 J 0|\u2190 RPRT 0|\u2192 U RIT 0|\u2190 RPRT 0
numbers.1	RigState[freqHz=14074000, mode=DIGITAL, rawMode=pktusb, passband=0, split=true, txFreqHz=0]
numbers.2	RigState[freqHz=7012000, mode=null, rawMode=, passband=0, split=false, txFreqHz=0]
numbers.3	RigState[freqHz=0, mode=null, rawMode=??, passband=0, split=false, txFreqHz=0]
numbers.4	RigState[freqHz=1, mode=null, rawMode=VFOB, passband=0, split=false, txFreqHz=0]
numbers.5	RigState[freqHz=300, mode=null, rawMode=01, passband=0, split=false, txFreqHz=0]
numbers.sent	f|m|s|i|f|m|s|f|m|s|f|m|s|f|m|s
numbers.log	\u2192 f|\u2190 +14074000|\u2192 m|\u2190 pktusb|\u2190 abc|\u2192 s|\u2190 1|\u2190 VFOB|\u2192 i|\u2190 RPRT -9|\u2192 f|\u2190 7012000|\u2192 m|\u2190 |\u2190 RTTY|\u2192 s|\u2190 +300|\u2190 1|\u2192 f|\u2190 VFOB|\u2192 m|\u2190 ??|\u2190 |\u2192 s|\u2190 RTTY|\u2190 +300|\u2192 f|\u2190 01|\u2192 m|\u2190 VFOB|\u2190 14.074e6|\u2192 s|\u2190 |\u2190 RTTY|\u2192 f|\u2190 +300|\u2192 m|\u2190 01|\u2190 VFOB|\u2192 s|\u2190 9223372036854775808|\u2190 
modes.1	RigState[freqHz=14074000, mode=FT8, rawMode=PKTUSB, passband=500, split=false, txFreqHz=0]
modes.2	ok
modes.3	RigState[freqHz=14074000, mode=DIGITAL, rawMode=PKTUSB, passband=500, split=false, txFreqHz=0]
modes.4	ok
modes.sent	f|m|s|M PKTLSB 0|M PKTUSB 0|f|m|s|M RTTY 0
modes.log	\u2192 f|\u2190 14074000|\u2192 m|\u2190 PKTUSB|\u2190 500|\u2192 s|\u2190 0|\u2190 VFOA|\u2192 M PKTLSB 0|\u2190 RPRT 0|\u2192 M PKTUSB 0|\u2190 RPRT 0|\u2192 f|\u2190 14074000|\u2192 m|\u2190 PKTUSB|\u2190 500|\u2192 s|\u2190 0|\u2190 VFOA|\u2192 M RTTY 0|\u2190 RPRT 0
splitUnsupported.1	RigState[freqHz=14074000, mode=SSB, rawMode=USB, passband=2400, split=false, txFreqHz=0]
splitUnsupported.2	RigState[freqHz=14074000, mode=SSB, rawMode=USB, passband=2400, split=false, txFreqHz=0]
splitUnsupported.3	ok
splitUnsupported.4	RigState[freqHz=14074000, mode=SSB, rawMode=USB, passband=2400, split=false, txFreqHz=0]
splitUnsupported.5	RigState[freqHz=14074000, mode=SSB, rawMode=USB, passband=2400, split=false, txFreqHz=0]
splitUnsupported.6	ok
splitUnsupported.sent	f|m|s|f|m|S 1 VFOB|I 14030000|f|m|s|f|m|S 1 VFOB|S 0 VFOA|S 1 VFOB
splitUnsupported.log	\u2192 f|\u2190 14074000|\u2192 m|\u2190 USB|\u2190 2400|\u2192 s|\u2190 RPRT -11|\u2192 f|\u2190 14074000|\u2192 m|\u2190 USB|\u2190 2400|\u2192 S 1 VFOB|\u2190 RPRT 0|\u2192 I 14030000|\u2190 RPRT 0|\u2192 f|\u2190 14074000|\u2192 m|\u2190 USB|\u2190 2400|\u2192 s|\u2190 RPRT -11|\u2192 f|\u2190 14074000|\u2192 m|\u2190 USB|\u2190 2400|\u2192 S 1 VFOB|\u2190 RPRT 0|\u2192 S 0 VFOA|\u2190 RPRT 0|\u2192 S 1 VFOB|\u2190 RPRT 0
splitTx.1	RigState[freqHz=14074000, mode=SSB, rawMode=USB, passband=2400, split=false, txFreqHz=0]
splitTx.2	RigState[freqHz=14074000, mode=SSB, rawMode=USB, passband=2400, split=false, txFreqHz=0]
splitTx.3	RigState[freqHz=14074000, mode=SSB, rawMode=USB, passband=2400, split=false, txFreqHz=0]
splitTx.sent	f|m|s|f|m|f|m
splitTx.log	\u2192 f|\u2190 14074000|\u2192 m|\u2190 USB|\u2190 2400|\u2192 s|\u2190 RPRTX|\u2192 f|\u2190 14074000|\u2192 m|\u2190 USB|\u2190 2400|\u2192 f|\u2190 14074000|\u2192 m|\u2190 USB|\u2190 2400
rprt.1	ok
rprt.2	ok
rprt.3	ok
rprt.4	EXC CatException: rigctld odm\u00EDtl nastaven\u00ED frekvence: rprt 0
rprt.5	EXC CatException: rigctld odm\u00EDtl nastaven\u00ED frekvence: RPRT -1
rprt.6	EXC CatException: rigctld odm\u00EDtl nastaven\u00ED frekvence: RPRT  0
rprt.7	EXC CatException: rigctld odm\u00EDtl nastaven\u00ED frekvence: RPRT
rprt.sent	F 1|F 2|F 3|F 4|F 5|F 6|F 7
rprt.log	\u2192 F 1|\u2190 RPRT 0x|\u2192 F 2|\u2190 RPRT 0|\u2192 F 3|\u2190 RPRT 01|\u2192 F 4|\u2190 rprt 0|\u2192 F 5|\u2190 RPRT -1|\u2192 F 6|\u2190 RPRT  0|\u2192 F 7|\u2190 RPRT
setRejected.1	EXC CatException: rigctld odm\u00EDtl zapnut\u00ED splitu: RPRT -1
setRejected.2	EXC CatException: rigctld odm\u00EDtl vypnut\u00ED splitu: RPRT -1
setRejected.3	EXC CatException: rigctld odm\u00EDtl zakl\u00ED\u010Dov\u00E1n\u00ED (PTT): RPRT -1
setRejected.4	EXC CatException: rigctld odm\u00EDtl odkl\u00ED\u010Dov\u00E1n\u00ED (PTT): RPRT -1
setRejected.5	EXC CatException: rigctld odm\u00EDtl odesl\u00E1n\u00ED CW (rig mus\u00ED b\u00FDt v m\u00F3du CW): RPRT -1
setRejected.6	EXC CatException: rigctld odm\u00EDtl zastaven\u00ED CW: RPRT -11
setRejected.7	EXC CatException: rigctld odm\u00EDtl nastaven\u00ED rychlosti CW: RPRT -1
setRejected.8	EXC CatException: rigctld odm\u00EDtl p\u0159epnut\u00ED ant\u00E9ny: RPRT -1
setRejected.9	EXC CatException: rigctld odm\u00EDtl prohozen\u00ED VFO: RPRT -1
setRejected.10	EXC CatException: rigctld odm\u00EDtl nastaven\u00ED m\u00F3du: RPRT -1
setRejected.11	EXC CatException: rigctld odm\u00EDtl nastaven\u00ED RIT: RPRT -1
setRejected.12	ok
setRejected.sent	S 1 VFOB|S 0 VFOA|T 1|T 0|b CQ|\u005Cstop_morse|L KEYSPD 30|Y 9 0|G XCHG|M CW 0|J 10|V VFOB
setRejected.log	\u2192 S 1 VFOB|\u2190 RPRT -1|\u2192 S 0 VFOA|\u2190 RPRT -1|\u2192 T 1|\u2190 RPRT -1|\u2192 T 0|\u2190 RPRT -1|\u2192 b CQ|\u2190 RPRT -1|\u2192 \u005Cstop_morse|\u2190 RPRT -11|\u2192 L KEYSPD 30|\u2190 RPRT -1|\u2192 Y 9 0|\u2190 RPRT -1|\u2192 G XCHG|\u2190 RPRT -1|\u2192 M CW 0|\u2190 RPRT -1|\u2192 J 10|\u2190 RPRT -1|\u2192 V VFOB|\u2190 RPRT 0
splitTxRejected.1	EXC CatException: rigctld odm\u00EDtl nastaven\u00ED vys\u00EDlac\u00ED frekvence: RPRT -9
splitTxRejected.sent	S 1 VFOB|I 14030000
splitTxRejected.log	\u2192 S 1 VFOB|\u2190 RPRT 0|\u2192 I 14030000|\u2190 RPRT -9
otherVfo.1	ok
otherVfo.2	EXC CatException: rigctld odm\u00EDtl v\u00FDb\u011Br VFO B: RPRT -1
otherVfo.3	EXC CatException: rigctld odm\u00EDtl n\u00E1vrat na VFO A: RPRT -2
otherVfo.4	EXC CatException: rigctld odm\u00EDtl v\u00FDb\u011Br VFO B: RPRT -3
otherVfo.sent	V VFOB|F 7012000|V VFOA|V VFOB|V VFOB|F 7014000|V VFOA|V VFOB
otherVfo.log	\u2192 V VFOB|\u2190 RPRT 0|\u2192 F 7012000|\u2190 RPRT 0|\u2192 V VFOA|\u2190 RPRT 0|\u2192 V VFOB|\u2190 RPRT -1|\u2192 V VFOB|\u2190 RPRT 0|\u2192 F 7014000|\u2190 RPRT -1|\u2192 V VFOA|\u2190 RPRT -2|\u2192 V VFOB|\u2190 RPRT -3
otherVfoFirstRejected.1	EXC CatException: rigctld odm\u00EDtl v\u00FDb\u011Br VFO B: RPRT -1
otherVfoFirstRejected.sent	V VFOB
otherVfoFirstRejected.log	\u2192 V VFOB|\u2190 RPRT -1
eofMid.1	EXC CatException: rigctld ukon\u010Dil spojen\u00ED
eofMid.2	true
eofMid.3	EXC CatException: rigctld ukon\u010Dil spojen\u00ED
eofMid.4	EXC CatException: Chyba z\u00E1pisu p\u0159\u00EDkazu 'f' do rigctld <- java.net.SocketException: Broken pipe
eofMid.5	EXC CatException: Chyba z\u00E1pisu p\u0159\u00EDkazu 'F 1' do rigctld <- java.net.SocketException: Broken pipe
eofMid.sent	f|m
eofMid.log	\u2192 f|\u2190 14074000|\u2192 m|\u2190 USB|\u2192 f
eofSplit.1	EXC CatException: rigctld ukon\u010Dil spojen\u00ED
eofSplit.sent	f|m|s
eofSplit.log	\u2192 f|\u2190 14074000|\u2192 m|\u2190 USB|\u2190 2400|\u2192 s|\u2190 1
desync.1	EXC CatException: Chyba \u010Dten\u00ED odpov\u011Bdi z rigctld <- java.net.SocketTimeoutException: Read timed out
desync.2	RigState[freqHz=2400, mode=null, rawMode=14074000, passband=0, split=false, txFreqHz=0]
desync.3	RigState[freqHz=0, mode=null, rawMode=2400, passband=14074000, split=false, txFreqHz=0]
desync.4	true
desync.sent	f|m|f|m|s|f|m|s
desync.log	\u2192 f|\u2190 14074000|\u2192 m|\u2190 USB|\u2192 f|\u2190 2400|\u2192 m|\u2190 14074000|\u2190 USB|\u2192 s|\u2190 2400|\u2190 0|\u2192 f|\u2190 VFOA|\u2192 m|\u2190 2400|\u2190 14074000|\u2192 s|\u2190 USB|\u2190 2400
mRprt.1	EXC CatException: Chyba \u010Dten\u00ED odpov\u011Bdi z rigctld <- java.net.SocketTimeoutException: Read timed out
mRprt.2	EXC CatException: Chyba \u010Dten\u00ED odpov\u011Bdi z rigctld <- java.net.SocketTimeoutException: Read timed out
mRprt.sent	f|m|f|m
mRprt.log	\u2192 f|\u2190 14074000|\u2192 m|\u2190 RPRT -11|\u2192 f|\u2190 14074000|\u2192 m|\u2190 RPRT -11
ritSilent.1	EXC CatException: Chyba \u010Dten\u00ED odpov\u011Bdi z rigctld <- java.net.SocketTimeoutException: Read timed out
ritSilent.2	RigState[freqHz=14074000, mode=SSB, rawMode=USB, passband=2400, split=false, txFreqHz=0]
ritSilent.sent	J 5|U RIT 1|f|m|s
ritSilent.log	\u2192 J 5|\u2190 RPRT 0|\u2192 U RIT 1|\u2192 f|\u2190 14074000|\u2192 m|\u2190 USB|\u2190 2400|\u2192 s|\u2190 0|\u2190 VFOA
crSplit.1	RigState[freqHz=14074000, mode=SSB, rawMode=USB, passband=2400, split=false, txFreqHz=0]
crSplit.2	RigState[freqHz=0, mode=null, rawMode=7000000, passband=0, split=false, txFreqHz=0]
crSplit.sent	f|m|s|f|m|s
crSplit.log	\u2192 f|\u2190 14074000|\u2192 m|\u2190 USB|\u2190 2400|\u2192 s|\u2190 0|\u2190 VFOA|\u2192 f|\u2190 |\u2192 m|\u2190 7000000|\u2190 |\u2192 s|\u2190 CW|\u2190 100
bytes.1	RigState[freqHz=0, mode=null, rawMode=\uFFFDSB, passband=2400, split=false, txFreqHz=0]
bytes.sent	f|m|s
bytes.log	\u2192 f|\u2190 \uFFFD14074000|\u2192 m|\u2190 \uFFFDSB|\u2190 2400|\u2192 s|\u2190 0|\u2190 VFOA
logFails.1	EXC UncheckedIOException: Nelze zapsat do CAT logu: <dir>/blocker/cat.log <- java.nio.file.FileAlreadyExistsException: <dir>/blocker
logFails.2	RigState[freqHz=14074000, mode=null, rawMode=14074000, passband=0, split=false, txFreqHz=0]
logFails.3	RigState[freqHz=0, mode=null, rawMode=14074000, passband=0, split=false, txFreqHz=0]
logFails.sent	f|f|m|s|f|m|s
logFails.log	\u2192 f|\u2192 f|\u2190 14074000|\u2192 m|\u2190 14074000|\u2190 USB|\u2192 s|\u2190 2400|\u2190 0|\u2192 f|\u2190 VFOA|\u2192 m|\u2190 14074000|\u2190 USB|\u2192 s|\u2190 2400|\u2190 0
connect.refused	EXC CatException: Nelze se p\u0159ipojit k rigctld na localhost:<port> <- java.net.ConnectException: Connection refused
connect.range	EXC IllegalArgumentException: port out of range:70000
connect.rangeNeg	EXC IllegalArgumentException: port out of range:-1
connect.timeoutNeg	EXC IllegalArgumentException: connect: timeout can't be negative
connect.unknownHost	EXC CatException: Nelze se p\u0159ipojit k rigctld na rig.neexistuje.invalid:4600 <- java.net.UnknownHostException: rig.neexistuje.invalid
connect.nullHost	EXC IllegalArgumentException: hostname can't be null
port.free	false
port.blank	false
port.max	false
port.neg	false
port.invalid	false
port.listening	true
port.listening127	true
"""#

    /// Key → value.
    static let rows: [String: String] = {
        var out: [String: String] = [:]
        for line in tsv.split(separator: "\n") {
            let parts = line.split(separator: "\t", maxSplits: 1, omittingEmptySubsequences: false)
            out[String(parts[0])] = parts.count > 1 ? String(parts[1]) : ""
        }
        return out
    }()
}
